package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp01StudyEntrySectionAtoD;
import ni.org.ics.zip.appmovil.domain.Zp01StudyEntrySectionE;
import ni.org.ics.zip.appmovil.domain.Zp01StudyEntrySectionFtoK;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp01DBConstants;

import java.util.Date;

/**
 * Helper para el parseo del formulario Zp01StudyEntry
 * Todas las secciones: A-D, E y F-K
 * Created by FIRSTICT on 10/20/2016.
 * V1.0
 */
public class Zp01StudyEntryHelper {

    /**********************************************************/
    /********** PARA OBJETO Zp01StudyEntrySectionAtoD *********/
    /**********************************************************/
    public static ContentValues crearZp01StudyEntrySectionAtoDValues(Zp01StudyEntrySectionAtoD studyEntrySectionAtoD){
        ContentValues cv = new ContentValues();

        cv.put(Zp01DBConstants.recordId, studyEntrySectionAtoD.getRecordId());
        if (studyEntrySectionAtoD.getSeaVdate() != null) cv.put(Zp01DBConstants.seaVdate, studyEntrySectionAtoD.getSeaVdate().getTime());
        if (studyEntrySectionAtoD.getSeaPtdate() != null) cv.put(Zp01DBConstants.seaPtdate, studyEntrySectionAtoD.getSeaPtdate().getTime());
        cv.put(Zp01DBConstants.seaTresults, studyEntrySectionAtoD.getSeaTresults());
        if (studyEntrySectionAtoD.getSeaLmpdate() != null) cv.put(Zp01DBConstants.seaLmpdate, studyEntrySectionAtoD.getSeaLmpdate().getTime());
        cv.put(Zp01DBConstants.seaLmpunknown, studyEntrySectionAtoD.getSeaLmpunknown());
        cv.put(Zp01DBConstants.seaGaWeek, studyEntrySectionAtoD.getSeaGaWeek());
        cv.put(Zp01DBConstants.seaGaDay, studyEntrySectionAtoD.getSeaGaDay());
        if (studyEntrySectionAtoD.getSeaEddLmp() != null) cv.put(Zp01DBConstants.seaEddLmp, studyEntrySectionAtoD.getSeaEddLmp().getTime());
        cv.put(Zp01DBConstants.seaTriultrasound, studyEntrySectionAtoD.getSeaTriultrasound());
        cv.put(Zp01DBConstants.seaUltravailable, studyEntrySectionAtoD.getSeaUltravailable());
        cv.put(Zp01DBConstants.seaUltraDay, studyEntrySectionAtoD.getSeaUltraDay());
        cv.put(Zp01DBConstants.seaUltraMonth, studyEntrySectionAtoD.getSeaUltraMonth());
        cv.put(Zp01DBConstants.seaUltraYear, studyEntrySectionAtoD.getSeaUltraYear());
        cv.put(Zp01DBConstants.seaAgweeks, studyEntrySectionAtoD.getSeaAgweeks());
        cv.put(Zp01DBConstants.seaAgdays, studyEntrySectionAtoD.getSeaAgdays());
        if (studyEntrySectionAtoD.getSeaEdd() != null) cv.put(Zp01DBConstants.seaEdd, studyEntrySectionAtoD.getSeaEdd().getTime());
        cv.put(Zp01DBConstants.seaEddUsed, studyEntrySectionAtoD.getSeaEddUsed());
        cv.put(Zp01DBConstants.seaPreWt, studyEntrySectionAtoD.getSeaPreWt());
        cv.put(Zp01DBConstants.seaPrewtUnit, studyEntrySectionAtoD.getSeaPrewtUnit());
        cv.put(Zp01DBConstants.seaCurHt, studyEntrySectionAtoD.getSeaCurHt());
        cv.put(Zp01DBConstants.seaCurhtUnit, studyEntrySectionAtoD.getSeaCurhtUnit());
        cv.put(Zp01DBConstants.seaMotherWt, studyEntrySectionAtoD.getSeaMotherWt());
        cv.put(Zp01DBConstants.seaMotherwtUnit, studyEntrySectionAtoD.getSeaMotherwtUnit());
        cv.put(Zp01DBConstants.seaHem, studyEntrySectionAtoD.getSeaHem());
        cv.put(Zp01DBConstants.seaSystolic, studyEntrySectionAtoD.getSeaSystolic());
        cv.put(Zp01DBConstants.seaDiastolic, studyEntrySectionAtoD.getSeaDiastolic());
        cv.put(Zp01DBConstants.seaTemp, studyEntrySectionAtoD.getSeaTemp());
        cv.put(Zp01DBConstants.seaTmpUnit, studyEntrySectionAtoD.getSeaTmpUnit());
        cv.put(Zp01DBConstants.seaCity, studyEntrySectionAtoD.getSeaCity());
        cv.put(Zp01DBConstants.seaState, studyEntrySectionAtoD.getSeaState());
        cv.put(Zp01DBConstants.seaCountry, studyEntrySectionAtoD.getSeaCountry());
        cv.put(Zp01DBConstants.seaLive, studyEntrySectionAtoD.getSeaLive());
        cv.put(Zp01DBConstants.seaAgeLeave, studyEntrySectionAtoD.getSeaAgeLeave());
        cv.put(Zp01DBConstants.seaLeavena, studyEntrySectionAtoD.getSeaLeavena());
        cv.put(Zp01DBConstants.seaMstatus, studyEntrySectionAtoD.getSeaMstatus());
        cv.put(Zp01DBConstants.seaRace, studyEntrySectionAtoD.getSeaRace());
        cv.put(Zp01DBConstants.seaEthnicityOther, studyEntrySectionAtoD.getSeaEthnicityOther());
        cv.put(Zp01DBConstants.seaDegreeYou, studyEntrySectionAtoD.getSeaDegreeYou());
        cv.put(Zp01DBConstants.seaYdegreeYears, studyEntrySectionAtoD.getSeaYdegreeYears());
        cv.put(Zp01DBConstants.seaDegreeSpouse, studyEntrySectionAtoD.getSeaDegreeSpouse());
        cv.put(Zp01DBConstants.seaSdegreeYears, studyEntrySectionAtoD.getSeaSdegreeYears());

        return cv;
    }

    public static Zp01StudyEntrySectionAtoD crearZp01StudyEntrySectionAtoD(Cursor cursorAtoD){
        Zp01StudyEntrySectionAtoD studyEntrySectionAtoD = new Zp01StudyEntrySectionAtoD();
        studyEntrySectionAtoD.setRecordId(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.recordId)));
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaVdate))>0) studyEntrySectionAtoD.setSeaVdate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaVdate))));
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaPtdate))>0) studyEntrySectionAtoD.setSeaPtdate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaPtdate))));
        studyEntrySectionAtoD.setSeaTresults(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaTresults)));
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaLmpdate))>0) studyEntrySectionAtoD.setSeaLmpdate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaLmpdate))));
        studyEntrySectionAtoD.setSeaLmpunknown(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaLmpunknown)));
        if (cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaGaWeek))>0) studyEntrySectionAtoD.setSeaGaWeek(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaGaWeek)));
        studyEntrySectionAtoD.setSeaGaDay(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaGaDay))); //permite 0
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEddLmp))>0) studyEntrySectionAtoD.setSeaEddLmp(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEddLmp))));
        studyEntrySectionAtoD.setSeaTriultrasound(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaTriultrasound)));
        studyEntrySectionAtoD.setSeaUltravailable(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaUltravailable)));
        studyEntrySectionAtoD.setSeaUltraDay(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaUltraDay)));
        studyEntrySectionAtoD.setSeaUltraMonth(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaUltraMonth)));
        studyEntrySectionAtoD.setSeaUltraYear(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaUltraYear)));
        if (cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaAgweeks))>0) studyEntrySectionAtoD.setSeaAgweeks(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaAgweeks)));
        studyEntrySectionAtoD.setSeaAgdays(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaAgdays))); //permite 0
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEdd))>0) studyEntrySectionAtoD.setSeaEdd(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEdd))));
        studyEntrySectionAtoD.setSeaEddUsed(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEddUsed)));
        studyEntrySectionAtoD.setSeaPreWt(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaPreWt)));
        studyEntrySectionAtoD.setSeaPrewtUnit(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaPrewtUnit)));
        studyEntrySectionAtoD.setSeaCurHt(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaCurHt)));
        studyEntrySectionAtoD.setSeaCurhtUnit(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaCurhtUnit)));
        studyEntrySectionAtoD.setSeaMotherWt(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaMotherWt)));
        studyEntrySectionAtoD.setSeaMotherwtUnit(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaMotherwtUnit)));
        studyEntrySectionAtoD.setSeaHem(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaHem)));
        if (cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaSystolic))>0) studyEntrySectionAtoD.setSeaSystolic(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaSystolic)));
        if (cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaDiastolic))>0) studyEntrySectionAtoD.setSeaDiastolic(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaDiastolic)));
        studyEntrySectionAtoD.setSeaTemp(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaTemp)));
        studyEntrySectionAtoD.setSeaTmpUnit(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaTmpUnit)));
        studyEntrySectionAtoD.setSeaCity(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaCity)));
        studyEntrySectionAtoD.setSeaState(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaState)));
        studyEntrySectionAtoD.setSeaCountry(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaCountry)));
        studyEntrySectionAtoD.setSeaLive(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaLive)));
        studyEntrySectionAtoD.setSeaAgeLeave(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zp01DBConstants.seaAgeLeave))); //permite 0
        studyEntrySectionAtoD.setSeaLeavena(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaLeavena)));
        studyEntrySectionAtoD.setSeaMstatus(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaMstatus)));
        studyEntrySectionAtoD.setSeaRace(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaRace)));
        studyEntrySectionAtoD.setSeaEthnicityOther(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaEthnicityOther)));
        studyEntrySectionAtoD.setSeaDegreeYou(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaDegreeYou)));
        studyEntrySectionAtoD.setSeaYdegreeYears(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaYdegreeYears)));
        studyEntrySectionAtoD.setSeaDegreeSpouse(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zp01DBConstants.seaDegreeSpouse)));
        studyEntrySectionAtoD.setSeaSdegreeYears(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zp01DBConstants.seaSdegreeYears)));
        //Movil y Metadata
        if(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.recordDate))>0) studyEntrySectionAtoD.setRecordDate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.recordDate))));
        studyEntrySectionAtoD.setRecordUser(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.recordUser)));
        studyEntrySectionAtoD.setPasive(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        studyEntrySectionAtoD.setIdInstancia(cursorAtoD.getInt(cursorAtoD.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        studyEntrySectionAtoD.setInstancePath(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.FILE_PATH)));
        studyEntrySectionAtoD.setEstado(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.STATUS)));
        studyEntrySectionAtoD.setStart(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.START)));
        studyEntrySectionAtoD.setEnd(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.END)));
        studyEntrySectionAtoD.setSimserial(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        studyEntrySectionAtoD.setPhonenumber(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        studyEntrySectionAtoD.setDeviceid(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.TODAY))>0) studyEntrySectionAtoD.setToday(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.TODAY))));

        return studyEntrySectionAtoD;
    }

    /**********************************************************/
    /********** PARA OBJETO Zp01StudyEntrySectionE *********/
    /**********************************************************/
    public static ContentValues crearZp01StudyEntrySectionEValues(Zp01StudyEntrySectionE studyEntrySectionE){
        ContentValues cv = new ContentValues();
        cv.put(Zp01DBConstants.recordId, studyEntrySectionE.getRecordId());
        cv.put(Zp01DBConstants.seaDiseases, studyEntrySectionE.getSeaDiseases());
        cv.put(Zp01DBConstants.seaOtherSpecify, studyEntrySectionE.getSeaOtherSpecify());
        cv.put(Zp01DBConstants.seaHepatitis, studyEntrySectionE.getSeaHepatitis());
        if (studyEntrySectionE.getSeaHepatitisDate1()!=null) cv.put(Zp01DBConstants.seaHepatitisDate1, studyEntrySectionE.getSeaHepatitisDate1().getTime());
        if (studyEntrySectionE.getSeaHepatitisDate2()!=null) cv.put(Zp01DBConstants.seaHepatitisDate2, studyEntrySectionE.getSeaHepatitisDate2().getTime());
        if (studyEntrySectionE.getSeaHepatitisDate3()!=null) cv.put(Zp01DBConstants.seaHepatitisDate3, studyEntrySectionE.getSeaHepatitisDate3().getTime());
        cv.put(Zp01DBConstants.seaMeasles, studyEntrySectionE.getSeaMeasles());
        if (studyEntrySectionE.getSeaMeaslesDate1()!=null) cv.put(Zp01DBConstants.seaMeaslesDate1, studyEntrySectionE.getSeaMeaslesDate1().getTime());
        if (studyEntrySectionE.getSeaMeaslesDate2()!=null) cv.put(Zp01DBConstants.seaMeaslesDate2, studyEntrySectionE.getSeaMeaslesDate2().getTime());
        if (studyEntrySectionE.getSeaMeaslesDate3()!=null) cv.put(Zp01DBConstants.seaMeaslesDate3, studyEntrySectionE.getSeaMeaslesDate3().getTime());
        cv.put(Zp01DBConstants.seaChickenpox, studyEntrySectionE.getSeaChickenpox());
        if (studyEntrySectionE.getSeaChickenpoxDate1()!=null) cv.put(Zp01DBConstants.seaChickenpoxDate1, studyEntrySectionE.getSeaChickenpoxDate1().getTime());
        if (studyEntrySectionE.getSeaChickenpoxDate2()!=null) cv.put(Zp01DBConstants.seaChickenpoxDate2, studyEntrySectionE.getSeaChickenpoxDate2().getTime());
        if (studyEntrySectionE.getSeaChickenpoxDate3()!=null) cv.put(Zp01DBConstants.seaChickenpoxDate3, studyEntrySectionE.getSeaChickenpoxDate3().getTime());
        cv.put(Zp01DBConstants.seaInfluenza, studyEntrySectionE.getSeaInfluenza());
        if (studyEntrySectionE.getSeaInfluenzaDate1()!=null) cv.put(Zp01DBConstants.seaInfluenzaDate1, studyEntrySectionE.getSeaInfluenzaDate1().getTime());
        if (studyEntrySectionE.getSeaInfluenzaDate2()!=null) cv.put(Zp01DBConstants.seaInfluenzaDate2, studyEntrySectionE.getSeaInfluenzaDate2().getTime());
        if (studyEntrySectionE.getSeaInfluenzaDate3()!=null) cv.put(Zp01DBConstants.seaInfluenzaDate3, studyEntrySectionE.getSeaInfluenzaDate3().getTime());
        cv.put(Zp01DBConstants.seaYellow, studyEntrySectionE.getSeaYellow());
        if (studyEntrySectionE.getSeaYellowDate1()!=null) cv.put(Zp01DBConstants.seaYellowDate1, studyEntrySectionE.getSeaYellowDate1().getTime());
        if (studyEntrySectionE.getSeaYellowDate2()!=null) cv.put(Zp01DBConstants.seaYellowDate2, studyEntrySectionE.getSeaYellowDate2().getTime());
        if (studyEntrySectionE.getSeaYellowDate3()!=null) cv.put(Zp01DBConstants.seaYellowDate3, studyEntrySectionE.getSeaYellowDate3().getTime());
        cv.put(Zp01DBConstants.seaDengue, studyEntrySectionE.getSeaDengue());
        if (studyEntrySectionE.getSeaDengueDate1()!=null) cv.put(Zp01DBConstants.seaDengueDate1, studyEntrySectionE.getSeaDengueDate1().getTime());
        if (studyEntrySectionE.getSeaDengueDate2()!=null) cv.put(Zp01DBConstants.seaDengueDate2, studyEntrySectionE.getSeaDengueDate2().getTime());
        if (studyEntrySectionE.getSeaDengueDate3()!=null) cv.put(Zp01DBConstants.seaDengueDate3, studyEntrySectionE.getSeaDengueDate3().getTime());
        cv.put(Zp01DBConstants.seaVacOther, studyEntrySectionE.getSeaVacOther());
        cv.put(Zp01DBConstants.seaVacotherSpecify, studyEntrySectionE.getSeaVacotherSpecify());
        if (studyEntrySectionE.getSeaOtherDate1()!=null) cv.put(Zp01DBConstants.seaOtherDate1, studyEntrySectionE.getSeaOtherDate1().getTime());
        if (studyEntrySectionE.getSeaOtherDate2()!=null) cv.put(Zp01DBConstants.seaOtherDate2, studyEntrySectionE.getSeaOtherDate2().getTime());
        if (studyEntrySectionE.getSeaOtherDate3()!=null) cv.put(Zp01DBConstants.seaOtherDate3, studyEntrySectionE.getSeaOtherDate3().getTime());
        cv.put(Zp01DBConstants.seaRubella, studyEntrySectionE.getSeaRubella());
        if (studyEntrySectionE.getSeaRubellaDate1()!=null) cv.put(Zp01DBConstants.seaRubellaDate1, studyEntrySectionE.getSeaRubellaDate1().getTime());
        if (studyEntrySectionE.getSeaRubellaDate2()!=null) cv.put(Zp01DBConstants.seaRubellaDate2, studyEntrySectionE.getSeaRubellaDate2().getTime());
        if (studyEntrySectionE.getSeaRubellaDate3()!=null) cv.put(Zp01DBConstants.seaRubellaDate3, studyEntrySectionE.getSeaRubellaDate3().getTime());
        cv.put(Zp01DBConstants.seaRubellaDoc, studyEntrySectionE.getSeaRubellaDoc());
        cv.put(Zp01DBConstants.seaCmv, studyEntrySectionE.getSeaCmv());
        if (studyEntrySectionE.getSeaCmvDate1()!=null) cv.put(Zp01DBConstants.seaCmvDate1, studyEntrySectionE.getSeaCmvDate1().getTime());
        if (studyEntrySectionE.getSeaCmvDate2()!=null) cv.put(Zp01DBConstants.seaCmvDate2, studyEntrySectionE.getSeaCmvDate2().getTime());
        if (studyEntrySectionE.getSeaCmvDate3()!=null) cv.put(Zp01DBConstants.seaCmvDate3, studyEntrySectionE.getSeaCmvDate3().getTime());
        cv.put(Zp01DBConstants.seaCmvDoc, studyEntrySectionE.getSeaCmvDoc());
        cv.put(Zp01DBConstants.seaHerpes, studyEntrySectionE.getSeaHerpes());
        if (studyEntrySectionE.getSeaHerpesDate1()!=null )cv.put(Zp01DBConstants.seaHerpesDate1, studyEntrySectionE.getSeaHerpesDate1().getTime());
        if (studyEntrySectionE.getSeaHerpesDate2()!=null) cv.put(Zp01DBConstants.seaHerpesDate2, studyEntrySectionE.getSeaHerpesDate2().getTime());
        if (studyEntrySectionE.getSeaHerpesDate3()!=null) cv.put(Zp01DBConstants.seaHerpesDate3, studyEntrySectionE.getSeaHerpesDate3().getTime());
        cv.put(Zp01DBConstants.seaHerpesDoc, studyEntrySectionE.getSeaHerpesDoc());
        cv.put(Zp01DBConstants.seaParvovirus, studyEntrySectionE.getSeaParvovirus());
        if (studyEntrySectionE.getSeaParvovirusDate1()!=null) cv.put(Zp01DBConstants.seaParvovirusDate1, studyEntrySectionE.getSeaParvovirusDate1().getTime());
        if (studyEntrySectionE.getSeaParvovirusDate2()!=null) cv.put(Zp01DBConstants.seaParvovirusDate2, studyEntrySectionE.getSeaParvovirusDate2().getTime());
        if (studyEntrySectionE.getSeaParvovirusDate3()!=null) cv.put(Zp01DBConstants.seaParvovirusDate3, studyEntrySectionE.getSeaParvovirusDate3().getTime());
        cv.put(Zp01DBConstants.seaParvovirusDoc, studyEntrySectionE.getSeaParvovirusDoc());
        cv.put(Zp01DBConstants.seaToxoplasmosis, studyEntrySectionE.getSeaToxoplasmosis());
        if (studyEntrySectionE.getSeaToxoplasmosisDate1()!=null) cv.put(Zp01DBConstants.seaToxoplasmosisDate1, studyEntrySectionE.getSeaToxoplasmosisDate1().getTime());
        if (studyEntrySectionE.getSeaToxoplasmosisDate2()!=null) cv.put(Zp01DBConstants.seaToxoplasmosisDate2, studyEntrySectionE.getSeaToxoplasmosisDate2().getTime());
        if (studyEntrySectionE.getSeaToxoplasmosisDate3()!=null) cv.put(Zp01DBConstants.seaToxoplasmosisDate3, studyEntrySectionE.getSeaToxoplasmosisDate3().getTime());
        cv.put(Zp01DBConstants.seaToxoplasmosisDoc, studyEntrySectionE.getSeaToxoplasmosisDoc());
        cv.put(Zp01DBConstants.seaSyphillis, studyEntrySectionE.getSeaSyphillis());
        if (studyEntrySectionE.getSeaSyphillisDate1()!=null) cv.put(Zp01DBConstants.seaSyphillisDate1, studyEntrySectionE.getSeaSyphillisDate1().getTime());
        if (studyEntrySectionE.getSeaSyphillisDate2()!=null) cv.put(Zp01DBConstants.seaSyphillisDate2, studyEntrySectionE.getSeaSyphillisDate2().getTime());
        if (studyEntrySectionE.getSeaSyphillisDate3()!=null) cv.put(Zp01DBConstants.seaSyphillisDate3, studyEntrySectionE.getSeaSyphillisDate3().getTime());
        cv.put(Zp01DBConstants.seaSyphillisDoc, studyEntrySectionE.getSeaSyphillisDoc());
        cv.put(Zp01DBConstants.seaHiv, studyEntrySectionE.getSeaHiv());
        if (studyEntrySectionE.getSeaHivDate1()!=null) cv.put(Zp01DBConstants.seaHivDate1, studyEntrySectionE.getSeaHivDate1().getTime());
        if (studyEntrySectionE.getSeaHivDate2()!=null) cv.put(Zp01DBConstants.seaHivDate2, studyEntrySectionE.getSeaHivDate2().getTime());
        if (studyEntrySectionE.getSeaHivDate3()!=null) cv.put(Zp01DBConstants.seaHivDate3, studyEntrySectionE.getSeaHivDate3().getTime());
        cv.put(Zp01DBConstants.seaHivDoc, studyEntrySectionE.getSeaHivDoc());
        cv.put(Zp01DBConstants.seaZika, studyEntrySectionE.getSeaZika());
        if (studyEntrySectionE.getSeaZikaDate1()!=null) cv.put(Zp01DBConstants.seaZikaDate1, studyEntrySectionE.getSeaZikaDate1().getTime());
        if (studyEntrySectionE.getSeaZikaDate2()!=null) cv.put(Zp01DBConstants.seaZikaDate2, studyEntrySectionE.getSeaZikaDate2().getTime());
        if (studyEntrySectionE.getSeaZikaDate3()!=null) cv.put(Zp01DBConstants.seaZikaDate3, studyEntrySectionE.getSeaZikaDate3().getTime());
        cv.put(Zp01DBConstants.seaZikaDoc, studyEntrySectionE.getSeaZikaDoc());
        cv.put(Zp01DBConstants.seaChikung, studyEntrySectionE.getSeaChikung());
        if (studyEntrySectionE.getSeaChikungDate1()!=null) cv.put(Zp01DBConstants.seaChikungDate1, studyEntrySectionE.getSeaChikungDate1().getTime());
        if (studyEntrySectionE.getSeaChikungDate2()!=null) cv.put(Zp01DBConstants.seaChikungDate2, studyEntrySectionE.getSeaChikungDate2().getTime());
        if (studyEntrySectionE.getSeaChikungDate3()!=null) cv.put(Zp01DBConstants.seaChikungDate3, studyEntrySectionE.getSeaChikungDate3().getTime());
        cv.put(Zp01DBConstants.seaChikungDoc, studyEntrySectionE.getSeaChikungDoc());
        cv.put(Zp01DBConstants.seaInfluInfect, studyEntrySectionE.getSeaInfluInfect());
        if (studyEntrySectionE.getSeaInflueInfectDate1()!=null) cv.put(Zp01DBConstants.seaInflueInfectDate1, studyEntrySectionE.getSeaInflueInfectDate1().getTime());
        if (studyEntrySectionE.getSeaInfluInfectDate2()!=null) cv.put(Zp01DBConstants.seaInfluInfectDate2, studyEntrySectionE.getSeaInfluInfectDate2().getTime());
        if (studyEntrySectionE.getSeaInfluInfectDate3()!=null) cv.put(Zp01DBConstants.seaInfluInfectDate3, studyEntrySectionE.getSeaInfluInfectDate3().getTime());
        cv.put(Zp01DBConstants.seaInfluInfectDoc, studyEntrySectionE.getSeaInfluInfectDoc());
        cv.put(Zp01DBConstants.seaDengueInfect, studyEntrySectionE.getSeaDengueInfect());
        if (studyEntrySectionE.getSeaDengueInfectDate1()!=null)cv.put(Zp01DBConstants.seaDengueInfectDate1, studyEntrySectionE.getSeaDengueInfectDate1().getTime());
        if (studyEntrySectionE.getSeaDengueInfectDate2()!=null) cv.put(Zp01DBConstants.seaDengueInfectDate2, studyEntrySectionE.getSeaDengueInfectDate2().getTime());
        if (studyEntrySectionE.getSeaDengueInfectDate3()!=null) cv.put(Zp01DBConstants.seaDengueInfectDate3, studyEntrySectionE.getSeaDengueInfectDate3().getTime());
        cv.put(Zp01DBConstants.seaDengueInfectDoc, studyEntrySectionE.getSeaDengueInfectDoc());
        cv.put(Zp01DBConstants.seaFeverSymptom, studyEntrySectionE.getSeaFeverSymptom());
        cv.put(Zp01DBConstants.seaRash, studyEntrySectionE.getSeaRash());
        cv.put(Zp01DBConstants.seaItch, studyEntrySectionE.getSeaItch());
        cv.put(Zp01DBConstants.seaRashFirst, studyEntrySectionE.getSeaRashFirst());
        cv.put(Zp01DBConstants.seaRashDay, studyEntrySectionE.getSeaRashDay());
        cv.put(Zp01DBConstants.seaRashMonth, studyEntrySectionE.getSeaRashMonth());
        cv.put(Zp01DBConstants.seaRashYear, studyEntrySectionE.getSeaRashYear());
        cv.put(Zp01DBConstants.seaRashDuration, studyEntrySectionE.getSeaRashDuration());
        cv.put(Zp01DBConstants.seaRashSpread, studyEntrySectionE.getSeaRashSpread());
        cv.put(Zp01DBConstants.seaSpreadPart, studyEntrySectionE.getSeaSpreadPart());
        cv.put(Zp01DBConstants.seaFeverExperience, studyEntrySectionE.getSeaFeverExperience());
        cv.put(Zp01DBConstants.seaTempMeasure, studyEntrySectionE.getSeaTempMeasure());
        cv.put(Zp01DBConstants.seaHighTemp, studyEntrySectionE.getSeaHighTemp());
        cv.put(Zp01DBConstants.seaHightemUnit, studyEntrySectionE.getSeaHightemUnit());
        cv.put(Zp01DBConstants.seaTempunknown, studyEntrySectionE.getSeaTempunknown());
        cv.put(Zp01DBConstants.seaFeverDay, studyEntrySectionE.getSeaFeverDay());
        cv.put(Zp01DBConstants.seaFeverMonth, studyEntrySectionE.getSeaFeverMonth());
        cv.put(Zp01DBConstants.seaFeverYear, studyEntrySectionE.getSeaFeverYear());
        cv.put(Zp01DBConstants.seaFeverDuration, studyEntrySectionE.getSeaFeverDuration());
        cv.put(Zp01DBConstants.seaRedeyes, studyEntrySectionE.getSeaRedeyes());
        cv.put(Zp01DBConstants.seaRedeyesDay, studyEntrySectionE.getSeaRedeyesDay());
        cv.put(Zp01DBConstants.seaRedeyesMonth, studyEntrySectionE.getSeaRedeyesMonth());
        cv.put(Zp01DBConstants.seaRedeyesYear, studyEntrySectionE.getSeaRedeyesYear());
        cv.put(Zp01DBConstants.seaRedeyesDuration, studyEntrySectionE.getSeaRedeyesDuration());
        cv.put(Zp01DBConstants.seaOccurSame, studyEntrySectionE.getSeaOccurSame());
        cv.put(Zp01DBConstants.seaSameSymptom, studyEntrySectionE.getSeaSameSymptom());
        cv.put(Zp01DBConstants.seaJoint, studyEntrySectionE.getSeaJoint());
        cv.put(Zp01DBConstants.seaJointDay, studyEntrySectionE.getSeaJointDay());
        cv.put(Zp01DBConstants.seaJointMonth, studyEntrySectionE.getSeaJointMonth());
        cv.put(Zp01DBConstants.seaJointYear, studyEntrySectionE.getSeaJointYear());
        cv.put(Zp01DBConstants.seaJointDuration, studyEntrySectionE.getSeaJointDuration());
        cv.put(Zp01DBConstants.seaHeadache, studyEntrySectionE.getSeaHeadache());
        cv.put(Zp01DBConstants.seaHeadacheDay, studyEntrySectionE.getSeaHeadacheDay());
        cv.put(Zp01DBConstants.seaHeadacheMonth, studyEntrySectionE.getSeaHeadacheMonth());
        cv.put(Zp01DBConstants.seaHeadacheYear, studyEntrySectionE.getSeaHeadacheYear());
        cv.put(Zp01DBConstants.seaHeadacheDuration, studyEntrySectionE.getSeaHeadacheDuration());
        cv.put(Zp01DBConstants.seaSymptomOther, studyEntrySectionE.getSeaSymptomOther());
        cv.put(Zp01DBConstants.seaSpecifySymptom, studyEntrySectionE.getSeaSpecifySymptom());
        cv.put(Zp01DBConstants.seaOtherSymptom, studyEntrySectionE.getSeaOtherSymptom());
        cv.put(Zp01DBConstants.seaMedicare, studyEntrySectionE.getSeaMedicare());
        cv.put(Zp01DBConstants.seaCareDay, studyEntrySectionE.getSeaCareDay());
        cv.put(Zp01DBConstants.seaCareMonth, studyEntrySectionE.getSeaCareMonth());
        cv.put(Zp01DBConstants.seaCareYear, studyEntrySectionE.getSeaCareYear());
        cv.put(Zp01DBConstants.seaCareFacility, studyEntrySectionE.getSeaCareFacility());
        cv.put(Zp01DBConstants.seaHospitalized, studyEntrySectionE.getSeaHospitalized());
        cv.put(Zp01DBConstants.seaHospital, studyEntrySectionE.getSeaHospital());
        cv.put(Zp01DBConstants.seaDiagRubella, studyEntrySectionE.getSeaDiagRubella());
        cv.put(Zp01DBConstants.seaDiagDengue, studyEntrySectionE.getSeaDiagDengue());
        cv.put(Zp01DBConstants.seaDiagChikung, studyEntrySectionE.getSeaDiagChikung());
        cv.put(Zp01DBConstants.seaDiagZika, studyEntrySectionE.getSeaDiagZika());
        cv.put(Zp01DBConstants.seaDiagCytome, studyEntrySectionE.getSeaDiagCytome());
        cv.put(Zp01DBConstants.seaMedicine, studyEntrySectionE.getSeaMedicine());
        cv.put(Zp01DBConstants.seaMedcineName, studyEntrySectionE.getSeaMedcineName());
        cv.put(Zp01DBConstants.seaGuillainbarre, studyEntrySectionE.getSeaGuillainbarre());
        cv.put(Zp01DBConstants.seaTingling, studyEntrySectionE.getSeaTingling());
        cv.put(Zp01DBConstants.seaTinglingArm, studyEntrySectionE.getSeaTinglingArm());
        cv.put(Zp01DBConstants.seaTinglingLeg, studyEntrySectionE.getSeaTinglingLeg());
        cv.put(Zp01DBConstants.seaTinglingHand, studyEntrySectionE.getSeaTinglingHand());
        cv.put(Zp01DBConstants.seaTinglingFoot, studyEntrySectionE.getSeaTinglingFoot());
        cv.put(Zp01DBConstants.seaTinglingFace, studyEntrySectionE.getSeaTinglingFace());
        cv.put(Zp01DBConstants.seaTinglingOther, studyEntrySectionE.getSeaTinglingOther());
        cv.put(Zp01DBConstants.seaSensationMin, studyEntrySectionE.getSeaSensationMin());
        cv.put(Zp01DBConstants.seaSensationHr, studyEntrySectionE.getSeaSensationHr());
        cv.put(Zp01DBConstants.seaSenstaionDay, studyEntrySectionE.getSeaSenstaionDay());
        cv.put(Zp01DBConstants.seaInjury, studyEntrySectionE.getSeaInjury());
        cv.put(Zp01DBConstants.seaTinglingDay, studyEntrySectionE.getSeaTinglingDay());
        cv.put(Zp01DBConstants.seaTinglingMonth, studyEntrySectionE.getSeaTinglingMonth());
        cv.put(Zp01DBConstants.seaTinglingYear, studyEntrySectionE.getSeaTinglingYear());
        cv.put(Zp01DBConstants.seaTinglingDuration, studyEntrySectionE.getSeaTinglingDuration());
        cv.put(Zp01DBConstants.seaNumbness, studyEntrySectionE.getSeaNumbness());
        cv.put(Zp01DBConstants.seaNumbArm, studyEntrySectionE.getSeaNumbArm());
        cv.put(Zp01DBConstants.seaNumbLeg, studyEntrySectionE.getSeaNumbLeg());
        cv.put(Zp01DBConstants.seaNumbHand, studyEntrySectionE.getSeaNumbHand());
        cv.put(Zp01DBConstants.seaNumbFoot, studyEntrySectionE.getSeaNumbFoot());
        cv.put(Zp01DBConstants.seaNumbFace, studyEntrySectionE.getSeaNumbFace());
        cv.put(Zp01DBConstants.seaNumbOther, studyEntrySectionE.getSeaNumbOther());
        cv.put(Zp01DBConstants.seaNumbDay, studyEntrySectionE.getSeaNumbDay());
        cv.put(Zp01DBConstants.seaNumbMonth, studyEntrySectionE.getSeaNumbMonth());
        cv.put(Zp01DBConstants.seaNumbYear, studyEntrySectionE.getSeaNumbYear());
        cv.put(Zp01DBConstants.seaNumbDuration, studyEntrySectionE.getSeaNumbDuration());
        cv.put(Zp01DBConstants.seaParalysis, studyEntrySectionE.getSeaParalysis());
        cv.put(Zp01DBConstants.seaParaArm, studyEntrySectionE.getSeaParaArm());
        cv.put(Zp01DBConstants.seaParaLeg, studyEntrySectionE.getSeaParaLeg());
        cv.put(Zp01DBConstants.seaParaHand, studyEntrySectionE.getSeaParaHand());
        cv.put(Zp01DBConstants.seaParaFoot, studyEntrySectionE.getSeaParaFoot());
        cv.put(Zp01DBConstants.seaParaFace, studyEntrySectionE.getSeaParaFace());
        cv.put(Zp01DBConstants.seaParaOther, studyEntrySectionE.getSeaParaOther());
        cv.put(Zp01DBConstants.seaParaDay, studyEntrySectionE.getSeaParaDay());
        cv.put(Zp01DBConstants.seaParaMonth, studyEntrySectionE.getSeaParaMonth());
        cv.put(Zp01DBConstants.seaParaYear, studyEntrySectionE.getSeaParaYear());
        cv.put(Zp01DBConstants.seaParaDuration, studyEntrySectionE.getSeaParaDuration());

        return cv;
    }

    public static Zp01StudyEntrySectionE crearZp01StudyEntrySectionE(Cursor cursorE){
        Zp01StudyEntrySectionE studyEntrySectionE = new Zp01StudyEntrySectionE();
        studyEntrySectionE.setRecordId(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.recordId)));
        studyEntrySectionE.setSeaDiseases(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiseases)));
        studyEntrySectionE.setSeaOtherSpecify(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaOtherSpecify)));
        studyEntrySectionE.setSeaHepatitis(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate1))>0) studyEntrySectionE.setSeaHepatitisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate2))>0) studyEntrySectionE.setSeaHepatitisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate3))>0) studyEntrySectionE.setSeaHepatitisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHepatitisDate3))));
        studyEntrySectionE.setSeaMeasles(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaMeasles)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate1))>0) studyEntrySectionE.setSeaMeaslesDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate2))>0) studyEntrySectionE.setSeaMeaslesDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate3))>0) studyEntrySectionE.setSeaMeaslesDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaMeaslesDate3))));
        studyEntrySectionE.setSeaChickenpox(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpox)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate1))>0) studyEntrySectionE.setSeaChickenpoxDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate2))>0) studyEntrySectionE.setSeaChickenpoxDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate3))>0) studyEntrySectionE.setSeaChickenpoxDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChickenpoxDate3))));
        studyEntrySectionE.setSeaInfluenza(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenza)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate1))>0) studyEntrySectionE.setSeaInfluenzaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate2))>0) studyEntrySectionE.setSeaInfluenzaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate3))>0) studyEntrySectionE.setSeaInfluenzaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluenzaDate3))));
        studyEntrySectionE.setSeaYellow(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaYellow)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate1))>0) studyEntrySectionE.setSeaYellowDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate2))>0) studyEntrySectionE.setSeaYellowDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate3))>0) studyEntrySectionE.setSeaYellowDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaYellowDate3))));
        studyEntrySectionE.setSeaDengue(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDengue)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate1))>0) studyEntrySectionE.setSeaDengueDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate2))>0) studyEntrySectionE.setSeaDengueDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate3))>0) studyEntrySectionE.setSeaDengueDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueDate3))));
        studyEntrySectionE.setSeaVacOther(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaVacOther)));
        studyEntrySectionE.setSeaVacotherSpecify(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaVacotherSpecify)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate1))>0) studyEntrySectionE.setSeaOtherDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate2))>0) studyEntrySectionE.setSeaOtherDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate3))>0) studyEntrySectionE.setSeaOtherDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaOtherDate3))));
        studyEntrySectionE.setSeaRubella(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRubella)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate1))>0) studyEntrySectionE.setSeaRubellaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate2))>0) studyEntrySectionE.setSeaRubellaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate3))>0) studyEntrySectionE.setSeaRubellaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDate3))));
        studyEntrySectionE.setSeaRubellaDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRubellaDoc)));
        studyEntrySectionE.setSeaCmv(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCmv)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate1))>0) studyEntrySectionE.setSeaCmvDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate2))>0) studyEntrySectionE.setSeaCmvDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate3))>0) studyEntrySectionE.setSeaCmvDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDate3))));
        studyEntrySectionE.setSeaCmvDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCmvDoc)));
        studyEntrySectionE.setSeaHerpes(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHerpes)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate1))>0) studyEntrySectionE.setSeaHerpesDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate2))>0) studyEntrySectionE.setSeaHerpesDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate3))>0) studyEntrySectionE.setSeaHerpesDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDate3))));
        studyEntrySectionE.setSeaHerpesDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHerpesDoc)));
        studyEntrySectionE.setSeaParvovirus(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirus)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate1))>0) studyEntrySectionE.setSeaParvovirusDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate2))>0) studyEntrySectionE.setSeaParvovirusDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate3))>0) studyEntrySectionE.setSeaParvovirusDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDate3))));
        studyEntrySectionE.setSeaParvovirusDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParvovirusDoc)));
        studyEntrySectionE.setSeaToxoplasmosis(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate1))>0) studyEntrySectionE.setSeaToxoplasmosisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate2))>0) studyEntrySectionE.setSeaToxoplasmosisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate3))>0) studyEntrySectionE.setSeaToxoplasmosisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDate3))));
        studyEntrySectionE.setSeaToxoplasmosisDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaToxoplasmosisDoc)));
        studyEntrySectionE.setSeaSyphillis(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate1))>0) studyEntrySectionE.setSeaSyphillisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate2))>0) studyEntrySectionE.setSeaSyphillisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate3))>0) studyEntrySectionE.setSeaSyphillisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDate3))));
        studyEntrySectionE.setSeaSyphillisDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSyphillisDoc)));
        studyEntrySectionE.setSeaHiv(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHiv)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate1))>0) studyEntrySectionE.setSeaHivDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate2))>0) studyEntrySectionE.setSeaHivDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate3))>0) studyEntrySectionE.setSeaHivDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaHivDate3))));
        studyEntrySectionE.setSeaHivDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHivDoc)));
        studyEntrySectionE.setSeaZika(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaZika)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate1))>0) studyEntrySectionE.setSeaZikaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate2))>0) studyEntrySectionE.setSeaZikaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate3))>0) studyEntrySectionE.setSeaZikaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDate3))));
        studyEntrySectionE.setSeaZikaDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaZikaDoc)));
        studyEntrySectionE.setSeaChikung(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaChikung)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate1))>0) studyEntrySectionE.setSeaChikungDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate2))>0) studyEntrySectionE.setSeaChikungDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate3))>0) studyEntrySectionE.setSeaChikungDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDate3))));
        studyEntrySectionE.setSeaChikungDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaChikungDoc)));
        studyEntrySectionE.setSeaInfluInfect(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfect)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInflueInfectDate1))>0) studyEntrySectionE.setSeaInflueInfectDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInflueInfectDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfectDate2))>0) studyEntrySectionE.setSeaInfluInfectDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfectDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfectDate3))>0) studyEntrySectionE.setSeaInfluInfectDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfectDate3))));
        studyEntrySectionE.setSeaInfluInfectDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaInfluInfectDoc)));
        studyEntrySectionE.setSeaDengueInfect(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfect)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate1))>0) studyEntrySectionE.setSeaDengueInfectDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate2))>0) studyEntrySectionE.setSeaDengueInfectDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate3))>0) studyEntrySectionE.setSeaDengueInfectDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDate3))));
        studyEntrySectionE.setSeaDengueInfectDoc(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDengueInfectDoc)));
        studyEntrySectionE.setSeaFeverSymptom(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaFeverSymptom)));
        studyEntrySectionE.setSeaRash(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRash)));
        studyEntrySectionE.setSeaItch(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaItch)));
        studyEntrySectionE.setSeaRashFirst(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRashFirst)));
        studyEntrySectionE.setSeaRashDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRashDay)));
        studyEntrySectionE.setSeaRashMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRashMonth)));
        studyEntrySectionE.setSeaRashYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRashYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaRashDuration))>0) studyEntrySectionE.setSeaRashDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaRashDuration)));
        studyEntrySectionE.setSeaRashSpread(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRashSpread)));
        studyEntrySectionE.setSeaSpreadPart(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSpreadPart)));
        studyEntrySectionE.setSeaFeverExperience(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaFeverExperience)));
        studyEntrySectionE.setSeaTempMeasure(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTempMeasure)));
        if (cursorE.getFloat(cursorE.getColumnIndex(Zp01DBConstants.seaHighTemp))>0) studyEntrySectionE.setSeaHighTemp(cursorE.getFloat(cursorE.getColumnIndex(Zp01DBConstants.seaHighTemp)));
        studyEntrySectionE.setSeaHightemUnit(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHightemUnit)));
        studyEntrySectionE.setSeaTempunknown(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTempunknown)));
        studyEntrySectionE.setSeaFeverDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaFeverDay)));
        studyEntrySectionE.setSeaFeverMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaFeverMonth)));
        studyEntrySectionE.setSeaFeverYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaFeverYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaFeverDuration))>0) studyEntrySectionE.setSeaFeverDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaFeverDuration)));
        studyEntrySectionE.setSeaRedeyes(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyes)));
        studyEntrySectionE.setSeaRedeyesDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyesDay)));
        studyEntrySectionE.setSeaRedeyesMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyesMonth)));
        studyEntrySectionE.setSeaRedeyesYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyesYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyesDuration))>0) studyEntrySectionE.setSeaRedeyesDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaRedeyesDuration)));
        studyEntrySectionE.setSeaOccurSame(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaOccurSame)));
        studyEntrySectionE.setSeaSameSymptom(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSameSymptom)));
        studyEntrySectionE.setSeaJoint(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaJoint)));
        studyEntrySectionE.setSeaJointDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaJointDay)));
        studyEntrySectionE.setSeaJointMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaJointMonth)));
        studyEntrySectionE.setSeaJointYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaJointYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaJointDuration))>0) studyEntrySectionE.setSeaJointDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaJointDuration)));
        studyEntrySectionE.setSeaHeadache(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHeadache)));
        studyEntrySectionE.setSeaHeadacheDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHeadacheDay)));
        studyEntrySectionE.setSeaHeadacheMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHeadacheMonth)));
        studyEntrySectionE.setSeaHeadacheYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHeadacheYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaHeadacheDuration))>0) studyEntrySectionE.setSeaHeadacheDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaHeadacheDuration)));
        studyEntrySectionE.setSeaSymptomOther(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSymptomOther)));
        studyEntrySectionE.setSeaSpecifySymptom(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSpecifySymptom)));
        studyEntrySectionE.setSeaOtherSymptom(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaOtherSymptom)));
        studyEntrySectionE.setSeaMedicare(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaMedicare)));
        studyEntrySectionE.setSeaCareDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCareDay)));
        studyEntrySectionE.setSeaCareMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCareMonth)));
        studyEntrySectionE.setSeaCareYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCareYear)));
        studyEntrySectionE.setSeaCareFacility(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaCareFacility)));
        studyEntrySectionE.setSeaHospitalized(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHospitalized)));
        studyEntrySectionE.setSeaHospital(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaHospital)));
        studyEntrySectionE.setSeaDiagRubella(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiagRubella)));
        studyEntrySectionE.setSeaDiagDengue(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiagDengue)));
        studyEntrySectionE.setSeaDiagChikung(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiagChikung)));
        studyEntrySectionE.setSeaDiagZika(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiagZika)));
        studyEntrySectionE.setSeaDiagCytome(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaDiagCytome)));
        studyEntrySectionE.setSeaMedicine(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaMedicine)));
        studyEntrySectionE.setSeaMedcineName(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaMedcineName)));
        studyEntrySectionE.setSeaGuillainbarre(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaGuillainbarre)));
        studyEntrySectionE.setSeaTingling(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTingling)));
        studyEntrySectionE.setSeaTinglingArm(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingArm)));
        studyEntrySectionE.setSeaTinglingLeg(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingLeg)));
        studyEntrySectionE.setSeaTinglingHand(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingHand)));
        studyEntrySectionE.setSeaTinglingFoot(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingFoot)));
        studyEntrySectionE.setSeaTinglingFace(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingFace)));
        studyEntrySectionE.setSeaTinglingOther(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingOther)));
        studyEntrySectionE.setSeaSensationMin(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSensationMin)));
        studyEntrySectionE.setSeaSensationHr(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSensationHr)));
        studyEntrySectionE.setSeaSenstaionDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaSenstaionDay)));
        studyEntrySectionE.setSeaInjury(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaInjury)));
        studyEntrySectionE.setSeaTinglingDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingDay)));
        studyEntrySectionE.setSeaTinglingMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingMonth)));
        studyEntrySectionE.setSeaTinglingYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingDuration))>0) studyEntrySectionE.setSeaTinglingDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaTinglingDuration)));
        studyEntrySectionE.setSeaNumbness(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbness)));
        studyEntrySectionE.setSeaNumbArm(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbArm)));
        studyEntrySectionE.setSeaNumbLeg(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbLeg)));
        studyEntrySectionE.setSeaNumbHand(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbHand)));
        studyEntrySectionE.setSeaNumbFoot(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbFoot)));
        studyEntrySectionE.setSeaNumbFace(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbFace)));
        studyEntrySectionE.setSeaNumbOther(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbOther)));
        studyEntrySectionE.setSeaNumbDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbDay)));
        studyEntrySectionE.setSeaNumbMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbMonth)));
        studyEntrySectionE.setSeaNumbYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaNumbYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaNumbDuration))>0) studyEntrySectionE.setSeaNumbDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaNumbDuration)));
        studyEntrySectionE.setSeaParalysis(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParalysis)));
        studyEntrySectionE.setSeaParaArm(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaArm)));
        studyEntrySectionE.setSeaParaLeg(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaLeg)));
        studyEntrySectionE.setSeaParaHand(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaHand)));
        studyEntrySectionE.setSeaParaFoot(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaFoot)));
        studyEntrySectionE.setSeaParaFace(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaFace)));
        studyEntrySectionE.setSeaParaOther(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaOther)));
        studyEntrySectionE.setSeaParaDay(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaDay)));
        studyEntrySectionE.setSeaParaMonth(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaMonth)));
        studyEntrySectionE.setSeaParaYear(cursorE.getString(cursorE.getColumnIndex(Zp01DBConstants.seaParaYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaParaDuration))>0) studyEntrySectionE.setSeaParaDuration(cursorE.getInt(cursorE.getColumnIndex(Zp01DBConstants.seaParaDuration)));
        //Movil y Metadata
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))>0) studyEntrySectionE.setRecordDate(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))));
        studyEntrySectionE.setRecordUser(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.recordUser)));
        studyEntrySectionE.setPasive(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        studyEntrySectionE.setIdInstancia(cursorE.getInt(cursorE.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        studyEntrySectionE.setInstancePath(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.FILE_PATH)));
        studyEntrySectionE.setEstado(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.STATUS)));
        studyEntrySectionE.setStart(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.START)));
        studyEntrySectionE.setEnd(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.END)));
        studyEntrySectionE.setSimserial(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        studyEntrySectionE.setPhonenumber(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        studyEntrySectionE.setDeviceid(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))>0) studyEntrySectionE.setToday(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))));

        return studyEntrySectionE;
    }

    /**********************************************************/
    /********** PARA OBJETO Zp01StudyEntrySectionFtoK *********/
    /**********************************************************/
    public static ContentValues crearZp01StudyEntrySectionFtoKValues(Zp01StudyEntrySectionFtoK studyEntrySectionFtoK){
        ContentValues cv = new ContentValues();

        return cv;
    }

    public static Zp01StudyEntrySectionFtoK crearZp01StudyEntrySectionFtoK(Cursor cursorFtoK){
        Zp01StudyEntrySectionFtoK studyEntrySectionFtoK = new Zp01StudyEntrySectionFtoK();

        return studyEntrySectionFtoK;
    }
}
