package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp02BiospecimenCollection;
import ni.org.ics.zip.appmovil.domain.Zp02dInfantBiospecimenCollection;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp02DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 10/21/2016.
 * V1.0
 */
public class Zp02BiospecimenCollectionHelper {

    public static ContentValues crearZp02BiospecimenCollection(Zp02BiospecimenCollection biospecimenCollection){
        ContentValues cv = new ContentValues();

        cv.put(Zp02DBConstants.recordId, biospecimenCollection.getRecordId());
        cv.put(Zp02DBConstants.redcapEventName, biospecimenCollection.getRedcapEventName());
        if (biospecimenCollection.getBscDov()!=null) cv.put(Zp02DBConstants.bscDov, biospecimenCollection.getBscDov().getTime());
        cv.put(Zp02DBConstants.bscVisit, biospecimenCollection.getBscVisit());
        cv.put(Zp02DBConstants.bscMatBldCol, biospecimenCollection.getBscMatBldCol());
        cv.put(Zp02DBConstants.bscMatBldRsn, biospecimenCollection.getBscMatBldRsn());
        cv.put(Zp02DBConstants.bscMatBldSpecify, biospecimenCollection.getBscMatBldSpecify());
        cv.put(Zp02DBConstants.bscMatBldTyp1, biospecimenCollection.getBscMatBldTyp1());
        cv.put(Zp02DBConstants.bscMatBldId1, biospecimenCollection.getBscMatBldId1());
        cv.put(Zp02DBConstants.bscMatBldVol1, biospecimenCollection.getBscMatBldVol1());
        cv.put(Zp02DBConstants.bscMatBldTyp2, biospecimenCollection.getBscMatBldTyp2());
        cv.put(Zp02DBConstants.bscMatBldId2, biospecimenCollection.getBscMatBldId2());
        cv.put(Zp02DBConstants.bscMatBldVol2, biospecimenCollection.getBscMatBldVol2());
        cv.put(Zp02DBConstants.bscMatBldTyp3, biospecimenCollection.getBscMatBldTyp3());
        cv.put(Zp02DBConstants.bscMatBldId3, biospecimenCollection.getBscMatBldId3());
        cv.put(Zp02DBConstants.bscMatBldVol3, biospecimenCollection.getBscMatBldVol3());
        cv.put(Zp02DBConstants.bscMatBldTyp4, biospecimenCollection.getBscMatBldTyp4());
        cv.put(Zp02DBConstants.bscMatBldId4, biospecimenCollection.getBscMatBldId4());
        cv.put(Zp02DBConstants.bscMatBldVol4, biospecimenCollection.getBscMatBldVol4());
        cv.put(Zp02DBConstants.bscMatBldTyp5, biospecimenCollection.getBscMatBldTyp5());
        cv.put(Zp02DBConstants.bscMatBldId5, biospecimenCollection.getBscMatBldId5());
        cv.put(Zp02DBConstants.bscMatBldVol5, biospecimenCollection.getBscMatBldVol5());
        cv.put(Zp02DBConstants.bscMatBldTyp6, biospecimenCollection.getBscMatBldTyp6());
        cv.put(Zp02DBConstants.bscMatBldId6, biospecimenCollection.getBscMatBldId6());
        cv.put(Zp02DBConstants.bscMatBldVol6, biospecimenCollection.getBscMatBldVol6());
        cv.put(Zp02DBConstants.bscMatBldTyp7, biospecimenCollection.getBscMatBldTyp7());
        cv.put(Zp02DBConstants.bscMatBldId7, biospecimenCollection.getBscMatBldId7());
        cv.put(Zp02DBConstants.bscMatBldVol7, biospecimenCollection.getBscMatBldVol7());
        cv.put(Zp02DBConstants.bscMatBldTyp8, biospecimenCollection.getBscMatBldTyp8());
        cv.put(Zp02DBConstants.bscMatBldId8, biospecimenCollection.getBscMatBldId8());
        cv.put(Zp02DBConstants.bscMatBldVol8, biospecimenCollection.getBscMatBldVol8());
        cv.put(Zp02DBConstants.bscMatBldTotVol, biospecimenCollection.getBscMatBldTotVol());
        cv.put(Zp02DBConstants.bscMatBldTime, biospecimenCollection.getBscMatBldTime());
        cv.put(Zp02DBConstants.bscMatBldCom, biospecimenCollection.getBscMatBldCom());
        cv.put(Zp02DBConstants.bscMatSlvaCol, biospecimenCollection.getBscMatSlvaCol());
        cv.put(Zp02DBConstants.bscMatSlvaRsn, biospecimenCollection.getBscMatSlvaRsn());
        cv.put(Zp02DBConstants.bscMatSlvaSpecify, biospecimenCollection.getBscMatSlvaSpecify());
        cv.put(Zp02DBConstants.bscMatSlvaId, biospecimenCollection.getBscMatSlvaId());
        cv.put(Zp02DBConstants.bscMatSlvaTime, biospecimenCollection.getBscMatSlvaTime());
        cv.put(Zp02DBConstants.bscMatSlvaCom, biospecimenCollection.getBscMatSlvaCom());
        cv.put(Zp02DBConstants.bscMatVagCol, biospecimenCollection.getBscMatVagCol());
        cv.put(Zp02DBConstants.bscMatVagRsn, biospecimenCollection.getBscMatVagRsn());
        cv.put(Zp02DBConstants.bscMatVagSpecify, biospecimenCollection.getBscMatVagSpecify());
        cv.put(Zp02DBConstants.bscMatVagId, biospecimenCollection.getBscMatVagId());
        cv.put(Zp02DBConstants.bscMatVagTime, biospecimenCollection.getBscMatVagTime());
        cv.put(Zp02DBConstants.bscMatVagCom, biospecimenCollection.getBscMatVagCom());
        cv.put(Zp02DBConstants.bscMatVstUrnCol, biospecimenCollection.getBscMatVstUrnCol());
        cv.put(Zp02DBConstants.bscMatVstUrnRsn, biospecimenCollection.getBscMatVstUrnRsn());
        cv.put(Zp02DBConstants.bscMatVstUrnSpecify, biospecimenCollection.getBscMatVstUrnSpecify());
        cv.put(Zp02DBConstants.bscMatVstUrnId, biospecimenCollection.getBscMatVstUrnId());
        cv.put(Zp02DBConstants.bscMatVstUrnTime, biospecimenCollection.getBscMatVstUrnTime());
        cv.put(Zp02DBConstants.bscMatVstUrnCom, biospecimenCollection.getBscMatVstUrnCom());
        cv.put(Zp02DBConstants.bscMatHomUrnCol, biospecimenCollection.getBscMatHomUrnCol());
        cv.put(Zp02DBConstants.bscMatHomUrnRsn, biospecimenCollection.getBscMatHomUrnRsn());
        cv.put(Zp02DBConstants.bscMatHomUrnSpecify, biospecimenCollection.getBscMatHomUrnSpecify());
        cv.put(Zp02DBConstants.bscMatHomUrnNum, biospecimenCollection.getBscMatHomUrnNum());
        cv.put(Zp02DBConstants.bscMatHomUrnId1, biospecimenCollection.getBscMatHomUrnId1());
        if (biospecimenCollection.getBscMatHomUrnDat1()!=null) cv.put(Zp02DBConstants.bscMatHomUrnDat1, biospecimenCollection.getBscMatHomUrnDat1().getTime());
        cv.put(Zp02DBConstants.bscMatHomUrnTime1, biospecimenCollection.getBscMatHomUrnTime1());
        cv.put(Zp02DBConstants.bscMatHomUrnCom1, biospecimenCollection.getBscMatHomUrnCom1());
        cv.put(Zp02DBConstants.bscMatHomUrnId2, biospecimenCollection.getBscMatHomUrnId2());
        if (biospecimenCollection.getBscMatHomUrnDat2()!=null) cv.put(Zp02DBConstants.bscMatHomUrnDat2, biospecimenCollection.getBscMatHomUrnDat2().getTime());
        cv.put(Zp02DBConstants.bscMatHomUrnTime2, biospecimenCollection.getBscMatHomUrnTime2());
        cv.put(Zp02DBConstants.bscMatHomUrnCom2, biospecimenCollection.getBscMatHomUrnCom2());
        cv.put(Zp02DBConstants.bscMatHomUrnId3, biospecimenCollection.getBscMatHomUrnId3());
        if (biospecimenCollection.getBscMatHomUrnDat3()!=null) cv.put(Zp02DBConstants.bscMatHomUrnDat3, biospecimenCollection.getBscMatHomUrnDat3().getTime());
        cv.put(Zp02DBConstants.bscMatHomUrnTime3, biospecimenCollection.getBscMatHomUrnTime3());
        cv.put(Zp02DBConstants.bscMatHomUrnCom3, biospecimenCollection.getBscMatHomUrnCom3());
        cv.put(Zp02DBConstants.bscMatHomUrnId4, biospecimenCollection.getBscMatBldId4());
        if (biospecimenCollection.getBscMatHomUrnDat4()!=null) cv.put(Zp02DBConstants.bscMatHomUrnDat4, biospecimenCollection.getBscMatHomUrnDat4().getTime());
        cv.put(Zp02DBConstants.bscMatHomUrnTime4, biospecimenCollection.getBscMatHomUrnTime4());
        cv.put(Zp02DBConstants.bscMatHomUrnCom4, biospecimenCollection.getBscMatHomUrnCom4());
        cv.put(Zp02DBConstants.bscMatOtherCol, biospecimenCollection.getBscMatOtherCol());
        cv.put(Zp02DBConstants.bscMatOtherType, biospecimenCollection.getBscMatOtherType());
        cv.put(Zp02DBConstants.bscMatOtherTypeSpecify, biospecimenCollection.getBscMatOtherTypeSpecify());
        cv.put(Zp02DBConstants.bscMatAmfCol, biospecimenCollection.getBscMatAmfCol());
        cv.put(Zp02DBConstants.bscMatAmfRsn, biospecimenCollection.getBscMatAmfRsn());
        cv.put(Zp02DBConstants.bscMatAmfSpecify, biospecimenCollection.getBscMatAmfSpecify());
        cv.put(Zp02DBConstants.bscMatAmfId, biospecimenCollection.getBscMatAmfId());
        cv.put(Zp02DBConstants.bscMatAmfAmount, biospecimenCollection.getBscMatAmfAmount());
        cv.put(Zp02DBConstants.bscMatAmfTime, biospecimenCollection.getBscMatAmfTime());
        cv.put(Zp02DBConstants.bscMatAmfCom, biospecimenCollection.getBscMatAmfCom());
        cv.put(Zp02DBConstants.bscMatCordCol, biospecimenCollection.getBscMatCordCol());
        cv.put(Zp02DBConstants.bscMatCordRsn, biospecimenCollection.getBscMatCordRsn());
        cv.put(Zp02DBConstants.bscMatCordSpecify, biospecimenCollection.getBscMatCordSpecify());
        cv.put(Zp02DBConstants.bscMatCordId, biospecimenCollection.getBscMatCordId());
        cv.put(Zp02DBConstants.bscMatCordTime, biospecimenCollection.getBscMatCordTime());
        cv.put(Zp02DBConstants.bscMatCordAmount, biospecimenCollection.getBscMatCordAmount());
        cv.put(Zp02DBConstants.bscMatCordCom, biospecimenCollection.getBscMatCordCom());
        cv.put(Zp02DBConstants.bscMatPlacenCol, biospecimenCollection.getBscMatPlacenCol());
        cv.put(Zp02DBConstants.bscMatPlacenRsn, biospecimenCollection.getBscMatPlacenRsn());
        cv.put(Zp02DBConstants.bscMatPlacenSpecify, biospecimenCollection.getBscMatPlacenSpecify());
        cv.put(Zp02DBConstants.bscMatPlacenCircum, biospecimenCollection.getBscMatPlacenCircum());
        cv.put(Zp02DBConstants.bscMatPlacenId, biospecimenCollection.getBscMatPlacenId());
        cv.put(Zp02DBConstants.bscMatPlacenTime, biospecimenCollection.getBscMatPlacenTime());
        cv.put(Zp02DBConstants.bscMatPlacenCom, biospecimenCollection.getBscMatPlacenCom());
        cv.put(Zp02DBConstants.bscMatBreastmCol, biospecimenCollection.getBscMatBreastmCol());
        cv.put(Zp02DBConstants.bscMatBreastmRsn, biospecimenCollection.getBscMatBreastmRsn());
        cv.put(Zp02DBConstants.bscMatBreastmSpecify, biospecimenCollection.getBscMatBreastmSpecify());
        cv.put(Zp02DBConstants.bscMatBreastmId, biospecimenCollection.getBscMatBreastmId());
        cv.put(Zp02DBConstants.bscMatBreastmTime, biospecimenCollection.getBscMatBreastmTime());
        cv.put(Zp02DBConstants.bscMatBreastmAmount, biospecimenCollection.getBscMatBreastmAmount());
        cv.put(Zp02DBConstants.bscMatBreastmCom, biospecimenCollection.getBscMatBreastmCom());
        cv.put(Zp02DBConstants.bscMatMiscarr, biospecimenCollection.getBscMatMiscarr());
        cv.put(Zp02DBConstants.bscMatFetaltCol, biospecimenCollection.getBscMatFetaltCol());
        cv.put(Zp02DBConstants.bscMatFetaltId, biospecimenCollection.getBscMatFetaltId());
        cv.put(Zp02DBConstants.bscMatFetaltTime, biospecimenCollection.getBscMatFetaltTime());
        cv.put(Zp02DBConstants.bscMatFetaltCom, biospecimenCollection.getBscMatFetaltCom());
        cv.put(Zp02DBConstants.bscMatdBreastmCol, biospecimenCollection.getBscMatdBreastmCol());
        cv.put(Zp02DBConstants.bscMatdBreastmRsn, biospecimenCollection.getBscMatdBreastmRsn());
        cv.put(Zp02DBConstants.bscMatdBreastmSpecify, biospecimenCollection.getBscMatdBreastmSpecify());
        cv.put(Zp02DBConstants.bscMatdBreastmId, biospecimenCollection.getBscMatdBreastmId());
        cv.put(Zp02DBConstants.bscMatdBreastmTime, biospecimenCollection.getBscMatdBreastmTime());
        cv.put(Zp02DBConstants.bscMatdBreastmAmou, biospecimenCollection.getBscMatdBreastmAmou());
        cv.put(Zp02DBConstants.bscMatdBreastmCom, biospecimenCollection.getBscMatdBreastmCom());
        cv.put(Zp02DBConstants.addtAnemiaTest, biospecimenCollection.getAddtAnemiaTest());
        if (biospecimenCollection.getAddtLastAnemiaTest()!=null) cv.put(Zp02DBConstants.addtLastAnemiaTest, biospecimenCollection.getAddtLastAnemiaTest().getTime());
        cv.put(Zp02DBConstants.addtLastAnemiaTestUk, biospecimenCollection.getAddtLastAnemiaTestUk());
        cv.put(Zp02DBConstants.addtAnemiaTestAv, biospecimenCollection.getAddtAnemiaTestAv());
        cv.put(Zp02DBConstants.addtHematocrit, biospecimenCollection.getAddtHematocrit());
        cv.put(Zp02DBConstants.addtHemoglobin, biospecimenCollection.getAddtHemoglobin());


        cv.put(Zp02DBConstants.bscPerson1, biospecimenCollection.getBscPerson1());
        if (biospecimenCollection.getBscCompleteDate1()!=null)cv.put(Zp02DBConstants.bscCompleteDate1, biospecimenCollection.getBscCompleteDate1().getTime());
        cv.put(Zp02DBConstants.bscPerson2, biospecimenCollection.getBscPerson2());
        if (biospecimenCollection.getBscCompleteDate2()!=null) cv.put(Zp02DBConstants.bscCompleteDate2, biospecimenCollection.getBscCompleteDate2().getTime());
        cv.put(Zp02DBConstants.bscPerson3, biospecimenCollection.getBscPerson3());
        if (biospecimenCollection.getBscCompleteDate3()!=null) cv.put(Zp02DBConstants.bscCompleteDate3, biospecimenCollection.getBscCompleteDate3().getTime());

        if (biospecimenCollection.getRecordDate() != null) cv.put(MainDBConstants.recordDate, biospecimenCollection.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, biospecimenCollection.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(biospecimenCollection.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, biospecimenCollection.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, biospecimenCollection.getInstancePath());
        cv.put(MainDBConstants.STATUS, biospecimenCollection.getEstado());
        cv.put(MainDBConstants.START, biospecimenCollection.getStart());
        cv.put(MainDBConstants.END, biospecimenCollection.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, biospecimenCollection.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, biospecimenCollection.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, biospecimenCollection.getPhonenumber());
        if (biospecimenCollection.getToday() != null) cv.put(MainDBConstants.TODAY, biospecimenCollection.getToday().getTime());

        return cv;
    }

    public static Zp02BiospecimenCollection crearZp02BiospecimenCollection(Cursor cursorBC){
        Zp02BiospecimenCollection biospecimenCollection = new Zp02BiospecimenCollection();
        biospecimenCollection.setRecordId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.recordId)));
        biospecimenCollection.setRedcapEventName(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.redcapEventName)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscDov))>0) biospecimenCollection.setBscDov(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscDov))));
        biospecimenCollection.setBscVisit(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscVisit)));
        biospecimenCollection.setBscMatBldCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldCol)));
        biospecimenCollection.setBscMatBldRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldRsn)));
        biospecimenCollection.setBscMatBldSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldSpecify)));
        biospecimenCollection.setBscMatBldTyp1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp1)));
        biospecimenCollection.setBscMatBldId1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId1)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol1))>0) biospecimenCollection.setBscMatBldVol1(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol1)));
        biospecimenCollection.setBscMatBldTyp2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp2)));
        biospecimenCollection.setBscMatBldId2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId2)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol2))>0) biospecimenCollection.setBscMatBldVol2(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol2)));
        biospecimenCollection.setBscMatBldTyp3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp3)));
        biospecimenCollection.setBscMatBldId3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId3)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol3))>0) biospecimenCollection.setBscMatBldVol3(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol3)));
        biospecimenCollection.setBscMatBldTyp4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp4)));
        biospecimenCollection.setBscMatBldId4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId4)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol4))>0) biospecimenCollection.setBscMatBldVol4(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol4)));
        biospecimenCollection.setBscMatBldTyp5(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp5)));
        biospecimenCollection.setBscMatBldId5(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId5)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol5))>0) biospecimenCollection.setBscMatBldVol5(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol5)));
        biospecimenCollection.setBscMatBldTyp6(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp6)));
        biospecimenCollection.setBscMatBldId6(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId6)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol6))>0) biospecimenCollection.setBscMatBldVol6(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol6)));
        biospecimenCollection.setBscMatBldTyp7(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp7)));
        biospecimenCollection.setBscMatBldId7(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId7)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol7))>0) biospecimenCollection.setBscMatBldVol7(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol7)));
        biospecimenCollection.setBscMatBldTyp8(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTyp8)));
        biospecimenCollection.setBscMatBldId8(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldId8)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol8))>0) biospecimenCollection.setBscMatBldVol8(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldVol8)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTotVol))>0) biospecimenCollection.setBscMatBldTotVol(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTotVol)));
        biospecimenCollection.setBscMatBldTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldTime)));
        biospecimenCollection.setBscMatBldCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBldCom)));
        biospecimenCollection.setBscMatSlvaCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaCol)));
        biospecimenCollection.setBscMatSlvaRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaRsn)));
        biospecimenCollection.setBscMatSlvaSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaSpecify)));
        biospecimenCollection.setBscMatSlvaId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaId)));
        biospecimenCollection.setBscMatSlvaTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaTime)));
        biospecimenCollection.setBscMatSlvaCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatSlvaCom)));
        biospecimenCollection.setBscMatVagCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagCol)));
        biospecimenCollection.setBscMatVagRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagRsn)));
        biospecimenCollection.setBscMatVagSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagSpecify)));
        biospecimenCollection.setBscMatVagId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagId)));
        biospecimenCollection.setBscMatVagTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagTime)));
        biospecimenCollection.setBscMatVagCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVagCom)));
        biospecimenCollection.setBscMatVstUrnCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnCol)));
        biospecimenCollection.setBscMatVstUrnRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnRsn)));
        biospecimenCollection.setBscMatVstUrnSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnSpecify)));
        biospecimenCollection.setBscMatVstUrnId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnId)));
        biospecimenCollection.setBscMatVstUrnTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnTime)));
        biospecimenCollection.setBscMatVstUrnCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatVstUrnCom)));
        biospecimenCollection.setBscMatHomUrnCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnCol)));
        biospecimenCollection.setBscMatHomUrnRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnRsn)));
        biospecimenCollection.setBscMatHomUrnSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnSpecify)));
        if(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnNum))>0) biospecimenCollection.setBscMatHomUrnNum(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnNum)));
        biospecimenCollection.setBscMatHomUrnId1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnId1)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat1))>0) biospecimenCollection.setBscMatHomUrnDat1(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat1))));
        biospecimenCollection.setBscMatHomUrnTime1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnTime1)));
        biospecimenCollection.setBscMatHomUrnCom1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnCom1)));
        biospecimenCollection.setBscMatHomUrnId2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnId2)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat2))>0) biospecimenCollection.setBscMatHomUrnDat2(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat2))));
        biospecimenCollection.setBscMatHomUrnTime2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnTime2)));
        biospecimenCollection.setBscMatHomUrnCom2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnCom2)));
        biospecimenCollection.setBscMatHomUrnId3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnId3)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat3))>0) biospecimenCollection.setBscMatHomUrnDat3(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat3))));
        biospecimenCollection.setBscMatHomUrnTime3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnTime3)));
        biospecimenCollection.setBscMatHomUrnCom3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnCom3)));
        biospecimenCollection.setBscMatHomUrnId4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnId4)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat4))>0) biospecimenCollection.setBscMatHomUrnDat4(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnDat4))));
        biospecimenCollection.setBscMatHomUrnTime4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnTime4)));
        biospecimenCollection.setBscMatHomUrnCom4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatHomUrnCom4)));
        biospecimenCollection.setBscMatOtherCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatOtherCol)));
        biospecimenCollection.setBscMatOtherType(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatOtherType)));
        biospecimenCollection.setBscMatOtherTypeSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatOtherTypeSpecify)));
        biospecimenCollection.setBscMatAmfCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfCol)));
        biospecimenCollection.setBscMatAmfRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfRsn)));
        biospecimenCollection.setBscMatAmfSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfSpecify)));
        biospecimenCollection.setBscMatAmfId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfId)));
        if (cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfAmount))>0) biospecimenCollection.setBscMatAmfAmount(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfAmount)));
        biospecimenCollection.setBscMatAmfTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfTime)));
        biospecimenCollection.setBscMatAmfCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatAmfCom)));
        biospecimenCollection.setBscMatCordCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordCol)));
        biospecimenCollection.setBscMatCordRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordRsn)));
        biospecimenCollection.setBscMatCordSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordSpecify)));
        biospecimenCollection.setBscMatCordId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordId)));
        biospecimenCollection.setBscMatCordTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordTime)));
        if(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordAmount))>0) biospecimenCollection.setBscMatCordAmount(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordAmount)));
        biospecimenCollection.setBscMatCordCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatCordCom)));
        biospecimenCollection.setBscMatPlacenCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenCol)));
        biospecimenCollection.setBscMatPlacenRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenRsn)));
        biospecimenCollection.setBscMatPlacenSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenSpecify)));
        biospecimenCollection.setBscMatPlacenCircum(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenCircum)));
        biospecimenCollection.setBscMatPlacenId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenId)));
        biospecimenCollection.setBscMatPlacenTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenTime)));
        biospecimenCollection.setBscMatPlacenCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatPlacenCom)));
        biospecimenCollection.setBscMatBreastmCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmCol)));
        biospecimenCollection.setBscMatBreastmRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmRsn)));
        biospecimenCollection.setBscMatBreastmSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmSpecify)));
        biospecimenCollection.setBscMatBreastmId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmId)));
        biospecimenCollection.setBscMatBreastmTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmTime)));
        if(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmAmount))>0) biospecimenCollection.setBscMatBreastmAmount(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmAmount)));
        biospecimenCollection.setBscMatBreastmCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatBreastmCom)));
        biospecimenCollection.setBscMatMiscarr(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatMiscarr)));
        biospecimenCollection.setBscMatFetaltCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatFetaltCol)));
        biospecimenCollection.setBscMatFetaltId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatFetaltId)));
        biospecimenCollection.setBscMatFetaltTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatFetaltTime)));
        biospecimenCollection.setBscMatFetaltCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatFetaltCom)));
        biospecimenCollection.setBscMatdBreastmCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmCol)));
        biospecimenCollection.setBscMatdBreastmRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmRsn)));
        biospecimenCollection.setBscMatdBreastmSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmSpecify)));
        biospecimenCollection.setBscMatdBreastmId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmId)));
        biospecimenCollection.setBscMatdBreastmTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmTime)));
        if(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmAmou))>0) biospecimenCollection.setBscMatdBreastmAmou(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmAmou)));
        biospecimenCollection.setBscMatdBreastmCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscMatdBreastmCom)));
        biospecimenCollection.setAddtAnemiaTest(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.addtAnemiaTest)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.addtLastAnemiaTest))>0) biospecimenCollection.setAddtLastAnemiaTest(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.addtLastAnemiaTest))));
        biospecimenCollection.setAddtLastAnemiaTestUk(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.addtLastAnemiaTestUk)));
        biospecimenCollection.setAddtAnemiaTestAv(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.addtLastAnemiaTestUk)));
        biospecimenCollection.setAddtHematocrit(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.addtHematocrit)));
        biospecimenCollection.setAddtHemoglobin(cursorBC.getFloat(cursorBC.getColumnIndex(Zp02DBConstants.addtHemoglobin)));

        biospecimenCollection.setBscPerson1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscPerson1)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate1))>0) biospecimenCollection.setBscCompleteDate1(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate1))));
        biospecimenCollection.setBscPerson2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscPerson2)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate2))>0) biospecimenCollection.setBscCompleteDate2(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate2))));
        biospecimenCollection.setBscPerson3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.bscPerson3)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate3))>0) biospecimenCollection.setBscCompleteDate3(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscCompleteDate3))));

        if(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.recordDate))>0) biospecimenCollection.setRecordDate(new Date(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.recordDate))));
        biospecimenCollection.setRecordUser(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.recordUser)));
        biospecimenCollection.setPasive(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        biospecimenCollection.setIdInstancia(cursorBC.getInt(cursorBC.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        biospecimenCollection.setInstancePath(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.FILE_PATH)));
        biospecimenCollection.setEstado(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.STATUS)));
        biospecimenCollection.setStart(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.START)));
        biospecimenCollection.setEnd(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.END)));
        biospecimenCollection.setSimserial(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        biospecimenCollection.setPhonenumber(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        biospecimenCollection.setDeviceid(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.TODAY))>0) biospecimenCollection.setToday(new Date(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.TODAY))));

        return biospecimenCollection;
    }

    public static ContentValues crearZp02dInfantBiospecimenCollection(Zp02dInfantBiospecimenCollection dInfantBiospecimenCollection){
        ContentValues cv = new ContentValues();

        cv.put(Zp02DBConstants.recordId, dInfantBiospecimenCollection.getRecordId());
        cv.put(Zp02DBConstants.redcapEventName, dInfantBiospecimenCollection.getRedcapEventName());

        if (dInfantBiospecimenCollection.getInfantDov()!=null) cv.put(Zp02DBConstants.infantDov, dInfantBiospecimenCollection.getInfantDov().getTime());
        cv.put(Zp02DBConstants.whomAddtVisit, dInfantBiospecimenCollection.getWhomAddtVisit());
        cv.put(Zp02DBConstants.infantAddtVisit, dInfantBiospecimenCollection.getInfantAddtVisit());
        cv.put(Zp02DBConstants.infantAddtVisitOther, dInfantBiospecimenCollection.getInfantAddtVisitOther());
        cv.put(Zp02DBConstants.infantMatBldCol, dInfantBiospecimenCollection.getInfantMatBldCol());
        cv.put(Zp02DBConstants.infantMatBldRsn, dInfantBiospecimenCollection.getInfantMatBldRsn());
        cv.put(Zp02DBConstants.infantMatBldSpecify, dInfantBiospecimenCollection.getInfantMatBldSpecify());
        cv.put(Zp02DBConstants.infantMatBldTyp1, dInfantBiospecimenCollection.getInfantMatBldTyp1());
        cv.put(Zp02DBConstants.infantMatBldId1, dInfantBiospecimenCollection.getInfantMatBldId1());
        cv.put(Zp02DBConstants.infantMatBldVol1, dInfantBiospecimenCollection.getInfantMatBldVol1());
        cv.put(Zp02DBConstants.infantMatBldTyp2, dInfantBiospecimenCollection.getInfantMatBldTyp2());
        cv.put(Zp02DBConstants.infantMatBldId2, dInfantBiospecimenCollection.getInfantMatBldId2());
        cv.put(Zp02DBConstants.infantMatBldVol2, dInfantBiospecimenCollection.getInfantMatBldVol2());
        cv.put(Zp02DBConstants.infantMatBldTyp3, dInfantBiospecimenCollection.getInfantMatBldTyp3());
        cv.put(Zp02DBConstants.infantMatBldId3, dInfantBiospecimenCollection.getInfantMatBldId3());
        cv.put(Zp02DBConstants.infantMatBldVol3, dInfantBiospecimenCollection.getInfantMatBldVol3());
        cv.put(Zp02DBConstants.infantMatBldTyp4, dInfantBiospecimenCollection.getInfantMatBldTyp4());
        cv.put(Zp02DBConstants.infantMatBldId4, dInfantBiospecimenCollection.getInfantMatBldId4());
        cv.put(Zp02DBConstants.infantMatBldVol4, dInfantBiospecimenCollection.getInfantMatBldVol4());
        cv.put(Zp02DBConstants.infantMatBldTyp5, dInfantBiospecimenCollection.getInfantMatBldTyp5());
        cv.put(Zp02DBConstants.infantMatBldId5, dInfantBiospecimenCollection.getInfantMatBldId5());
        cv.put(Zp02DBConstants.infantMatBldVol5, dInfantBiospecimenCollection.getInfantMatBldVol5());
        cv.put(Zp02DBConstants.infantMatBldTyp6, dInfantBiospecimenCollection.getInfantMatBldTyp6());
        cv.put(Zp02DBConstants.infantMatBldId6, dInfantBiospecimenCollection.getInfantMatBldId6());
        cv.put(Zp02DBConstants.infantMatBldVol6, dInfantBiospecimenCollection.getInfantMatBldVol6());
        cv.put(Zp02DBConstants.infantMatBldTyp7, dInfantBiospecimenCollection.getInfantMatBldTyp7());
        cv.put(Zp02DBConstants.infantMatBldId7, dInfantBiospecimenCollection.getInfantMatBldId7());
        cv.put(Zp02DBConstants.infantMatBldVol7, dInfantBiospecimenCollection.getInfantMatBldVol7());
        cv.put(Zp02DBConstants.infantMatBldTyp8, dInfantBiospecimenCollection.getInfantMatBldTyp8());
        cv.put(Zp02DBConstants.infantMatBldId8, dInfantBiospecimenCollection.getInfantMatBldId8());
        cv.put(Zp02DBConstants.infantMatBldVol8, dInfantBiospecimenCollection.getInfantMatBldVol8());
        cv.put(Zp02DBConstants.infantMatBldTotVol, dInfantBiospecimenCollection.getInfantMatBldTotVol());
        cv.put(Zp02DBConstants.infantMatBldTime, dInfantBiospecimenCollection.getInfantMatBldTime());
        cv.put(Zp02DBConstants.infantMatBldCom, dInfantBiospecimenCollection.getInfantMatBldCom());
        cv.put(Zp02DBConstants.infantMatSlvaCol, dInfantBiospecimenCollection.getInfantMatSlvaCol());
        cv.put(Zp02DBConstants.infantMatSlvaRsn, dInfantBiospecimenCollection.getInfantMatSlvaRsn());
        cv.put(Zp02DBConstants.infantMatSlvaSpecify, dInfantBiospecimenCollection.getInfantMatSlvaSpecify());
        cv.put(Zp02DBConstants.infantMatSlvaId, dInfantBiospecimenCollection.getInfantMatSlvaId());
        cv.put(Zp02DBConstants.infantMatSlvaTime, dInfantBiospecimenCollection.getInfantMatSlvaTime());
        cv.put(Zp02DBConstants.infantMatSlvaCom, dInfantBiospecimenCollection.getInfantMatSlvaCom());
        cv.put(Zp02DBConstants.infantMatVstUrnCol, dInfantBiospecimenCollection.getInfantMatVstUrnCol());
        cv.put(Zp02DBConstants.infantMatVstUrnRsn, dInfantBiospecimenCollection.getInfantMatVstUrnRsn());
        cv.put(Zp02DBConstants.infantMatVstUrnSpecify, dInfantBiospecimenCollection.getInfantMatVstUrnSpecify());
        cv.put(Zp02DBConstants.infantMatVstUrnId, dInfantBiospecimenCollection.getInfantMatVstUrnId());
        cv.put(Zp02DBConstants.infantMatVstUrnTime, dInfantBiospecimenCollection.getInfantMatVstUrnTime());
        cv.put(Zp02DBConstants.infantMatVstUrnCom, dInfantBiospecimenCollection.getInfantMatVstUrnCom());
        cv.put(Zp02DBConstants.infantPerson1, dInfantBiospecimenCollection.getInfantPerson1());
        if (dInfantBiospecimenCollection.getInfantCompleteDate1()!=null) cv.put(Zp02DBConstants.infantCompleteDate1, dInfantBiospecimenCollection.getInfantCompleteDate1().getTime());
        cv.put(Zp02DBConstants.infantPerson2, dInfantBiospecimenCollection.getInfantPerson2());
        if (dInfantBiospecimenCollection.getInfantCompleteDate2()!=null) cv.put(Zp02DBConstants.infantCompleteDate2, dInfantBiospecimenCollection.getInfantCompleteDate2().getTime());
        cv.put(Zp02DBConstants.infantPerson3, dInfantBiospecimenCollection.getInfantPerson3());
        if (dInfantBiospecimenCollection.getInfantCompleteDate3()!=null) cv.put(Zp02DBConstants.infantCompleteDate3, dInfantBiospecimenCollection.getInfantCompleteDate3().getTime());

        if (dInfantBiospecimenCollection.getRecordDate() != null) cv.put(MainDBConstants.recordDate, dInfantBiospecimenCollection.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, dInfantBiospecimenCollection.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(dInfantBiospecimenCollection.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, dInfantBiospecimenCollection.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, dInfantBiospecimenCollection.getInstancePath());
        cv.put(MainDBConstants.STATUS, dInfantBiospecimenCollection.getEstado());
        cv.put(MainDBConstants.START, dInfantBiospecimenCollection.getStart());
        cv.put(MainDBConstants.END, dInfantBiospecimenCollection.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, dInfantBiospecimenCollection.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, dInfantBiospecimenCollection.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, dInfantBiospecimenCollection.getPhonenumber());
        if (dInfantBiospecimenCollection.getToday() != null) cv.put(MainDBConstants.TODAY, dInfantBiospecimenCollection.getToday().getTime());

        return cv;
    }

    public static Zp02dInfantBiospecimenCollection crearZp02dInfantBiospecimenCollection(Cursor cursorBC){

        Zp02dInfantBiospecimenCollection dInfantBiospecimenCollection = new Zp02dInfantBiospecimenCollection();
        dInfantBiospecimenCollection.setRecordId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.recordId)));
        dInfantBiospecimenCollection.setRedcapEventName(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.redcapEventName)));
        if (cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.bscDov))>0) dInfantBiospecimenCollection.setInfantDov(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantDov))));
        dInfantBiospecimenCollection.setWhomAddtVisit(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.whomAddtVisit)));
        dInfantBiospecimenCollection.setInfantAddtVisit(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantAddtVisit)));
        dInfantBiospecimenCollection.setInfantAddtVisitOther(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantAddtVisitOther)));
        dInfantBiospecimenCollection.setInfantMatBldCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldCol)));
        dInfantBiospecimenCollection.setInfantMatBldRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldRsn)));
        dInfantBiospecimenCollection.setInfantMatBldSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldSpecify)));
        dInfantBiospecimenCollection.setInfantMatBldTyp1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp1)));
        dInfantBiospecimenCollection.setInfantMatBldId1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId1)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol1))>0) dInfantBiospecimenCollection.setInfantMatBldVol1(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol1)));
        dInfantBiospecimenCollection.setInfantMatBldTyp2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp2)));
        dInfantBiospecimenCollection.setInfantMatBldId2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId2)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol2))>0) dInfantBiospecimenCollection.setInfantMatBldVol2(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol2)));
        dInfantBiospecimenCollection.setInfantMatBldTyp3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp3)));
        dInfantBiospecimenCollection.setInfantMatBldId3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId3)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol3))>0) dInfantBiospecimenCollection.setInfantMatBldVol3(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol3)));
        dInfantBiospecimenCollection.setInfantMatBldTyp4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp4)));
        dInfantBiospecimenCollection.setInfantMatBldId4(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId4)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol4))>0) dInfantBiospecimenCollection.setInfantMatBldVol4(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol4)));
        dInfantBiospecimenCollection.setInfantMatBldTyp5(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp5)));
        dInfantBiospecimenCollection.setInfantMatBldId5(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId5)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol5))>0) dInfantBiospecimenCollection.setInfantMatBldVol5(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol5)));
        dInfantBiospecimenCollection.setInfantMatBldTyp6(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp6)));
        dInfantBiospecimenCollection.setInfantMatBldId6(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId6)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol6))>0) dInfantBiospecimenCollection.setInfantMatBldVol6(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol6)));
        dInfantBiospecimenCollection.setInfantMatBldTyp7(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp7)));
        dInfantBiospecimenCollection.setInfantMatBldId7(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId7)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol7))>0) dInfantBiospecimenCollection.setInfantMatBldVol7(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol7)));
        dInfantBiospecimenCollection.setInfantMatBldTyp8(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTyp8)));
        dInfantBiospecimenCollection.setInfantMatBldId8(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldId8)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol8))>0) dInfantBiospecimenCollection.setInfantMatBldVol8(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldVol8)));
        if (cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTotVol))>0) dInfantBiospecimenCollection.setInfantMatBldTotVol(cursorBC.getInt(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTotVol)));
        dInfantBiospecimenCollection.setInfantMatBldTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldTime)));
        dInfantBiospecimenCollection.setInfantMatBldCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatBldCom)));
        dInfantBiospecimenCollection.setInfantMatSlvaCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaCol)));
        dInfantBiospecimenCollection.setInfantMatSlvaRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaRsn)));
        dInfantBiospecimenCollection.setInfantMatSlvaSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaSpecify)));
        dInfantBiospecimenCollection.setInfantMatSlvaId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaId)));
        dInfantBiospecimenCollection.setInfantMatSlvaTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaTime)));
        dInfantBiospecimenCollection.setInfantMatSlvaCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatSlvaCom)));
        dInfantBiospecimenCollection.setInfantMatVstUrnCol(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnCol)));
        dInfantBiospecimenCollection.setInfantMatVstUrnRsn(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnRsn)));
        dInfantBiospecimenCollection.setInfantMatVstUrnSpecify(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnSpecify)));
        dInfantBiospecimenCollection.setInfantMatVstUrnId(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnId)));
        dInfantBiospecimenCollection.setInfantMatVstUrnTime(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnTime)));
        dInfantBiospecimenCollection.setInfantMatVstUrnCom(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantMatVstUrnCom)));
        dInfantBiospecimenCollection.setInfantPerson1(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantPerson1)));
        if(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate1))>0) dInfantBiospecimenCollection.setInfantCompleteDate1(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate1))));
        dInfantBiospecimenCollection.setInfantPerson2(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantPerson2)));
        if(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate2))>0) dInfantBiospecimenCollection.setInfantCompleteDate2(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate2))));
        dInfantBiospecimenCollection.setInfantPerson3(cursorBC.getString(cursorBC.getColumnIndex(Zp02DBConstants.infantPerson3)));
        if(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate3))>0) dInfantBiospecimenCollection.setInfantCompleteDate3(new Date(cursorBC.getLong(cursorBC.getColumnIndex(Zp02DBConstants.infantCompleteDate3))));

        if(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.recordDate))>0) dInfantBiospecimenCollection.setRecordDate(new Date(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.recordDate))));
        dInfantBiospecimenCollection.setRecordUser(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.recordUser)));
        dInfantBiospecimenCollection.setPasive(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        dInfantBiospecimenCollection.setIdInstancia(cursorBC.getInt(cursorBC.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        dInfantBiospecimenCollection.setInstancePath(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.FILE_PATH)));
        dInfantBiospecimenCollection.setEstado(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.STATUS)));
        dInfantBiospecimenCollection.setStart(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.START)));
        dInfantBiospecimenCollection.setEnd(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.END)));
        dInfantBiospecimenCollection.setSimserial(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        dInfantBiospecimenCollection.setPhonenumber(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        dInfantBiospecimenCollection.setDeviceid(cursorBC.getString(cursorBC.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.TODAY))>0) dInfantBiospecimenCollection.setToday(new Date(cursorBC.getLong(cursorBC.getColumnIndex(MainDBConstants.TODAY))));

        return dInfantBiospecimenCollection;
    }
}
