package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp03MonthlyVisit;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp03DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 10/24/2016.
 * V1.0
 */
public class Zp03MonthlyVisitHelper {

    public static ContentValues crearZp03MonthlyVisit(Zp03MonthlyVisit monthlyVisit){
        ContentValues cv = new ContentValues();

        cv.put(Zp03DBConstants.recordId, monthlyVisit.getRecordId());

        cv.put(Zp03DBConstants.redcapEventName, monthlyVisit.getRedcapEventName());
        if (monthlyVisit.getMonVisitDate()!=null) cv.put(Zp03DBConstants.monVisitDate, monthlyVisit.getMonVisitDate().getTime());
        cv.put(Zp03DBConstants.monVisitType, monthlyVisit.getMonVisitType());
        cv.put(Zp03DBConstants.monReasonMissed, monthlyVisit.getMonReasonMissed());
        cv.put(Zp03DBConstants.monOtherReschedu, monthlyVisit.getMonOtherReschedu());
        cv.put(Zp03DBConstants.monReasonUnscheduled, monthlyVisit.getMonReasonUnscheduled());
        cv.put(Zp03DBConstants.monOtherUnscheduled, monthlyVisit.getMonOtherUnscheduled());
        cv.put(Zp03DBConstants.monMotherWt, monthlyVisit.getMonMotherWt());
        cv.put(Zp03DBConstants.monWtUnit, monthlyVisit.getMonWtUnit());
        cv.put(Zp03DBConstants.monSystolic, monthlyVisit.getMonSystolic());
        cv.put(Zp03DBConstants.monDiastolic, monthlyVisit.getMonDiastolic());
        cv.put(Zp03DBConstants.monTemperature, monthlyVisit.getMonTemperature());
        cv.put(Zp03DBConstants.monTempUnit, monthlyVisit.getMonTempUnit());
        cv.put(Zp03DBConstants.monPregnancyLoss, monthlyVisit.getMonPregnancyLoss());
        if (monthlyVisit.getMonDateLoss()!=null) cv.put(Zp03DBConstants.monDateLoss, monthlyVisit.getMonDateLoss().getTime());
        cv.put(Zp03DBConstants.monPersisHeadache, monthlyVisit.getMonPersisHeadache());
        cv.put(Zp03DBConstants.monDizziness, monthlyVisit.getMonDizziness());
        cv.put(Zp03DBConstants.monNausea, monthlyVisit.getMonNausea());
        cv.put(Zp03DBConstants.monVomiting, monthlyVisit.getMonVomiting());
        cv.put(Zp03DBConstants.monLights, monthlyVisit.getMonLights());
        cv.put(Zp03DBConstants.monLightsSpecify, monthlyVisit.getMonLightsSpecify());
        cv.put(Zp03DBConstants.monSwelling, monthlyVisit.getMonSwelling());
        cv.put(Zp03DBConstants.monFetalMovement, monthlyVisit.getMonFetalMovement());
        cv.put(Zp03DBConstants.monMoveUsual, monthlyVisit.getMonMoveUsual());
        cv.put(Zp03DBConstants.monMoveDecrease, monthlyVisit.getMonMoveDecrease());
        cv.put(Zp03DBConstants.monContractions, monthlyVisit.getMonContractions());
        cv.put(Zp03DBConstants.monContractWeek, monthlyVisit.getMonContractWeek());
        cv.put(Zp03DBConstants.monContractDay, monthlyVisit.getMonContractDay());
        cv.put(Zp03DBConstants.monContractHour, monthlyVisit.getMonContractHour());
        cv.put(Zp03DBConstants.monContract10min, monthlyVisit.getMonContract10min());
        cv.put(Zp03DBConstants.monVaginalDischarge, monthlyVisit.getMonVaginalDischarge());
        cv.put(Zp03DBConstants.monCharacDischarge, monthlyVisit.getMonCharacDischarge());
        cv.put(Zp03DBConstants.monBleeding, monthlyVisit.getMonBleeding());
        cv.put(Zp03DBConstants.monBleedingCharac, monthlyVisit.getMonBleedingCharac());

        cv.put(Zp03DBConstants.monUtiTold, monthlyVisit.getMonUtiTold());
        cv.put(Zp03DBConstants.monPrenatalDay, monthlyVisit.getMonPrenatalDay());
        cv.put(Zp03DBConstants.monPrenatalMonth, monthlyVisit.getMonPrenatalMonth());
        cv.put(Zp03DBConstants.monPrenatalYear, monthlyVisit.getMonPrenatalYear());
        cv.put(Zp03DBConstants.monFeverSymptom, monthlyVisit.getMonFeverSymptom());
        cv.put(Zp03DBConstants.monRash, monthlyVisit.getMonRash());
        cv.put(Zp03DBConstants.monItch, monthlyVisit.getMonItch());
        cv.put(Zp03DBConstants.monRashFirst, monthlyVisit.getMonRashFirst());
        cv.put(Zp03DBConstants.monRashDay, monthlyVisit.getMonRashDay());
        cv.put(Zp03DBConstants.monRashMonth, monthlyVisit.getMonRashMonth());
        cv.put(Zp03DBConstants.monRashYear, monthlyVisit.getMonRashYear());
        cv.put(Zp03DBConstants.monRashDuration, monthlyVisit.getMonRashDuration());
        cv.put(Zp03DBConstants.monRashSpread, monthlyVisit.getMonRashSpread());
        cv.put(Zp03DBConstants.monSpreadPart, monthlyVisit.getMonSpreadPart());
        cv.put(Zp03DBConstants.monFeverExperience, monthlyVisit.getMonFeverExperience());
        cv.put(Zp03DBConstants.monTempMeasure, monthlyVisit.getMonTempMeasure());
        cv.put(Zp03DBConstants.monHighTemp, monthlyVisit.getMonHighTemp());
        cv.put(Zp03DBConstants.monHightemUnit, monthlyVisit.getMonHightemUnit());
        cv.put(Zp03DBConstants.monTempunknown, monthlyVisit.getMonTempunknown());
        cv.put(Zp03DBConstants.monFeverDay, monthlyVisit.getMonFeverDay());
        cv.put(Zp03DBConstants.monFeverMonth, monthlyVisit.getMonFeverMonth());
        cv.put(Zp03DBConstants.monFeverYear, monthlyVisit.getMonFeverYear());
        cv.put(Zp03DBConstants.monFeverDuration, monthlyVisit.getMonFeverDuration());
        cv.put(Zp03DBConstants.monRedeyes, monthlyVisit.getMonRedeyes());
        cv.put(Zp03DBConstants.monRedeyesDay, monthlyVisit.getMonRedeyesDay());
        cv.put(Zp03DBConstants.monRedeyesMonth, monthlyVisit.getMonRedeyesMonth());
        cv.put(Zp03DBConstants.monRedeyesYear, monthlyVisit.getMonRedeyesYear());
        cv.put(Zp03DBConstants.monRedeyesDuration, monthlyVisit.getMonRedeyesDuration());
        cv.put(Zp03DBConstants.monJoint, monthlyVisit.getMonJoint());
        cv.put(Zp03DBConstants.monJointDay, monthlyVisit.getMonJointDay());
        cv.put(Zp03DBConstants.monJointMonth, monthlyVisit.getMonJointMonth());
        cv.put(Zp03DBConstants.monJointYear, monthlyVisit.getMonJointYear());
        cv.put(Zp03DBConstants.monJointDuration, monthlyVisit.getMonJointDuration());
        cv.put(Zp03DBConstants.monHeadache, monthlyVisit.getMonHeadache());

        cv.put(Zp03DBConstants.monHeadacheDay, monthlyVisit.getMonHeadacheDay());
        cv.put(Zp03DBConstants.monHeadacheMonth, monthlyVisit.getMonHeadacheMonth());
        cv.put(Zp03DBConstants.monHeadacheYear, monthlyVisit.getMonHeadacheYear());
        cv.put(Zp03DBConstants.monHeadacheDuration, monthlyVisit.getMonHeadacheDuration());
        cv.put(Zp03DBConstants.monSymptomOther, monthlyVisit.getMonSymptomOther());
        cv.put(Zp03DBConstants.monSpecifySymptom, monthlyVisit.getMonSpecifySymptom());
        cv.put(Zp03DBConstants.monOtherSymptom, monthlyVisit.getMonOtherSymptom());
        cv.put(Zp03DBConstants.monMedicare, monthlyVisit.getMonMedicare());
        cv.put(Zp03DBConstants.monCareDay, monthlyVisit.getMonCareDay());
        cv.put(Zp03DBConstants.monCareMonth, monthlyVisit.getMonCareMonth());
        cv.put(Zp03DBConstants.monCareYear, monthlyVisit.getMonCareYear());
        cv.put(Zp03DBConstants.monCareFacility, monthlyVisit.getMonCareFacility());
        cv.put(Zp03DBConstants.monHospitalized, monthlyVisit.getMonHospitalized());
        cv.put(Zp03DBConstants.monHospital, monthlyVisit.getMonHospital());
        cv.put(Zp03DBConstants.monDiagRubella, monthlyVisit.getMonDiagRubella());
        cv.put(Zp03DBConstants.monDiagDengue, monthlyVisit.getMonDiagDengue());
        cv.put(Zp03DBConstants.monDiagChikung, monthlyVisit.getMonDiagChikung());
        cv.put(Zp03DBConstants.monDiagZika, monthlyVisit.getMonDiagZika());
        cv.put(Zp03DBConstants.monDiagCytome, monthlyVisit.getMonDiagCytome());
        cv.put(Zp03DBConstants.monMedicine, monthlyVisit.getMonMedicine());
        cv.put(Zp03DBConstants.monMedcineName, monthlyVisit.getMonMedcineName());
        cv.put(Zp03DBConstants.monSymptomDiary, monthlyVisit.getMonSymptomDiary());
        cv.put(Zp03DBConstants.monGuillainbarre, monthlyVisit.getMonGuillainbarre());
        cv.put(Zp03DBConstants.monTingling, monthlyVisit.getMonTingling());
        cv.put(Zp03DBConstants.monTinglingArm, monthlyVisit.getMonTinglingArm());
        cv.put(Zp03DBConstants.monTinglingLeg, monthlyVisit.getMonTinglingLeg());
        cv.put(Zp03DBConstants.monTinglingHand, monthlyVisit.getMonTinglingHand());
        cv.put(Zp03DBConstants.monTinglingFoot, monthlyVisit.getMonTinglingFoot());
        cv.put(Zp03DBConstants.monTinglingFace, monthlyVisit.getMonTinglingFace());
        cv.put(Zp03DBConstants.monTinglingOther, monthlyVisit.getMonTinglingOther());
        cv.put(Zp03DBConstants.monSensationMin, monthlyVisit.getMonSensationMin());
        cv.put(Zp03DBConstants.monSensationHr, monthlyVisit.getMonSensationHr());
        cv.put(Zp03DBConstants.monSenstaionDay, monthlyVisit.getMonSenstaionDay());

        cv.put(Zp03DBConstants.monInjury, monthlyVisit.getMonInjury());
        cv.put(Zp03DBConstants.monTinglingDay, monthlyVisit.getMonTinglingDay());
        cv.put(Zp03DBConstants.monTinglingMonth, monthlyVisit.getMonTinglingMonth());
        cv.put(Zp03DBConstants.monTinglingYear, monthlyVisit.getMonTinglingYear());
        cv.put(Zp03DBConstants.monTinglingDuration, monthlyVisit.getMonTinglingDuration());
        cv.put(Zp03DBConstants.monNumbness, monthlyVisit.getMonNumbness());
        cv.put(Zp03DBConstants.monNumbArm, monthlyVisit.getMonNumbArm());
        cv.put(Zp03DBConstants.monNumbLeg, monthlyVisit.getMonNumbLeg());
        cv.put(Zp03DBConstants.monNumbHand, monthlyVisit.getMonNumbHand());
        cv.put(Zp03DBConstants.monNumbFoot, monthlyVisit.getMonNumbFoot());
        cv.put(Zp03DBConstants.monNumbFace, monthlyVisit.getMonNumbFace());
        cv.put(Zp03DBConstants.monNumbOther, monthlyVisit.getMonNumbOther());
        cv.put(Zp03DBConstants.monNumbDay, monthlyVisit.getMonNumbDay());
        cv.put(Zp03DBConstants.monNumbMonth, monthlyVisit.getMonNumbMonth());
        cv.put(Zp03DBConstants.monNumbYear, monthlyVisit.getMonNumbYear());
        cv.put(Zp03DBConstants.monNumbDuration, monthlyVisit.getMonNumbDuration());
        cv.put(Zp03DBConstants.monParalysis, monthlyVisit.getMonParalysis());
        cv.put(Zp03DBConstants.monParaArm, monthlyVisit.getMonParaArm());
        cv.put(Zp03DBConstants.monParaLeg, monthlyVisit.getMonParaLeg());
        cv.put(Zp03DBConstants.monParaHand, monthlyVisit.getMonParaHand());
        cv.put(Zp03DBConstants.monParaFoot, monthlyVisit.getMonParaFoot());
        cv.put(Zp03DBConstants.monParaFace, monthlyVisit.getMonParaFace());
        cv.put(Zp03DBConstants.monParaOther, monthlyVisit.getMonParaOther());
        cv.put(Zp03DBConstants.monParaDay, monthlyVisit.getMonParaDay());
        cv.put(Zp03DBConstants.monParaMonth, monthlyVisit.getMonParaMonth());
        cv.put(Zp03DBConstants.monParaYear, monthlyVisit.getMonParaYear());
        cv.put(Zp03DBConstants.monParaDuration, monthlyVisit.getMonParaDuration());
        cv.put(Zp03DBConstants.monResultsProvided, monthlyVisit.getMonResultsProvided());
        cv.put(Zp03DBConstants.monCounseling, monthlyVisit.getMonCounseling());
        cv.put(Zp03DBConstants.monResultsOther, monthlyVisit.getMonResultsOther());
        if (monthlyVisit.getMonOneweekDate()!=null) cv.put(Zp03DBConstants.monOneweekDate, monthlyVisit.getMonOneweekDate().getTime());
        cv.put(Zp03DBConstants.monOneweekTime, monthlyVisit.getMonOneweekTime());
        cv.put(Zp03DBConstants.monProvideSym, monthlyVisit.getMonProvideSym());
        cv.put(Zp03DBConstants.monReminderPreg, monthlyVisit.getMonReminderPreg());
        cv.put(Zp03DBConstants.monReminderProvided, monthlyVisit.getMonReminderProvided());
        if (monthlyVisit.getMonNextDate()!=null) cv.put(Zp03DBConstants.monNextDate, monthlyVisit.getMonNextDate().getTime());
        cv.put(Zp03DBConstants.monNextTime, monthlyVisit.getMonNextTime());
        cv.put(Zp03DBConstants.monIdCompleting, monthlyVisit.getMonIdCompleting());
        if (monthlyVisit.getMonDateCompleted()!=null) cv.put(Zp03DBConstants.monDateCompleted, monthlyVisit.getMonDateCompleted().getTime());
        cv.put(Zp03DBConstants.monIdReviewer, monthlyVisit.getMonIdReviewer());
        if (monthlyVisit.getMonDateReviewed()!=null) cv.put(Zp03DBConstants.monDateReviewed, monthlyVisit.getMonDateReviewed().getTime());
        cv.put(Zp03DBConstants.monIdDataEntry, monthlyVisit.getMonIdDataEntry());
        if (monthlyVisit.getMonDateEntered()!=null) cv.put(Zp03DBConstants.monDateEntered, monthlyVisit.getMonDateEntered().getTime());

        if (monthlyVisit.getRecordDate() != null) cv.put(MainDBConstants.recordDate, monthlyVisit.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, monthlyVisit.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(monthlyVisit.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, monthlyVisit.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, monthlyVisit.getInstancePath());
        cv.put(MainDBConstants.STATUS, monthlyVisit.getEstado());
        cv.put(MainDBConstants.START, monthlyVisit.getStart());
        cv.put(MainDBConstants.END, monthlyVisit.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, monthlyVisit.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, monthlyVisit.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, monthlyVisit.getPhonenumber());
        if (monthlyVisit.getToday() != null) cv.put(MainDBConstants.TODAY, monthlyVisit.getToday().getTime());

        return cv;
    }

    public static Zp03MonthlyVisit crearZp03MonthlyVisit(Cursor cursorMV){
        Zp03MonthlyVisit monthlyVisit = new Zp03MonthlyVisit();

        monthlyVisit.setRecordId(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.recordId)));
        monthlyVisit.setRedcapEventName(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.redcapEventName)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monVisitDate))>0) monthlyVisit.setMonVisitDate(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monVisitDate))));
        monthlyVisit.setMonVisitType(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monVisitType)));
        monthlyVisit.setMonReasonMissed(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monReasonMissed)));
        monthlyVisit.setMonOtherReschedu(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monOtherReschedu)));
        monthlyVisit.setMonReasonUnscheduled(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monReasonUnscheduled)));
        monthlyVisit.setMonOtherUnscheduled(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monOtherUnscheduled)));
        if (cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monMotherWt))>0) monthlyVisit.setMonMotherWt(cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monMotherWt)));
        monthlyVisit.setMonWtUnit(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monWtUnit)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monSystolic))>0) monthlyVisit.setMonSystolic(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monSystolic)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monDiastolic))>0) monthlyVisit.setMonDiastolic(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monDiastolic)));
        if (cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monTemperature))>0)monthlyVisit.setMonTemperature(cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monTemperature)));
        monthlyVisit.setMonTempUnit(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTempUnit)));
        monthlyVisit.setMonPregnancyLoss(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monPregnancyLoss)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateLoss))>0) monthlyVisit.setMonDateLoss(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateLoss))));
        monthlyVisit.setMonPersisHeadache(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monPersisHeadache)));
        monthlyVisit.setMonDizziness(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDizziness)));
        monthlyVisit.setMonNausea(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNausea)));
        monthlyVisit.setMonVomiting(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monVomiting)));
        monthlyVisit.setMonLights(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monLights)));
        monthlyVisit.setMonLightsSpecify(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monLightsSpecify)));
        monthlyVisit.setMonSwelling(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSwelling)));
        monthlyVisit.setMonFetalMovement(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFetalMovement)));
        monthlyVisit.setMonMoveUsual(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monMoveUsual)));
        monthlyVisit.setMonMoveDecrease(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monMoveDecrease)));
        monthlyVisit.setMonContractions(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monContractions)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractWeek))>0) monthlyVisit.setMonContractWeek(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractWeek)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractDay))>0) monthlyVisit.setMonContractDay(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractDay)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractHour))>0) monthlyVisit.setMonContractHour(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContractHour)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContract10min))>0) monthlyVisit.setMonContract10min(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monContract10min)));
        monthlyVisit.setMonVaginalDischarge(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monVaginalDischarge)));
        monthlyVisit.setMonCharacDischarge(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCharacDischarge)));
        monthlyVisit.setMonBleeding(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monBleeding)));
        monthlyVisit.setMonBleedingCharac(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monBleedingCharac)));
        monthlyVisit.setMonUtiTold(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monUtiTold)));
        monthlyVisit.setMonPrenatalDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monPrenatalDay)));
        monthlyVisit.setMonPrenatalMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monPrenatalMonth)));
        monthlyVisit.setMonPrenatalYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monPrenatalYear)));
        monthlyVisit.setMonFeverSymptom(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFeverSymptom)));
        monthlyVisit.setMonRash(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRash)));
        monthlyVisit.setMonItch(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monItch)));
        monthlyVisit.setMonRashFirst(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRashFirst)));
        monthlyVisit.setMonRashDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRashDay)));
        monthlyVisit.setMonRashMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRashMonth)));
        monthlyVisit.setMonRashYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRashYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monRashDuration))>0) monthlyVisit.setMonRashDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monRashDuration)));
        monthlyVisit.setMonRashSpread(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRashSpread)));
        monthlyVisit.setMonSpreadPart(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSpreadPart)));
        monthlyVisit.setMonFeverExperience(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFeverExperience)));
        monthlyVisit.setMonTempMeasure(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTempMeasure)));
        if (cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monHighTemp))>0) monthlyVisit.setMonHighTemp(cursorMV.getFloat(cursorMV.getColumnIndex(Zp03DBConstants.monHighTemp)));
        monthlyVisit.setMonHightemUnit(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHightemUnit)));
        monthlyVisit.setMonTempunknown(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTempunknown)));
        monthlyVisit.setMonFeverDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFeverDay)));
        monthlyVisit.setMonFeverMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFeverMonth)));
        monthlyVisit.setMonFeverYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monFeverYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monFeverDuration))>0) monthlyVisit.setMonFeverDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monFeverDuration)));
        monthlyVisit.setMonRedeyes(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyes)));
        monthlyVisit.setMonRedeyesDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyesDay)));
        monthlyVisit.setMonRedeyesMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyesMonth)));
        monthlyVisit.setMonRedeyesYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyesYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyesDuration))>0) monthlyVisit.setMonRedeyesDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monRedeyesDuration)));
        monthlyVisit.setMonJoint(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monJoint)));
        monthlyVisit.setMonJointDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monJointDay)));
        monthlyVisit.setMonJointMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monJointMonth)));
        monthlyVisit.setMonJointYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monJointYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monJointDuration))>0) monthlyVisit.setMonJointDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monJointDuration)));
        monthlyVisit.setMonHeadache(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHeadache)));
        monthlyVisit.setMonHeadacheDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHeadacheDay)));
        monthlyVisit.setMonHeadacheMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHeadacheMonth)));
        monthlyVisit.setMonHeadacheYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHeadacheYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monHeadacheDuration))>0) monthlyVisit.setMonHeadacheDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monHeadacheDuration)));
        monthlyVisit.setMonSymptomOther(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSymptomOther)));
        monthlyVisit.setMonSpecifySymptom(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSpecifySymptom)));
        monthlyVisit.setMonOtherSymptom(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monOtherSymptom)));
        monthlyVisit.setMonMedicare(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monMedicare)));
        monthlyVisit.setMonCareDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCareDay)));
        monthlyVisit.setMonCareMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCareMonth)));
        monthlyVisit.setMonCareYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCareYear)));
        monthlyVisit.setMonCareFacility(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCareFacility)));
        monthlyVisit.setMonHospitalized(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHospitalized)));
        monthlyVisit.setMonHospital(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monHospital)));
        monthlyVisit.setMonDiagRubella(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDiagRubella)));
        monthlyVisit.setMonDiagDengue(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDiagDengue)));
        monthlyVisit.setMonDiagChikung(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDiagChikung)));
        monthlyVisit.setMonDiagZika(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDiagZika)));
        monthlyVisit.setMonDiagCytome(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monDiagCytome)));
        monthlyVisit.setMonMedicine(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monMedicine)));
        monthlyVisit.setMonMedcineName(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monMedcineName)));
        monthlyVisit.setMonSymptomDiary(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSymptomDiary)));
        monthlyVisit.setMonGuillainbarre(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monGuillainbarre)));
        monthlyVisit.setMonTingling(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTingling)));
        monthlyVisit.setMonTinglingArm(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingArm)));
        monthlyVisit.setMonTinglingLeg(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingLeg)));
        monthlyVisit.setMonTinglingHand(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingHand)));
        monthlyVisit.setMonTinglingFoot(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingFoot)));
        monthlyVisit.setMonTinglingFace(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingFace)));
        monthlyVisit.setMonTinglingOther(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingOther)));
        monthlyVisit.setMonSensationMin(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSensationMin)));
        monthlyVisit.setMonSensationHr(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSensationHr)));
        monthlyVisit.setMonSenstaionDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monSenstaionDay)));
        monthlyVisit.setMonInjury(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monInjury)));
        monthlyVisit.setMonTinglingDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingDay)));
        monthlyVisit.setMonTinglingMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingMonth)));
        monthlyVisit.setMonTinglingYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingDuration))>0) monthlyVisit.setMonTinglingDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monTinglingDuration)));
        monthlyVisit.setMonNumbness(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbness)));
        monthlyVisit.setMonNumbArm(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbArm)));
        monthlyVisit.setMonNumbLeg(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbLeg)));
        monthlyVisit.setMonNumbHand(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbHand)));
        monthlyVisit.setMonNumbFoot(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbFoot)));
        monthlyVisit.setMonNumbFace(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbFace)));
        monthlyVisit.setMonNumbOther(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbOther)));
        monthlyVisit.setMonNumbDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbDay)));
        monthlyVisit.setMonNumbMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbMonth)));
        monthlyVisit.setMonNumbYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNumbYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monNumbDuration))>0) monthlyVisit.setMonNumbDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monNumbDuration)));
        monthlyVisit.setMonParalysis(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParalysis)));
        monthlyVisit.setMonParaArm(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaArm)));
        monthlyVisit.setMonParaLeg(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaLeg)));
        monthlyVisit.setMonParaHand(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaHand)));
        monthlyVisit.setMonParaFoot(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaFoot)));
        monthlyVisit.setMonParaFace(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaFace)));
        monthlyVisit.setMonParaOther(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaOther)));
        monthlyVisit.setMonParaDay(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaDay)));
        monthlyVisit.setMonParaMonth(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaMonth)));
        monthlyVisit.setMonParaYear(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monParaYear)));
        if (cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monParaDuration))>0) monthlyVisit.setMonParaDuration(cursorMV.getInt(cursorMV.getColumnIndex(Zp03DBConstants.monParaDuration)));
        monthlyVisit.setMonResultsProvided(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monResultsProvided)));
        monthlyVisit.setMonCounseling(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monCounseling)));
        monthlyVisit.setMonResultsOther(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monResultsOther)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monOneweekDate))>0) monthlyVisit.setMonOneweekDate(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monOneweekDate))));
        monthlyVisit.setMonOneweekTime(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monOneweekTime)));
        monthlyVisit.setMonProvideSym(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monProvideSym)));
        monthlyVisit.setMonReminderPreg(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monReminderPreg)));
        monthlyVisit.setMonReminderProvided(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monReminderProvided)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monNextDate))>0) monthlyVisit.setMonNextDate(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monNextDate))));
        monthlyVisit.setMonNextTime(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monNextTime)));
        monthlyVisit.setMonIdCompleting(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monIdCompleting)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateCompleted))>0) monthlyVisit.setMonDateCompleted(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateCompleted))));
        monthlyVisit.setMonIdReviewer(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monIdReviewer)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateReviewed))>0) monthlyVisit.setMonDateReviewed(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateReviewed))));
        monthlyVisit.setMonIdDataEntry(cursorMV.getString(cursorMV.getColumnIndex(Zp03DBConstants.monIdDataEntry)));
        if (cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateEntered))>0) monthlyVisit.setMonDateEntered(new Date(cursorMV.getLong(cursorMV.getColumnIndex(Zp03DBConstants.monDateEntered))));

        if(cursorMV.getLong(cursorMV.getColumnIndex(MainDBConstants.recordDate))>0) monthlyVisit.setRecordDate(new Date(cursorMV.getLong(cursorMV.getColumnIndex(MainDBConstants.recordDate))));
        monthlyVisit.setRecordUser(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.recordUser)));
        monthlyVisit.setPasive(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        monthlyVisit.setIdInstancia(cursorMV.getInt(cursorMV.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        monthlyVisit.setInstancePath(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.FILE_PATH)));
        monthlyVisit.setEstado(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.STATUS)));
        monthlyVisit.setStart(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.START)));
        monthlyVisit.setEnd(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.END)));
        monthlyVisit.setSimserial(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        monthlyVisit.setPhonenumber(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        monthlyVisit.setDeviceid(cursorMV.getString(cursorMV.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorMV.getLong(cursorMV.getColumnIndex(MainDBConstants.TODAY))>0) monthlyVisit.setToday(new Date(cursorMV.getLong(cursorMV.getColumnIndex(MainDBConstants.TODAY))));

        return monthlyVisit;
    }
}
