package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp06DeliveryAnd6weekVisit;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp06DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 10/25/2016.
 * V1.0
 */
public class Zp06DeliveryAnd6weekVisitHelper {

    public static ContentValues crearZp06DeliveryAnd6weekVisit(Zp06DeliveryAnd6weekVisit deliveryAnd6weekVisit){
        ContentValues cv = new ContentValues();

        cv.put(Zp06DBConstants.recordId, deliveryAnd6weekVisit.getRecordId());
        cv.put(Zp06DBConstants.redcapEventName, deliveryAnd6weekVisit.getRedcapEventName());
        if (deliveryAnd6weekVisit.getDeliVisitDate()!=null) cv.put(Zp06DBConstants.deliVisitDate, deliveryAnd6weekVisit.getDeliVisitDate().getTime());
        cv.put(Zp06DBConstants.deliVisitStatus, deliveryAnd6weekVisit.getDeliVisitStatus());
        cv.put(Zp06DBConstants.deliVisitType, deliveryAnd6weekVisit.getDeliVisitType());
        cv.put(Zp06DBConstants.deliMotherWt, deliveryAnd6weekVisit.getDeliMotherWt());
        cv.put(Zp06DBConstants.deliWtUnit, deliveryAnd6weekVisit.getDeliWtUnit());
        cv.put(Zp06DBConstants.deliSystolic, deliveryAnd6weekVisit.getDeliSystolic());
        cv.put(Zp06DBConstants.deliDiastolic, deliveryAnd6weekVisit.getDeliDiastolic());
        cv.put(Zp06DBConstants.deliTemperature, deliveryAnd6weekVisit.getDeliTemperature());
        cv.put(Zp06DBConstants.deliTempUnit, deliveryAnd6weekVisit.getDeliTempUnit());
        if (deliveryAnd6weekVisit.getDeliDeliveryDate()!=null) cv.put(Zp06DBConstants.deliDeliveryDate, deliveryAnd6weekVisit.getDeliDeliveryDate().getTime());
        cv.put(Zp06DBConstants.deliMode, deliveryAnd6weekVisit.getDeliMode());
        cv.put(Zp06DBConstants.deliDeliveryWho, deliveryAnd6weekVisit.getDeliDeliveryWho());
        cv.put(Zp06DBConstants.deliDeliveryOccur, deliveryAnd6weekVisit.getDeliDeliveryOccur());
        cv.put(Zp06DBConstants.deliHospitalId, deliveryAnd6weekVisit.getDeliHospitalId());
        cv.put(Zp06DBConstants.deliClinicId, deliveryAnd6weekVisit.getDeliClinicId());
        cv.put(Zp06DBConstants.deliDeliveryOther, deliveryAnd6weekVisit.getDeliDeliveryOther());
        cv.put(Zp06DBConstants.deliNumBirth, deliveryAnd6weekVisit.getDeliNumBirth());
        cv.put(Zp06DBConstants.deliFetalOutcome1, deliveryAnd6weekVisit.getDeliFetalOutcome1());
        cv.put(Zp06DBConstants.deliCauseDeath1, deliveryAnd6weekVisit.getDeliCauseDeath1());
        cv.put(Zp06DBConstants.deliSexBaby1, deliveryAnd6weekVisit.getDeliSexBaby1());
        cv.put(Zp06DBConstants.deliFetalOutcome2, deliveryAnd6weekVisit.getDeliFetalOutcome2());
        cv.put(Zp06DBConstants.deliCauseDeath2, deliveryAnd6weekVisit.getDeliCauseDeath2());
        cv.put(Zp06DBConstants.deliSexBaby2, deliveryAnd6weekVisit.getDeliSexBaby2());
        cv.put(Zp06DBConstants.deliFetalOutcome3, deliveryAnd6weekVisit.getDeliFetalOutcome3());
        cv.put(Zp06DBConstants.deliCauseDeath3, deliveryAnd6weekVisit.getDeliCauseDeath3());
        cv.put(Zp06DBConstants.deliSexBaby3, deliveryAnd6weekVisit.getDeliSexBaby3());
        cv.put(Zp06DBConstants.deliConsentInfant, deliveryAnd6weekVisit.getDeliConsentInfant());
        cv.put(Zp06DBConstants.deliReasonNoconsent, deliveryAnd6weekVisit.getDeliReasonNoconsent());
        cv.put(Zp06DBConstants.deliNoconsentOther, deliveryAnd6weekVisit.getDeliNoconsentOther());
        cv.put(Zp06DBConstants.deliFeverSymptom, deliveryAnd6weekVisit.getDeliFeverSymptom());
        cv.put(Zp06DBConstants.deliRash, deliveryAnd6weekVisit.getDeliRash());
        cv.put(Zp06DBConstants.deliItch, deliveryAnd6weekVisit.getDeliItch());
        cv.put(Zp06DBConstants.deliRashFirst, deliveryAnd6weekVisit.getDeliRashFirst());
        cv.put(Zp06DBConstants.deliRashDay, deliveryAnd6weekVisit.getDeliRashDay());
        cv.put(Zp06DBConstants.deliRashMonth, deliveryAnd6weekVisit.getDeliRashMonth());
        cv.put(Zp06DBConstants.deliRashYear, deliveryAnd6weekVisit.getDeliRashYear());
        cv.put(Zp06DBConstants.deliRashDuration, deliveryAnd6weekVisit.getDeliRashDuration());
        cv.put(Zp06DBConstants.deliRashSpread, deliveryAnd6weekVisit.getDeliRashSpread());
        cv.put(Zp06DBConstants.deliSpreadPart, deliveryAnd6weekVisit.getDeliSpreadPart());
        cv.put(Zp06DBConstants.deliFeverExperience, deliveryAnd6weekVisit.getDeliFeverExperience());
        cv.put(Zp06DBConstants.deliTempMeasure, deliveryAnd6weekVisit.getDeliTempMeasure());
        cv.put(Zp06DBConstants.deliHighTemp, deliveryAnd6weekVisit.getDeliHighTemp());
        cv.put(Zp06DBConstants.deliHightemUnit, deliveryAnd6weekVisit.getDeliHightemUnit());
        cv.put(Zp06DBConstants.deliTempunknown, deliveryAnd6weekVisit.getDeliTempunknown());
        cv.put(Zp06DBConstants.deliFeverDay, deliveryAnd6weekVisit.getDeliFeverDay());
        cv.put(Zp06DBConstants.deliFeverMonth, deliveryAnd6weekVisit.getDeliFeverMonth());
        cv.put(Zp06DBConstants.deliFeverYear, deliveryAnd6weekVisit.getDeliFeverYear());
        cv.put(Zp06DBConstants.deliFeverDuration, deliveryAnd6weekVisit.getDeliFeverDuration());
        cv.put(Zp06DBConstants.deliRedeyes, deliveryAnd6weekVisit.getDeliRedeyes());
        cv.put(Zp06DBConstants.deliRedeyesDay, deliveryAnd6weekVisit.getDeliRedeyesDay());
        cv.put(Zp06DBConstants.deliRedeyesMonth, deliveryAnd6weekVisit.getDeliRedeyesMonth());
        cv.put(Zp06DBConstants.deliRedeyesYear, deliveryAnd6weekVisit.getDeliRedeyesYear());
        cv.put(Zp06DBConstants.deliRedeyesDuration, deliveryAnd6weekVisit.getDeliRedeyesDuration());
        cv.put(Zp06DBConstants.deliJoint, deliveryAnd6weekVisit.getDeliJoint());
        cv.put(Zp06DBConstants.deliJointDay, deliveryAnd6weekVisit.getDeliJointDay());
        cv.put(Zp06DBConstants.deliJointMonth, deliveryAnd6weekVisit.getDeliJointMonth());
        cv.put(Zp06DBConstants.deliJointYear, deliveryAnd6weekVisit.getDeliJointYear());
        cv.put(Zp06DBConstants.deliJointDuration, deliveryAnd6weekVisit.getDeliJointDuration());
        cv.put(Zp06DBConstants.deliHeadache, deliveryAnd6weekVisit.getDeliHeadache());
        cv.put(Zp06DBConstants.deliHeadacheDay, deliveryAnd6weekVisit.getDeliHeadacheDay());
        cv.put(Zp06DBConstants.deliHeadacheMonth, deliveryAnd6weekVisit.getDeliHeadacheMonth());
        cv.put(Zp06DBConstants.deliHeadacheYear, deliveryAnd6weekVisit.getDeliHeadacheYear());
        cv.put(Zp06DBConstants.deliHeadacheDuration, deliveryAnd6weekVisit.getDeliHeadacheDuration());
        cv.put(Zp06DBConstants.deliSymptomOther, deliveryAnd6weekVisit.getDeliSymptomOther());
        cv.put(Zp06DBConstants.deliSpecifySymptom, deliveryAnd6weekVisit.getDeliSpecifySymptom());
        cv.put(Zp06DBConstants.deliOtherSymptom, deliveryAnd6weekVisit.getDeliOtherSymptom());
        cv.put(Zp06DBConstants.deliMedicare, deliveryAnd6weekVisit.getDeliMedicare());
        cv.put(Zp06DBConstants.deliCareDay, deliveryAnd6weekVisit.getDeliCareDay());
        cv.put(Zp06DBConstants.deliCareMonth, deliveryAnd6weekVisit.getDeliCareMonth());
        cv.put(Zp06DBConstants.deliCareYear, deliveryAnd6weekVisit.getDeliCareYear());
        cv.put(Zp06DBConstants.deliCareFacility, deliveryAnd6weekVisit.getDeliCareFacility());
        cv.put(Zp06DBConstants.deliHospitalized, deliveryAnd6weekVisit.getDeliHospitalized());
        cv.put(Zp06DBConstants.deliHospital, deliveryAnd6weekVisit.getDeliHospital());
        cv.put(Zp06DBConstants.deliDiagRubella, deliveryAnd6weekVisit.getDeliDiagRubella());
        cv.put(Zp06DBConstants.deliDiagDengue, deliveryAnd6weekVisit.getDeliDiagDengue());
        cv.put(Zp06DBConstants.deliDiagChikung, deliveryAnd6weekVisit.getDeliDiagChikung());
        cv.put(Zp06DBConstants.deliDiagZika, deliveryAnd6weekVisit.getDeliDiagZika());
        cv.put(Zp06DBConstants.deliDiagCytome, deliveryAnd6weekVisit.getDeliDiagCytome());
        cv.put(Zp06DBConstants.deliMedicine, deliveryAnd6weekVisit.getDeliMedicine());
        cv.put(Zp06DBConstants.deliMedcineName, deliveryAnd6weekVisit.getDeliMedcineName());
        cv.put(Zp06DBConstants.deliSymptomDiary, deliveryAnd6weekVisit.getDeliSymptomDiary());
        cv.put(Zp06DBConstants.deliGuillainbarre, deliveryAnd6weekVisit.getDeliGuillainbarre());
        cv.put(Zp06DBConstants.deliTingling, deliveryAnd6weekVisit.getDeliTingling());
        cv.put(Zp06DBConstants.deliTinglingArm, deliveryAnd6weekVisit.getDeliTinglingArm());
        cv.put(Zp06DBConstants.deliTinglingLeg, deliveryAnd6weekVisit.getDeliTinglingLeg());
        cv.put(Zp06DBConstants.deliTinglingHand, deliveryAnd6weekVisit.getDeliTinglingHand());
        cv.put(Zp06DBConstants.deliTinglingFoot, deliveryAnd6weekVisit.getDeliTinglingFoot());
        cv.put(Zp06DBConstants.deliTinglingFace, deliveryAnd6weekVisit.getDeliTinglingFace());
        cv.put(Zp06DBConstants.deliTinglingOther, deliveryAnd6weekVisit.getDeliTinglingOther());
        cv.put(Zp06DBConstants.deliSensationMin, deliveryAnd6weekVisit.getDeliSensationMin());
        cv.put(Zp06DBConstants.deliSensationHr, deliveryAnd6weekVisit.getDeliSensationHr());
        cv.put(Zp06DBConstants.deliSenstaionDay, deliveryAnd6weekVisit.getDeliSenstaionDay());
        cv.put(Zp06DBConstants.deliInjury, deliveryAnd6weekVisit.getDeliInjury());
        cv.put(Zp06DBConstants.deliTinglingDay, deliveryAnd6weekVisit.getDeliTinglingDay());
        cv.put(Zp06DBConstants.deliTinglingMonth, deliveryAnd6weekVisit.getDeliTinglingMonth());
        cv.put(Zp06DBConstants.deliTinglingYear, deliveryAnd6weekVisit.getDeliTinglingYear());
        cv.put(Zp06DBConstants.deliTinglingDuration, deliveryAnd6weekVisit.getDeliTinglingDuration());
        cv.put(Zp06DBConstants.deliNumbness, deliveryAnd6weekVisit.getDeliNumbness());
        cv.put(Zp06DBConstants.deliNumbArm, deliveryAnd6weekVisit.getDeliNumbArm());
        cv.put(Zp06DBConstants.deliNumbLeg, deliveryAnd6weekVisit.getDeliNumbLeg());
        cv.put(Zp06DBConstants.deliNumbHand, deliveryAnd6weekVisit.getDeliNumbHand());
        cv.put(Zp06DBConstants.deliNumbFoot, deliveryAnd6weekVisit.getDeliNumbFoot());
        cv.put(Zp06DBConstants.deliNumbFace, deliveryAnd6weekVisit.getDeliNumbFace());
        cv.put(Zp06DBConstants.deliNumbOther, deliveryAnd6weekVisit.getDeliNumbOther());
        cv.put(Zp06DBConstants.deliNumbDay, deliveryAnd6weekVisit.getDeliNumbDay());
        cv.put(Zp06DBConstants.deliNumbMonth, deliveryAnd6weekVisit.getDeliNumbMonth());
        cv.put(Zp06DBConstants.deliNumbYear, deliveryAnd6weekVisit.getDeliNumbYear());
        cv.put(Zp06DBConstants.deliNumbDuration, deliveryAnd6weekVisit.getDeliNumbDuration());
        cv.put(Zp06DBConstants.deliParalysis, deliveryAnd6weekVisit.getDeliParalysis());
        cv.put(Zp06DBConstants.deliParaArm, deliveryAnd6weekVisit.getDeliParaArm());
        cv.put(Zp06DBConstants.deliParaLeg, deliveryAnd6weekVisit.getDeliParaLeg());
        cv.put(Zp06DBConstants.deliParaHand, deliveryAnd6weekVisit.getDeliParaHand());
        cv.put(Zp06DBConstants.deliParaFoot, deliveryAnd6weekVisit.getDeliParaFoot());
        cv.put(Zp06DBConstants.deliParaFace, deliveryAnd6weekVisit.getDeliParaFace());
        cv.put(Zp06DBConstants.deliParaOther, deliveryAnd6weekVisit.getDeliParaOther());
        cv.put(Zp06DBConstants.deliParaDay, deliveryAnd6weekVisit.getDeliParaDay());
        cv.put(Zp06DBConstants.deliParaMonth, deliveryAnd6weekVisit.getDeliParaMonth());
        cv.put(Zp06DBConstants.deliParaYear, deliveryAnd6weekVisit.getDeliParaYear());
        cv.put(Zp06DBConstants.deliParaDuration, deliveryAnd6weekVisit.getDeliParaDuration());
        cv.put(Zp06DBConstants.deliResultsProvided, deliveryAnd6weekVisit.getDeliResultsProvided());
        cv.put(Zp06DBConstants.deliCounseling, deliveryAnd6weekVisit.getDeliCounseling());
        cv.put(Zp06DBConstants.deliResultsOther, deliveryAnd6weekVisit.getDeliResultsOther());
        cv.put(Zp06DBConstants.deliIdCompleting, deliveryAnd6weekVisit.getDeliIdCompleting());
        if (deliveryAnd6weekVisit.getDeliDateCompleted()!=null) cv.put(Zp06DBConstants.deliDateCompleted, deliveryAnd6weekVisit.getDeliDateCompleted().getTime());
        cv.put(Zp06DBConstants.deliIdReviewer, deliveryAnd6weekVisit.getDeliIdReviewer());
        if (deliveryAnd6weekVisit.getDeliDateReviewed()!=null) cv.put(Zp06DBConstants.deliDateReviewed, deliveryAnd6weekVisit.getDeliDateReviewed().getTime());
        cv.put(Zp06DBConstants.deliIdDataEntry, deliveryAnd6weekVisit.getDeliIdDataEntry());
        if (deliveryAnd6weekVisit.getDeliDateEntered()!=null) cv.put(Zp06DBConstants.deliDateEntered, deliveryAnd6weekVisit.getDeliDateEntered().getTime());

        cv.put(Zp06DBConstants.deliHyperDisease, deliveryAnd6weekVisit.getDeliHyperDisease());
        cv.put(Zp06DBConstants.deliPreterm1, deliveryAnd6weekVisit.getDeliPreterm1());
        cv.put(Zp06DBConstants.deliPreterm2, deliveryAnd6weekVisit.getDeliPreterm2());
        cv.put(Zp06DBConstants.deliPreterm3, deliveryAnd6weekVisit.getDeliPreterm3());
        cv.put(Zp06DBConstants.deliDeliverEarly, deliveryAnd6weekVisit.getDeliDeliverEarly());
        
        if (deliveryAnd6weekVisit.getRecordDate() != null) cv.put(MainDBConstants.recordDate, deliveryAnd6weekVisit.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, deliveryAnd6weekVisit.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(deliveryAnd6weekVisit.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, deliveryAnd6weekVisit.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, deliveryAnd6weekVisit.getInstancePath());
        cv.put(MainDBConstants.STATUS, deliveryAnd6weekVisit.getEstado());
        cv.put(MainDBConstants.START, deliveryAnd6weekVisit.getStart());
        cv.put(MainDBConstants.END, deliveryAnd6weekVisit.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, deliveryAnd6weekVisit.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, deliveryAnd6weekVisit.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, deliveryAnd6weekVisit.getPhonenumber());
        if (deliveryAnd6weekVisit.getToday() != null) cv.put(MainDBConstants.TODAY, deliveryAnd6weekVisit.getToday().getTime());

        return cv;
    }

    public static Zp06DeliveryAnd6weekVisit crearZp06DeliveryAnd6weekVisit(Cursor cursor){
        Zp06DeliveryAnd6weekVisit deliveryAnd6weekVisit = new Zp06DeliveryAnd6weekVisit();

        deliveryAnd6weekVisit.setRecordId(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.recordId)));
        deliveryAnd6weekVisit.setRedcapEventName(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.redcapEventName)));

        if (cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliVisitDate))>0) deliveryAnd6weekVisit.setDeliVisitDate(new Date(cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliVisitDate))));

        deliveryAnd6weekVisit.setDeliVisitStatus(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliVisitStatus)));
        deliveryAnd6weekVisit.setDeliVisitType(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliVisitType)));

        if (cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliMotherWt))>0) deliveryAnd6weekVisit.setDeliMotherWt(cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliMotherWt)));

        deliveryAnd6weekVisit.setDeliWtUnit(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliWtUnit)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSystolic))>0) deliveryAnd6weekVisit.setDeliSystolic(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSystolic)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliDiastolic))>0) deliveryAnd6weekVisit.setDeliDiastolic(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliDiastolic)));
        if (cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliTemperature))>0) deliveryAnd6weekVisit.setDeliTemperature(cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliTemperature)));
        deliveryAnd6weekVisit.setDeliTempUnit(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTempUnit)));
        if (cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDeliveryDate))>0) deliveryAnd6weekVisit.setDeliDeliveryDate(new Date(cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDeliveryDate))));
        deliveryAnd6weekVisit.setDeliMode(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliMode)));
        deliveryAnd6weekVisit.setDeliDeliveryWho(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDeliveryWho)));
        deliveryAnd6weekVisit.setDeliDeliveryOccur(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDeliveryOccur)));
        deliveryAnd6weekVisit.setDeliHospitalId(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHospitalId)));
        deliveryAnd6weekVisit.setDeliClinicId(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliClinicId)));
        deliveryAnd6weekVisit.setDeliDeliveryOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDeliveryOther)));
        deliveryAnd6weekVisit.setDeliNumBirth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumBirth)));
        deliveryAnd6weekVisit.setDeliFetalOutcome1(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFetalOutcome1)));
        deliveryAnd6weekVisit.setDeliCauseDeath1(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCauseDeath1)));
        deliveryAnd6weekVisit.setDeliSexBaby1(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSexBaby1)));
        deliveryAnd6weekVisit.setDeliFetalOutcome2(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFetalOutcome2)));
        deliveryAnd6weekVisit.setDeliCauseDeath2(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCauseDeath2)));
        deliveryAnd6weekVisit.setDeliSexBaby2(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSexBaby2)));
        deliveryAnd6weekVisit.setDeliFetalOutcome3(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFetalOutcome3)));
        deliveryAnd6weekVisit.setDeliCauseDeath3(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCauseDeath3)));
        deliveryAnd6weekVisit.setDeliSexBaby3(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSexBaby3)));
        deliveryAnd6weekVisit.setDeliConsentInfant(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliConsentInfant)));
        deliveryAnd6weekVisit.setDeliReasonNoconsent(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliReasonNoconsent)));
        deliveryAnd6weekVisit.setDeliNoconsentOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNoconsentOther)));
        deliveryAnd6weekVisit.setDeliFeverSymptom(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFeverSymptom)));
        deliveryAnd6weekVisit.setDeliRash(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRash)));
        deliveryAnd6weekVisit.setDeliItch(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliItch)));
        deliveryAnd6weekVisit.setDeliRashFirst(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRashFirst)));
        deliveryAnd6weekVisit.setDeliRashDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRashDay)));
        deliveryAnd6weekVisit.setDeliRashMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRashMonth)));
        deliveryAnd6weekVisit.setDeliRashYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRashYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliRashDuration))>0) deliveryAnd6weekVisit.setDeliRashDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliRashDuration)));
        deliveryAnd6weekVisit.setDeliRashSpread(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRashSpread)));
        deliveryAnd6weekVisit.setDeliSpreadPart(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSpreadPart)));
        deliveryAnd6weekVisit.setDeliFeverExperience(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFeverExperience)));
        deliveryAnd6weekVisit.setDeliTempMeasure(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTempMeasure)));
        if (cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliHighTemp))>0) deliveryAnd6weekVisit.setDeliHighTemp(cursor.getFloat(cursor.getColumnIndex(Zp06DBConstants.deliHighTemp)));
        deliveryAnd6weekVisit.setDeliHightemUnit(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHightemUnit)));
        deliveryAnd6weekVisit.setDeliTempunknown(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTempunknown)));
        deliveryAnd6weekVisit.setDeliFeverDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFeverDay)));
        deliveryAnd6weekVisit.setDeliFeverMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFeverMonth)));
        deliveryAnd6weekVisit.setDeliFeverYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliFeverYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliFeverDuration))>0) deliveryAnd6weekVisit.setDeliFeverDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliFeverDuration)));
        deliveryAnd6weekVisit.setDeliRedeyes(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRedeyes)));
        deliveryAnd6weekVisit.setDeliRedeyesDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRedeyesDay)));
        deliveryAnd6weekVisit.setDeliRedeyesMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRedeyesMonth)));
        deliveryAnd6weekVisit.setDeliRedeyesYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliRedeyesYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliRedeyesDuration))>0) deliveryAnd6weekVisit.setDeliRedeyesDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliRedeyesDuration)));
        deliveryAnd6weekVisit.setDeliJoint(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliJoint)));
        deliveryAnd6weekVisit.setDeliJointDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliJointDay)));
        deliveryAnd6weekVisit.setDeliJointMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliJointMonth)));
        deliveryAnd6weekVisit.setDeliJointYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliJointYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliJointDuration))>0) deliveryAnd6weekVisit.setDeliJointDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliJointDuration)));
        deliveryAnd6weekVisit.setDeliHeadache(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHeadache)));
        deliveryAnd6weekVisit.setDeliHeadacheDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHeadacheDay)));
        deliveryAnd6weekVisit.setDeliHeadacheMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHeadacheMonth)));
        deliveryAnd6weekVisit.setDeliHeadacheYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHeadacheYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliHeadacheDuration))>0) deliveryAnd6weekVisit.setDeliHeadacheDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliHeadacheDuration)));
        deliveryAnd6weekVisit.setDeliSymptomOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSymptomOther)));
        deliveryAnd6weekVisit.setDeliSpecifySymptom(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSpecifySymptom)));
        deliveryAnd6weekVisit.setDeliOtherSymptom(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliOtherSymptom)));
        deliveryAnd6weekVisit.setDeliMedicare(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliMedicare)));
        deliveryAnd6weekVisit.setDeliCareDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCareDay)));
        deliveryAnd6weekVisit.setDeliCareMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCareMonth)));
        deliveryAnd6weekVisit.setDeliCareYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCareYear)));
        deliveryAnd6weekVisit.setDeliCareFacility(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCareFacility)));
        deliveryAnd6weekVisit.setDeliHospitalized(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHospitalized)));
        deliveryAnd6weekVisit.setDeliHospital(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHospital)));
        deliveryAnd6weekVisit.setDeliDiagRubella(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDiagRubella)));
        deliveryAnd6weekVisit.setDeliDiagDengue(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDiagDengue)));
        deliveryAnd6weekVisit.setDeliDiagChikung(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDiagChikung)));
        deliveryAnd6weekVisit.setDeliDiagZika(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDiagZika)));
        deliveryAnd6weekVisit.setDeliDiagCytome(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDiagCytome)));
        deliveryAnd6weekVisit.setDeliMedicine(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliMedicine)));
        deliveryAnd6weekVisit.setDeliMedcineName(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliMedcineName)));
        deliveryAnd6weekVisit.setDeliSymptomDiary(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliSymptomDiary)));
        deliveryAnd6weekVisit.setDeliGuillainbarre(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliGuillainbarre)));
        deliveryAnd6weekVisit.setDeliTingling(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTingling)));
        deliveryAnd6weekVisit.setDeliTinglingArm(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingArm)));
        deliveryAnd6weekVisit.setDeliTinglingLeg(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingLeg)));
        deliveryAnd6weekVisit.setDeliTinglingHand(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingHand)));
        deliveryAnd6weekVisit.setDeliTinglingFoot(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingFoot)));
        deliveryAnd6weekVisit.setDeliTinglingFace(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingFace)));
        deliveryAnd6weekVisit.setDeliTinglingOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingOther)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSensationMin))>0) deliveryAnd6weekVisit.setDeliSensationMin(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSensationMin)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSensationHr))>0) deliveryAnd6weekVisit.setDeliSensationHr(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSensationHr)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSenstaionDay))>0) deliveryAnd6weekVisit.setDeliSenstaionDay(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliSenstaionDay)));
        deliveryAnd6weekVisit.setDeliInjury(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliInjury)));
        deliveryAnd6weekVisit.setDeliTinglingDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingDay)));
        deliveryAnd6weekVisit.setDeliTinglingMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingMonth)));
        deliveryAnd6weekVisit.setDeliTinglingYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliTinglingYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliTinglingDuration))>0) deliveryAnd6weekVisit.setDeliTinglingDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliTinglingDuration)));
        deliveryAnd6weekVisit.setDeliNumbness(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbness)));
        deliveryAnd6weekVisit.setDeliNumbArm(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbArm)));
        deliveryAnd6weekVisit.setDeliNumbLeg(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbLeg)));
        deliveryAnd6weekVisit.setDeliNumbHand(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbHand)));
        deliveryAnd6weekVisit.setDeliNumbFoot(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbFoot)));
        deliveryAnd6weekVisit.setDeliNumbFace(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbFace)));
        deliveryAnd6weekVisit.setDeliNumbOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbOther)));
        deliveryAnd6weekVisit.setDeliNumbDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbDay)));
        deliveryAnd6weekVisit.setDeliNumbMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbMonth)));
        deliveryAnd6weekVisit.setDeliNumbYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliNumbYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliNumbDuration))>0) deliveryAnd6weekVisit.setDeliNumbDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliNumbDuration)));
        deliveryAnd6weekVisit.setDeliParalysis(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParalysis)));
        deliveryAnd6weekVisit.setDeliParaArm(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaArm)));
        deliveryAnd6weekVisit.setDeliParaLeg(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaLeg)));
        deliveryAnd6weekVisit.setDeliParaHand(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaHand)));
        deliveryAnd6weekVisit.setDeliParaFoot(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaFoot)));
        deliveryAnd6weekVisit.setDeliParaFace(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaFace)));
        deliveryAnd6weekVisit.setDeliParaOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaOther)));
        deliveryAnd6weekVisit.setDeliParaDay(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaDay)));
        deliveryAnd6weekVisit.setDeliParaMonth(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaMonth)));
        deliveryAnd6weekVisit.setDeliParaYear(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliParaYear)));
        if (cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliParaDuration))>0) deliveryAnd6weekVisit.setDeliParaDuration(cursor.getInt(cursor.getColumnIndex(Zp06DBConstants.deliParaDuration)));
        deliveryAnd6weekVisit.setDeliResultsProvided(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliResultsProvided)));
        deliveryAnd6weekVisit.setDeliCounseling(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliCounseling)));
        deliveryAnd6weekVisit.setDeliResultsOther(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliResultsOther)));
        deliveryAnd6weekVisit.setDeliIdCompleting(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliIdCompleting)));
        if (cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateCompleted))>0) deliveryAnd6weekVisit.setDeliDateCompleted(new Date(cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateCompleted))));
        deliveryAnd6weekVisit.setDeliIdReviewer(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliIdReviewer)));
        if (cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateReviewed))>0) deliveryAnd6weekVisit.setDeliDateReviewed(new Date(cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateReviewed))));
        deliveryAnd6weekVisit.setDeliIdDataEntry(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliIdDataEntry)));
        if (cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateEntered))>0) deliveryAnd6weekVisit.setDeliDateEntered(new Date(cursor.getLong(cursor.getColumnIndex(Zp06DBConstants.deliDateEntered))));

        deliveryAnd6weekVisit.setDeliHyperDisease(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliHyperDisease)));
        deliveryAnd6weekVisit.setDeliPreterm1(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliPreterm1)));
        deliveryAnd6weekVisit.setDeliPreterm2(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliPreterm2)));
        deliveryAnd6weekVisit.setDeliPreterm3(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliPreterm3)));
        deliveryAnd6weekVisit.setDeliDeliverEarly(cursor.getString(cursor.getColumnIndex(Zp06DBConstants.deliDeliverEarly)));
        
        if(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))>0) deliveryAnd6weekVisit.setRecordDate(new Date(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))));
        deliveryAnd6weekVisit.setRecordUser(cursor.getString(cursor.getColumnIndex(MainDBConstants.recordUser)));
        deliveryAnd6weekVisit.setPasive(cursor.getString(cursor.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        deliveryAnd6weekVisit.setIdInstancia(cursor.getInt(cursor.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        deliveryAnd6weekVisit.setInstancePath(cursor.getString(cursor.getColumnIndex(MainDBConstants.FILE_PATH)));
        deliveryAnd6weekVisit.setEstado(cursor.getString(cursor.getColumnIndex(MainDBConstants.STATUS)));
        deliveryAnd6weekVisit.setStart(cursor.getString(cursor.getColumnIndex(MainDBConstants.START)));
        deliveryAnd6weekVisit.setEnd(cursor.getString(cursor.getColumnIndex(MainDBConstants.END)));
        deliveryAnd6weekVisit.setSimserial(cursor.getString(cursor.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        deliveryAnd6weekVisit.setPhonenumber(cursor.getString(cursor.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        deliveryAnd6weekVisit.setDeviceid(cursor.getString(cursor.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursor.getLong(cursor.getColumnIndex(MainDBConstants.TODAY))>0) deliveryAnd6weekVisit.setToday(new Date(cursor.getLong(cursor.getColumnIndex(MainDBConstants.TODAY))));

        return deliveryAnd6weekVisit;
    }
}
