package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp07InfantAssessmentVisit;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp07DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 2/1/2017.
 * V1.0
 */
public class Zp07InfantAssessmentVisitHelper {

    public static ContentValues crearZp07InfantAssessmentVisit(Zp07InfantAssessmentVisit zp07InfantAssessmentVisit){
        ContentValues cv = new ContentValues();
        cv.put(Zp07DBConstants.recordId, zp07InfantAssessmentVisit.getRecordId());
        cv.put(Zp07DBConstants.redcapEventName, zp07InfantAssessmentVisit.getRedcapEventName());
        if (zp07InfantAssessmentVisit.getInfantVisitDate()!=null) cv.put(Zp07DBConstants.infantVisitDate, zp07InfantAssessmentVisit.getInfantVisitDate().getTime());
        cv.put(Zp07DBConstants.infantStatus, zp07InfantAssessmentVisit.getInfantStatus());
        if (zp07InfantAssessmentVisit.getInfantDeathDt() !=null) cv.put(Zp07DBConstants.infantDeathDt, zp07InfantAssessmentVisit.getInfantDeathDt().getTime());
        cv.put(Zp07DBConstants.infantVisit, zp07InfantAssessmentVisit.getInfantVisit());
        if (zp07InfantAssessmentVisit.getInfantVisitDate2()!=null) cv.put(Zp07DBConstants.infantVisitDate2, zp07InfantAssessmentVisit.getInfantVisitDate2().getTime());
        cv.put(Zp07DBConstants.infantStatus2, zp07InfantAssessmentVisit.getInfantStatus2());
        if (zp07InfantAssessmentVisit.getInfantDeathDt2() !=null) cv.put(Zp07DBConstants.infantDeathDt2, zp07InfantAssessmentVisit.getInfantDeathDt2().getTime());
        cv.put(Zp07DBConstants.infantVisit2, zp07InfantAssessmentVisit.getInfantVisit2());
        if (zp07InfantAssessmentVisit.getInfantVisitDate3()!=null) cv.put(Zp07DBConstants.infantVisitDate3, zp07InfantAssessmentVisit.getInfantVisitDate3().getTime());
        cv.put(Zp07DBConstants.infantStatus3, zp07InfantAssessmentVisit.getInfantStatus3());
        if (zp07InfantAssessmentVisit.getInfantDeathDt3() !=null) cv.put(Zp07DBConstants.infantDeathDt3, zp07InfantAssessmentVisit.getInfantDeathDt3().getTime());
        cv.put(Zp07DBConstants.infantVisit3, zp07InfantAssessmentVisit.getInfantVisit3());
        cv.put(Zp07DBConstants.infantTemp, zp07InfantAssessmentVisit.getInfantTemp());
        cv.put(Zp07DBConstants.infantTmpUnit, zp07InfantAssessmentVisit.getInfantTmpUnit());
        cv.put(Zp07DBConstants.infantWt, zp07InfantAssessmentVisit.getInfantWt());
        cv.put(Zp07DBConstants.infantWtUnit, zp07InfantAssessmentVisit.getInfantWtUnit());
        cv.put(Zp07DBConstants.infantWtPercen, zp07InfantAssessmentVisit.getInfantWtPercen());
        cv.put(Zp07DBConstants.infantWtpercenNa, zp07InfantAssessmentVisit.getInfantWtpercenNa());
        cv.put(Zp07DBConstants.infantLength, zp07InfantAssessmentVisit.getInfantLength());
        cv.put(Zp07DBConstants.infantLengthPercen, zp07InfantAssessmentVisit.getInfantLengthPercen());
        cv.put(Zp07DBConstants.infantLenpercenNa, zp07InfantAssessmentVisit.getInfantLenpercenNa());
        cv.put(Zp07DBConstants.infantHeadcircu, zp07InfantAssessmentVisit.getInfantHeadcircu());
        cv.put(Zp07DBConstants.infantHeapercen, zp07InfantAssessmentVisit.getInfantHeapercen());
        cv.put(Zp07DBConstants.infantHeapercenNa, zp07InfantAssessmentVisit.getInfantHeapercenNa());
        cv.put(Zp07DBConstants.infantHeasize, zp07InfantAssessmentVisit.getInfantHeasize());
        cv.put(Zp07DBConstants.infantApgarNa, zp07InfantAssessmentVisit.getInfantApgarNa());
        cv.put(Zp07DBConstants.infantApgar1min, zp07InfantAssessmentVisit.getInfantApgar1min());
        cv.put(Zp07DBConstants.infantApgar5min, zp07InfantAssessmentVisit.getInfantApgar5min());
        cv.put(Zp07DBConstants.infantSkinEvalu, zp07InfantAssessmentVisit.getInfantSkinEvalu());
        cv.put(Zp07DBConstants.infantRash, zp07InfantAssessmentVisit.getInfantRash());
        cv.put(Zp07DBConstants.infantScarring, zp07InfantAssessmentVisit.getInfantScarring());
        cv.put(Zp07DBConstants.infantOrganEvalu, zp07InfantAssessmentVisit.getInfantOrganEvalu());
        cv.put(Zp07DBConstants.infantAbdominal, zp07InfantAssessmentVisit.getInfantAbdominal());
        cv.put(Zp07DBConstants.infantLiverSpleen, zp07InfantAssessmentVisit.getInfantLiverSpleen());
        cv.put(Zp07DBConstants.infantOphth, zp07InfantAssessmentVisit.getInfantOphth());
        cv.put(Zp07DBConstants.infantOphthType, zp07InfantAssessmentVisit.getInfantOphthType());
        cv.put(Zp07DBConstants.infantOphthAbno, zp07InfantAssessmentVisit.getInfantOphthAbno());
        cv.put(Zp07DBConstants.infantOae, zp07InfantAssessmentVisit.getInfantOae());
        cv.put(Zp07DBConstants.infantHearingTest, zp07InfantAssessmentVisit.getInfantHearingTest());
        cv.put(Zp07DBConstants.infantHearingOverall, zp07InfantAssessmentVisit.getInfantHearingOverall());
        cv.put(Zp07DBConstants.infantRoae, zp07InfantAssessmentVisit.getInfantRoae());
        cv.put(Zp07DBConstants.infantRaabr, zp07InfantAssessmentVisit.getInfantRaabr());
        cv.put(Zp07DBConstants.infantLoae, zp07InfantAssessmentVisit.getInfantLoae());
        cv.put(Zp07DBConstants.infantLaabr, zp07InfantAssessmentVisit.getInfantLaabr());
        cv.put(Zp07DBConstants.infantBreastfeeding, zp07InfantAssessmentVisit.getInfantBreastfeeding());
        cv.put(Zp07DBConstants.infantBreastReason, zp07InfantAssessmentVisit.getInfantBreastReason());
        cv.put(Zp07DBConstants.infantBreastOther, zp07InfantAssessmentVisit.getInfantBreastOther());
        cv.put(Zp07DBConstants.infantNeurodeve, zp07InfantAssessmentVisit.getInfantNeurodeve());
        cv.put(Zp07DBConstants.infantAsymType, zp07InfantAssessmentVisit.getInfantAsymType());
        cv.put(Zp07DBConstants.infantOtherMove, zp07InfantAssessmentVisit.getInfantOtherMove());
        cv.put(Zp07DBConstants.infantExhibitOther, zp07InfantAssessmentVisit.getInfantExhibitOther());
        cv.put(Zp07DBConstants.infantMicroce, zp07InfantAssessmentVisit.getInfantMicroce());
        cv.put(Zp07DBConstants.infantDefinition, zp07InfantAssessmentVisit.getInfantDefinition());
        cv.put(Zp07DBConstants.infantFurtherNeuro, zp07InfantAssessmentVisit.getInfantFurtherNeuro());
        cv.put(Zp07DBConstants.infantEvaluation, zp07InfantAssessmentVisit.getInfantEvaluation());
        cv.put(Zp07DBConstants.infantNeuroAsq, zp07InfantAssessmentVisit.getInfantNeuroAsq());
        cv.put(Zp07DBConstants.infantAsqCommuni, zp07InfantAssessmentVisit.getInfantAsqCommuni());
        cv.put(Zp07DBConstants.infantAsqGross, zp07InfantAssessmentVisit.getInfantAsqGross());
        cv.put(Zp07DBConstants.infantAsqFine, zp07InfantAssessmentVisit.getInfantAsqFine());
        cv.put(Zp07DBConstants.infantAsqProblem, zp07InfantAssessmentVisit.getInfantAsqProblem());
        cv.put(Zp07DBConstants.infantAsqPersonal, zp07InfantAssessmentVisit.getInfantAsqPersonal());
        cv.put(Zp07DBConstants.infantNeuroBisd, zp07InfantAssessmentVisit.getInfantNeuroBisd());
        cv.put(Zp07DBConstants.infantCgScore, zp07InfantAssessmentVisit.getInfantCgScore());
        cv.put(Zp07DBConstants.infantCgRisk, zp07InfantAssessmentVisit.getInfantCgRisk());
        cv.put(Zp07DBConstants.infantRpScore, zp07InfantAssessmentVisit.getInfantRpScore());
        cv.put(Zp07DBConstants.infantRpRisk, zp07InfantAssessmentVisit.getInfantRpRisk());
        cv.put(Zp07DBConstants.infantEpRisk, zp07InfantAssessmentVisit.getInfantEpRisk());
        cv.put(Zp07DBConstants.infantEpScore, zp07InfantAssessmentVisit.getInfantEpScore());
        cv.put(Zp07DBConstants.infantEpRisk, zp07InfantAssessmentVisit.getInfantEpRisk());
        cv.put(Zp07DBConstants.infantFmScore, zp07InfantAssessmentVisit.getInfantFmScore());
        cv.put(Zp07DBConstants.infantFmRisk, zp07InfantAssessmentVisit.getInfantFmRisk());
        cv.put(Zp07DBConstants.infantGmScore, zp07InfantAssessmentVisit.getInfantGmScore());
        cv.put(Zp07DBConstants.infantGmRisk, zp07InfantAssessmentVisit.getInfantGmRisk());
        cv.put(Zp07DBConstants.infantNeuroOther, zp07InfantAssessmentVisit.getInfantNeuroOther());
        cv.put(Zp07DBConstants.infantOtherName, zp07InfantAssessmentVisit.getInfantOtherName());
        cv.put(Zp07DBConstants.infantOtherScore, zp07InfantAssessmentVisit.getInfantOtherScore());
        cv.put(Zp07DBConstants.infantResultScreening, zp07InfantAssessmentVisit.getInfantResultScreening());
        cv.put(Zp07DBConstants.infantReferTesting, zp07InfantAssessmentVisit.getInfantReferTesting());
        cv.put(Zp07DBConstants.infantFeverSymptom, zp07InfantAssessmentVisit.getInfantFeverSymptom());
        cv.put(Zp07DBConstants.infantRashSymptom, zp07InfantAssessmentVisit.getInfantRashSymptom());
        cv.put(Zp07DBConstants.infantItch, zp07InfantAssessmentVisit.getInfantItch());
        cv.put(Zp07DBConstants.infantRashFirst, zp07InfantAssessmentVisit.getInfantRashFirst());
        cv.put(Zp07DBConstants.infantRashDy, zp07InfantAssessmentVisit.getInfantRashDy());
        cv.put(Zp07DBConstants.infantRashMn, zp07InfantAssessmentVisit.getInfantRashMn());
        cv.put(Zp07DBConstants.infantRashYr, zp07InfantAssessmentVisit.getInfantRashYr());
        cv.put(Zp07DBConstants.infantRashDur, zp07InfantAssessmentVisit.getInfantRashDur());
        cv.put(Zp07DBConstants.infantRashSpread, zp07InfantAssessmentVisit.getInfantRashSpread());
        cv.put(Zp07DBConstants.infantSpreadPart, zp07InfantAssessmentVisit.getInfantSpreadPart());
        cv.put(Zp07DBConstants.infantFeverExperience, zp07InfantAssessmentVisit.getInfantFeverExperience());
        cv.put(Zp07DBConstants.infantTempMeasure, zp07InfantAssessmentVisit.getInfantTempMeasure());
        cv.put(Zp07DBConstants.infantHighTemp, zp07InfantAssessmentVisit.getInfantHighTemp());
        cv.put(Zp07DBConstants.infantHightemUnit, zp07InfantAssessmentVisit.getInfantHightemUnit());
        cv.put(Zp07DBConstants.infantTempunknown, zp07InfantAssessmentVisit.getInfantTempunknown());
        cv.put(Zp07DBConstants.infantFeverDy, zp07InfantAssessmentVisit.getInfantFeverDy());
        cv.put(Zp07DBConstants.infantFeverMn, zp07InfantAssessmentVisit.getInfantFeverMn());
        cv.put(Zp07DBConstants.infantFeverYr, zp07InfantAssessmentVisit.getInfantFeverYr());
        cv.put(Zp07DBConstants.infantFeverDur, zp07InfantAssessmentVisit.getInfantFeverDur());
        cv.put(Zp07DBConstants.infantRedeyes, zp07InfantAssessmentVisit.getInfantRedeyes());
        cv.put(Zp07DBConstants.infantRedeyesDy, zp07InfantAssessmentVisit.getInfantRedeyesDy());
        cv.put(Zp07DBConstants.infantRedeyesMn, zp07InfantAssessmentVisit.getInfantRedeyesMn());
        cv.put(Zp07DBConstants.infantRedeyesYr, zp07InfantAssessmentVisit.getInfantRedeyesYr());
        cv.put(Zp07DBConstants.infantRedeyesDur, zp07InfantAssessmentVisit.getInfantRedeyesDur());
        cv.put(Zp07DBConstants.infantJoint, zp07InfantAssessmentVisit.getInfantJoint());
        cv.put(Zp07DBConstants.infantJointDy, zp07InfantAssessmentVisit.getInfantJointDy());
        cv.put(Zp07DBConstants.infantJointMn, zp07InfantAssessmentVisit.getInfantJointMn());
        cv.put(Zp07DBConstants.infantJointYr, zp07InfantAssessmentVisit.getInfantJointYr());
        cv.put(Zp07DBConstants.infantJointDur, zp07InfantAssessmentVisit.getInfantJointDur());
        cv.put(Zp07DBConstants.infantHeadache, zp07InfantAssessmentVisit.getInfantHeadache());
        cv.put(Zp07DBConstants.infantHeadacheDy, zp07InfantAssessmentVisit.getInfantHeadacheDy());
        cv.put(Zp07DBConstants.infantHeadacheMn, zp07InfantAssessmentVisit.getInfantHeadacheMn());
        cv.put(Zp07DBConstants.infantHeadacheYr, zp07InfantAssessmentVisit.getInfantHeadacheYr());
        cv.put(Zp07DBConstants.infantHeadaDur, zp07InfantAssessmentVisit.getInfantHeadaDur());
        cv.put(Zp07DBConstants.infantSymptomOther, zp07InfantAssessmentVisit.getInfantSymptomOther());
        cv.put(Zp07DBConstants.infantSpecifySymptom, zp07InfantAssessmentVisit.getInfantSpecifySymptom());
        cv.put(Zp07DBConstants.infantOtherSymptom, zp07InfantAssessmentVisit.getInfantOtherSymptom());
        cv.put(Zp07DBConstants.infantMedicare, zp07InfantAssessmentVisit.getInfantMedicare());
        cv.put(Zp07DBConstants.infantCareDy, zp07InfantAssessmentVisit.getInfantCareDy());
        cv.put(Zp07DBConstants.infantCareMn, zp07InfantAssessmentVisit.getInfantCareMn());
        cv.put(Zp07DBConstants.infantCareYr, zp07InfantAssessmentVisit.getInfantCareYr());
        cv.put(Zp07DBConstants.infantCareFacility, zp07InfantAssessmentVisit.getInfantCareFacility());
        cv.put(Zp07DBConstants.infantHospitalized, zp07InfantAssessmentVisit.getInfantHospitalized());
        cv.put(Zp07DBConstants.infantHospital, zp07InfantAssessmentVisit.getInfantHospital());
        cv.put(Zp07DBConstants.infantDiagRubella, zp07InfantAssessmentVisit.getInfantDiagRubella());
        cv.put(Zp07DBConstants.infantDiagDengue, zp07InfantAssessmentVisit.getInfantDiagDengue());
        cv.put(Zp07DBConstants.infantDiagChikung, zp07InfantAssessmentVisit.getInfantDiagChikung());
        cv.put(Zp07DBConstants.infantDiagZika, zp07InfantAssessmentVisit.getInfantDiagZika());
        cv.put(Zp07DBConstants.infantDiagCytome, zp07InfantAssessmentVisit.getInfantDiagCytome());
        cv.put(Zp07DBConstants.infantMedicine, zp07InfantAssessmentVisit.getInfantMedicine());
        cv.put(Zp07DBConstants.infantMedName, zp07InfantAssessmentVisit.getInfantMedName());
        cv.put(Zp07DBConstants.infantSpDiary, zp07InfantAssessmentVisit.getInfantSpDiary());
        cv.put(Zp07DBConstants.infantPreResults, zp07InfantAssessmentVisit.getInfantPreResults());
        cv.put(Zp07DBConstants.infantReferr, zp07InfantAssessmentVisit.getInfantReferr());
        cv.put(Zp07DBConstants.infantOtherLab, zp07InfantAssessmentVisit.getInfantOtherLab());
        cv.put(Zp07DBConstants.infantCommentsYn, zp07InfantAssessmentVisit.getInfantCommentsYn());
        cv.put(Zp07DBConstants.infantComments2, zp07InfantAssessmentVisit.getInfantComments2());
        cv.put(Zp07DBConstants.infantCommentsYn2, zp07InfantAssessmentVisit.getInfantCommentsYn2());
        cv.put(Zp07DBConstants.infantComments2_2, zp07InfantAssessmentVisit.getInfantComments2_2());
        cv.put(Zp07DBConstants.infantCommentsYn3, zp07InfantAssessmentVisit.getInfantCommentsYn3());
        cv.put(Zp07DBConstants.infantComments2_3, zp07InfantAssessmentVisit.getInfantComments2_3());
        cv.put(Zp07DBConstants.infantIdCompleting, zp07InfantAssessmentVisit.getInfantIdCompleting());
        if (zp07InfantAssessmentVisit.getInfantDtComp()!=null) cv.put(Zp07DBConstants.infantDtComp, zp07InfantAssessmentVisit.getInfantDtComp().getTime());
        cv.put(Zp07DBConstants.infantIdReviewer, zp07InfantAssessmentVisit.getInfantIdReviewer());
        if (zp07InfantAssessmentVisit.getInfantDtReview()!=null) cv.put(Zp07DBConstants.infantDtReview, zp07InfantAssessmentVisit.getInfantDtReview().getTime());
        cv.put(Zp07DBConstants.infantIdDataEntry, zp07InfantAssessmentVisit.getInfantIdDataEntry());
        if (zp07InfantAssessmentVisit.getInfantDtEnter()!=null) cv.put(Zp07DBConstants.infantDtEnter, zp07InfantAssessmentVisit.getInfantDtEnter().getTime());

        cv.put(Zp07DBConstants.infantIdCompleting2, zp07InfantAssessmentVisit.getInfantIdCompleting2());
        if (zp07InfantAssessmentVisit.getInfantDtComp2()!=null) cv.put(Zp07DBConstants.infantDtComp2, zp07InfantAssessmentVisit.getInfantDtComp2().getTime());
        cv.put(Zp07DBConstants.infantIdReviewer2, zp07InfantAssessmentVisit.getInfantIdReviewer2());
        if (zp07InfantAssessmentVisit.getInfantDtReview2()!=null) cv.put(Zp07DBConstants.infantDtReview2, zp07InfantAssessmentVisit.getInfantDtReview2().getTime());
        cv.put(Zp07DBConstants.infantIdDataEntry2, zp07InfantAssessmentVisit.getInfantIdDataEntry2());
        if (zp07InfantAssessmentVisit.getInfantDtEnter2()!=null) cv.put(Zp07DBConstants.infantDtEnter2, zp07InfantAssessmentVisit.getInfantDtEnter2().getTime());

        cv.put(Zp07DBConstants.infantIdCompleting3, zp07InfantAssessmentVisit.getInfantIdCompleting3());
        if (zp07InfantAssessmentVisit.getInfantDtComp3()!=null) cv.put(Zp07DBConstants.infantDtComp3, zp07InfantAssessmentVisit.getInfantDtComp3().getTime());
        cv.put(Zp07DBConstants.infantIdReviewer3, zp07InfantAssessmentVisit.getInfantIdReviewer3());
        if (zp07InfantAssessmentVisit.getInfantDtReview3()!=null) cv.put(Zp07DBConstants.infantDtReview3, zp07InfantAssessmentVisit.getInfantDtReview3().getTime());
        cv.put(Zp07DBConstants.infantIdDataEntry3, zp07InfantAssessmentVisit.getInfantIdDataEntry3());
        if (zp07InfantAssessmentVisit.getInfantDtEnter3()!=null) cv.put(Zp07DBConstants.infantDtEnter3, zp07InfantAssessmentVisit.getInfantDtEnter3().getTime());

        if (zp07InfantAssessmentVisit.getPart1()!=null) cv.put(Zp07DBConstants.part1, zp07InfantAssessmentVisit.getPart1());
        if (zp07InfantAssessmentVisit.getPart2()!=null) cv.put(Zp07DBConstants.part2, zp07InfantAssessmentVisit.getPart2());
        if (zp07InfantAssessmentVisit.getPart3()!=null) cv.put(Zp07DBConstants.part3, zp07InfantAssessmentVisit.getPart3());
        
        if (zp07InfantAssessmentVisit.getInfantDob() != null) cv.put(Zp07DBConstants.infantDob, zp07InfantAssessmentVisit.getInfantDob().getTime());
        cv.put(Zp07DBConstants.infantWeeks, zp07InfantAssessmentVisit.getInfantWeeks());
        cv.put(Zp07DBConstants.infantDays, zp07InfantAssessmentVisit.getInfantDays());

        if (zp07InfantAssessmentVisit.getInfantHearDt()!=null) cv.put(Zp07DBConstants.infantHearDt, zp07InfantAssessmentVisit.getInfantHearDt().getTime());
        if (zp07InfantAssessmentVisit.getInfantNeuroDt()!=null) cv.put(Zp07DBConstants.infantNeuroDt, zp07InfantAssessmentVisit.getInfantNeuroDt().getTime());
        cv.put(Zp07DBConstants.infantExhibited1, zp07InfantAssessmentVisit.getInfantExhibited1());
        cv.put(Zp07DBConstants.infantExhibited2, zp07InfantAssessmentVisit.getInfantExhibited2());
        cv.put(Zp07DBConstants.infantExhibited3, zp07InfantAssessmentVisit.getInfantExhibited3());
        cv.put(Zp07DBConstants.infantExhibited4, zp07InfantAssessmentVisit.getInfantExhibited4());
        cv.put(Zp07DBConstants.infantExhibited5, zp07InfantAssessmentVisit.getInfantExhibited5());
        cv.put(Zp07DBConstants.infantExhibited6, zp07InfantAssessmentVisit.getInfantExhibited6());
        cv.put(Zp07DBConstants.infantExhibited7, zp07InfantAssessmentVisit.getInfantExhibited7());
        cv.put(Zp07DBConstants.infantExhibited8, zp07InfantAssessmentVisit.getInfantExhibited8());
        cv.put(Zp07DBConstants.infantExhibited9, zp07InfantAssessmentVisit.getInfantExhibited9());
        cv.put(Zp07DBConstants.infantExhibited10, zp07InfantAssessmentVisit.getInfantExhibited10());
        cv.put(Zp07DBConstants.infantExhibited11, zp07InfantAssessmentVisit.getInfantExhibited11());
        cv.put(Zp07DBConstants.infantExhibited12, zp07InfantAssessmentVisit.getInfantExhibited12());
        cv.put(Zp07DBConstants.infantExhibited13, zp07InfantAssessmentVisit.getInfantExhibited13());
        cv.put(Zp07DBConstants.infantExhibited14, zp07InfantAssessmentVisit.getInfantExhibited14());
        if (zp07InfantAssessmentVisit.getInfantNedeveDt()!=null) cv.put(Zp07DBConstants.infantNedeveDt, zp07InfantAssessmentVisit.getInfantNedeveDt().getTime());
        if (zp07InfantAssessmentVisit.getInfantOpDt()!=null) cv.put(Zp07DBConstants.infantOpDt, zp07InfantAssessmentVisit.getInfantOpDt().getTime());


        if (zp07InfantAssessmentVisit.getRecordDate() != null) cv.put(MainDBConstants.recordDate, zp07InfantAssessmentVisit.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, zp07InfantAssessmentVisit.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(zp07InfantAssessmentVisit.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, zp07InfantAssessmentVisit.getIdInstancia());
        cv.put(Zp07DBConstants.idInstancia2, zp07InfantAssessmentVisit.getIdInstancia2());
        cv.put(Zp07DBConstants.idInstancia3, zp07InfantAssessmentVisit.getIdInstancia3());
        cv.put(MainDBConstants.FILE_PATH, zp07InfantAssessmentVisit.getInstancePath());
        cv.put(MainDBConstants.STATUS, zp07InfantAssessmentVisit.getEstado());
        cv.put(MainDBConstants.START, zp07InfantAssessmentVisit.getStart());
        cv.put(MainDBConstants.END, zp07InfantAssessmentVisit.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, zp07InfantAssessmentVisit.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, zp07InfantAssessmentVisit.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, zp07InfantAssessmentVisit.getPhonenumber());
        if (zp07InfantAssessmentVisit.getToday() != null) cv.put(MainDBConstants.TODAY, zp07InfantAssessmentVisit.getToday().getTime());
        return cv;
    }

    public static Zp07InfantAssessmentVisit crearZp07InfantAssessmentVisit(Cursor cursorIA){
        Zp07InfantAssessmentVisit infantAssessmentVisit = new Zp07InfantAssessmentVisit();
        infantAssessmentVisit.setRecordId(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.recordId)));
        infantAssessmentVisit.setRedcapEventName(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.redcapEventName)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate))>0) infantAssessmentVisit.setInfantVisitDate(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate))));
        infantAssessmentVisit.setInfantStatus(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantStatus)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt))>0) infantAssessmentVisit.setInfantDeathDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt))));
        infantAssessmentVisit.setInfantVisit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantVisit)));

        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate2))>0) infantAssessmentVisit.setInfantVisitDate2(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate2))));
        infantAssessmentVisit.setInfantStatus2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantStatus2)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt2))>0) infantAssessmentVisit.setInfantDeathDt2(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt2))));
        infantAssessmentVisit.setInfantVisit2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantVisit2)));

        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate3))>0) infantAssessmentVisit.setInfantVisitDate3(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate3))));
        infantAssessmentVisit.setInfantStatus3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantStatus3)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt3))>0) infantAssessmentVisit.setInfantDeathDt3(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDeathDt3))));
        infantAssessmentVisit.setInfantVisit3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantVisit3)));


        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantTemp))>0) infantAssessmentVisit.setInfantTemp(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantTemp)));
        infantAssessmentVisit.setInfantTmpUnit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantTmpUnit)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWt))>0) infantAssessmentVisit.setInfantWt(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWt)));
        infantAssessmentVisit.setInfantWtUnit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWtUnit)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWtPercen))>0) infantAssessmentVisit.setInfantWtPercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWtPercen)));
        infantAssessmentVisit.setInfantWtpercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWtpercenNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLength))>0) infantAssessmentVisit.setInfantLength(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLength)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLengthPercen))>0) infantAssessmentVisit.setInfantLengthPercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLengthPercen)));
        infantAssessmentVisit.setInfantLenpercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLenpercenNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadcircu))>0) infantAssessmentVisit.setInfantHeadcircu(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadcircu)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercen))>0) infantAssessmentVisit.setInfantHeapercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercen)));
        infantAssessmentVisit.setInfantHeapercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercenNa)));
        infantAssessmentVisit.setInfantHeasize(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeasize)));
        // infantAssessmentVisit.setInfantReferr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferr)));
        infantAssessmentVisit.setInfantApgarNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantApgarNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar1min))>0) infantAssessmentVisit.setInfantApgar1min(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar1min)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar5min))>0) infantAssessmentVisit.setInfantApgar5min(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar5min)));
        infantAssessmentVisit.setInfantSkinEvalu(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSkinEvalu)));
        infantAssessmentVisit.setInfantRash(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRash)));
        infantAssessmentVisit.setInfantScarring(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantScarring)));
        infantAssessmentVisit.setInfantOrganEvalu(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOrganEvalu)));
        infantAssessmentVisit.setInfantAbdominal(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantAbdominal)));
        infantAssessmentVisit.setInfantLiverSpleen(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLiverSpleen)));
        infantAssessmentVisit.setInfantOphth(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOphth)));
        infantAssessmentVisit.setInfantOphthType(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOphthType)));
        infantAssessmentVisit.setInfantOphthAbno(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOphthAbno)));
        infantAssessmentVisit.setInfantOae(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOae)));
        infantAssessmentVisit.setInfantHearingTest(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHearingTest)));
        infantAssessmentVisit.setInfantHearingOverall(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHearingOverall)));
        infantAssessmentVisit.setInfantRoae(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRoae)));
        infantAssessmentVisit.setInfantRaabr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRaabr)));
        infantAssessmentVisit.setInfantLoae(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLoae)));
        infantAssessmentVisit.setInfantLaabr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLaabr)));
        infantAssessmentVisit.setInfantBreastfeeding(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastfeeding)));
        infantAssessmentVisit.setInfantBreastReason(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastReason)));
        infantAssessmentVisit.setInfantBreastOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastOther)));
        infantAssessmentVisit.setInfantNeurodeve(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeurodeve)));
        infantAssessmentVisit.setInfantAsymType(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantAsymType)));
        infantAssessmentVisit.setInfantOtherMove(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherMove)));
        infantAssessmentVisit.setInfantExhibitOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibitOther)));
        infantAssessmentVisit.setInfantMicroce(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMicroce)));
        infantAssessmentVisit.setInfantDefinition(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDefinition)));
        infantAssessmentVisit.setInfantFurtherNeuro(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFurtherNeuro)));
        infantAssessmentVisit.setInfantEvaluation(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantEvaluation)));
        infantAssessmentVisit.setInfantNeuroAsq(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeuroAsq)));
        infantAssessmentVisit.setInfantAsqCommuni(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantAsqCommuni)));
        infantAssessmentVisit.setInfantAsqGross(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantAsqGross)));
        infantAssessmentVisit.setInfantAsqFine(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantAsqFine)));
        infantAssessmentVisit.setInfantAsqProblem(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantAsqProblem)));
        infantAssessmentVisit.setInfantAsqPersonal(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantAsqPersonal)));
        infantAssessmentVisit.setInfantNeuroBisd(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeuroBisd)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantCgScore))>0) infantAssessmentVisit.setInfantCgScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantCgScore)));
        infantAssessmentVisit.setInfantCgRisk(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCgRisk)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantRpScore))>0) infantAssessmentVisit.setInfantRpScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantRpScore)));
        infantAssessmentVisit.setInfantRpRisk(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRpRisk)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantEpScore))>0) infantAssessmentVisit.setInfantEpScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantEpScore)));
        infantAssessmentVisit.setInfantEpRisk(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantEpRisk)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantFmScore))>0) infantAssessmentVisit.setInfantFmScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantFmScore)));
        infantAssessmentVisit.setInfantFmRisk(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFmRisk)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantGmScore))>0) infantAssessmentVisit.setInfantGmScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantGmScore)));
        infantAssessmentVisit.setInfantGmRisk(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantGmRisk)));
        infantAssessmentVisit.setInfantNeuroOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeuroOther)));
        infantAssessmentVisit.setInfantOtherName(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherName)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherScore))>0) infantAssessmentVisit.setInfantOtherScore(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherScore)));
        infantAssessmentVisit.setInfantResultScreening(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultScreening)));
        infantAssessmentVisit.setInfantReferTesting(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferTesting)));
        infantAssessmentVisit.setInfantFeverSymptom(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverSymptom)));
        infantAssessmentVisit.setInfantRashSymptom(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashSymptom)));
        infantAssessmentVisit.setInfantItch(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantItch)));
        infantAssessmentVisit.setInfantRashFirst(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashFirst)));
        infantAssessmentVisit.setInfantRashDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashDy)));
        infantAssessmentVisit.setInfantRashMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashMn)));
        infantAssessmentVisit.setInfantRashYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashYr)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantRashDur))>0) infantAssessmentVisit.setInfantRashDur(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantRashDur)));
        infantAssessmentVisit.setInfantRashSpread(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRashSpread)));
        infantAssessmentVisit.setInfantSpreadPart(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSpreadPart)));
        infantAssessmentVisit.setInfantFeverExperience(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverExperience)));
        infantAssessmentVisit.setInfantTempMeasure(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantTempMeasure)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHighTemp))>0) infantAssessmentVisit.setInfantHighTemp(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHighTemp)));
        infantAssessmentVisit.setInfantHightemUnit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHightemUnit)));
        infantAssessmentVisit.setInfantTempunknown(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantTempunknown)));
        infantAssessmentVisit.setInfantFeverDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverDy)));
        infantAssessmentVisit.setInfantFeverMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverMn)));
        infantAssessmentVisit.setInfantFeverYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverYr)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverDur))>0) infantAssessmentVisit.setInfantFeverDur(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantFeverDur)));
        infantAssessmentVisit.setInfantRedeyes(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyes)));
        infantAssessmentVisit.setInfantRedeyesDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyesDy)));
        infantAssessmentVisit.setInfantRedeyesMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyesMn)));
        infantAssessmentVisit.setInfantRedeyesYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyesYr)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyesDur))>0) infantAssessmentVisit.setInfantRedeyesDur(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantRedeyesDur)));
        infantAssessmentVisit.setInfantJoint(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantJoint)));
        infantAssessmentVisit.setInfantJointDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantJointDy)));
        infantAssessmentVisit.setInfantJointMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantJointMn)));
        infantAssessmentVisit.setInfantJointYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantJointYr)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantJointDur))>0) infantAssessmentVisit.setInfantJointDur(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantJointDur)));
        infantAssessmentVisit.setInfantHeadache(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadache)));
        infantAssessmentVisit.setInfantHeadacheDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadacheDy)));
        infantAssessmentVisit.setInfantHeadacheMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadacheMn)));
        infantAssessmentVisit.setInfantHeadacheYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadacheYr)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadaDur))>0) infantAssessmentVisit.setInfantHeadaDur(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadaDur)));
        infantAssessmentVisit.setInfantSymptomOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSymptomOther)));
        infantAssessmentVisit.setInfantSpecifySymptom(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSpecifySymptom)));
        infantAssessmentVisit.setInfantOtherSymptom(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherSymptom)));
        infantAssessmentVisit.setInfantMedicare(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMedicare)));
        infantAssessmentVisit.setInfantCareDy(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCareDy)));
        infantAssessmentVisit.setInfantCareMn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCareMn)));
        infantAssessmentVisit.setInfantCareYr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCareYr)));
        infantAssessmentVisit.setInfantCareFacility(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCareFacility)));
        infantAssessmentVisit.setInfantHospitalized(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHospitalized)));
        infantAssessmentVisit.setInfantHospital(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHospital)));
        infantAssessmentVisit.setInfantDiagRubella(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDiagRubella)));
        infantAssessmentVisit.setInfantDiagDengue(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDiagDengue)));
        infantAssessmentVisit.setInfantDiagChikung(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDiagChikung)));
        infantAssessmentVisit.setInfantDiagZika(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDiagZika)));
        infantAssessmentVisit.setInfantDiagCytome(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantDiagCytome)));
        infantAssessmentVisit.setInfantMedicine(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMedicine)));
        infantAssessmentVisit.setInfantMedName(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMedName)));
        infantAssessmentVisit.setInfantSpDiary(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSpDiary)));
        infantAssessmentVisit.setInfantPreResults(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantPreResults)));
        infantAssessmentVisit.setInfantReferr(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferr)));
        infantAssessmentVisit.setInfantOtherLab(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherLab)));
        infantAssessmentVisit.setInfantCommentsYn(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCommentsYn)));
        infantAssessmentVisit.setInfantComments2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantComments2)));
        infantAssessmentVisit.setInfantCommentsYn2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCommentsYn2)));
        infantAssessmentVisit.setInfantComments2_2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantComments2_2)));
        infantAssessmentVisit.setInfantCommentsYn3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCommentsYn3)));
        infantAssessmentVisit.setInfantComments2_3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantComments2_3)));

        infantAssessmentVisit.setInfantIdCompleting(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdCompleting)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp))>0) infantAssessmentVisit.setInfantDtComp(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp))));
        infantAssessmentVisit.setInfantIdReviewer(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdReviewer)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview))>0) infantAssessmentVisit.setInfantDtReview(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview))));
        infantAssessmentVisit.setInfantIdDataEntry(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdDataEntry)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter))>0) infantAssessmentVisit.setInfantDtEnter(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter))));

        infantAssessmentVisit.setInfantIdCompleting2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdCompleting2)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp2))>0) infantAssessmentVisit.setInfantDtComp2(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp2))));
        infantAssessmentVisit.setInfantIdReviewer2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdReviewer2)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview2))>0) infantAssessmentVisit.setInfantDtReview2(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview2))));
        infantAssessmentVisit.setInfantIdDataEntry2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdDataEntry2)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter2))>0) infantAssessmentVisit.setInfantDtEnter2(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter2))));

        infantAssessmentVisit.setInfantIdCompleting3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdCompleting3)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp3))>0) infantAssessmentVisit.setInfantDtComp3(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtComp3))));
        infantAssessmentVisit.setInfantIdReviewer3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdReviewer3)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview3))>0) infantAssessmentVisit.setInfantDtReview3(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtReview3))));
        infantAssessmentVisit.setInfantIdDataEntry3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdDataEntry3)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter3))>0) infantAssessmentVisit.setInfantDtEnter3(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDtEnter3))));

        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part1))>0) infantAssessmentVisit.setPart1(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part1)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part2))>0) infantAssessmentVisit.setPart2(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part2)));
        if (cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part3))>0) infantAssessmentVisit.setPart3(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.part3)));
        
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDob))>0) infantAssessmentVisit.setInfantDob(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDob))));
        infantAssessmentVisit.setInfantWeeks(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantWeeks)));
        infantAssessmentVisit.setInfantDays(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.infantDays)));

        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantHearDt))>0) infantAssessmentVisit.setInfantHearDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantHearDt))));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantNeuroDt))>0) infantAssessmentVisit.setInfantNeuroDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantNeuroDt))));
        infantAssessmentVisit.setInfantExhibited1(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited1)));
        infantAssessmentVisit.setInfantExhibited2(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited2)));
        infantAssessmentVisit.setInfantExhibited3(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited3)));
        infantAssessmentVisit.setInfantExhibited4(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited4)));
        infantAssessmentVisit.setInfantExhibited5(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited5)));
        infantAssessmentVisit.setInfantExhibited6(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited6)));
        infantAssessmentVisit.setInfantExhibited7(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited7)));
        infantAssessmentVisit.setInfantExhibited8(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited8)));
        infantAssessmentVisit.setInfantExhibited9(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited9)));
        infantAssessmentVisit.setInfantExhibited10(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited10)));
        infantAssessmentVisit.setInfantExhibited11(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited11)));
        infantAssessmentVisit.setInfantExhibited12(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited12)));
        infantAssessmentVisit.setInfantExhibited13(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited13)));
        infantAssessmentVisit.setInfantExhibited14(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited14)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantNedeveDt))>0) infantAssessmentVisit.setInfantNedeveDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantNedeveDt))));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantOpDt))>0) infantAssessmentVisit.setInfantOpDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantOpDt))));
        if(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.recordDate))>0) infantAssessmentVisit.setRecordDate(new Date(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.recordDate))));

        infantAssessmentVisit.setRecordUser(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.recordUser)));
        infantAssessmentVisit.setPasive(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        infantAssessmentVisit.setIdInstancia(cursorIA.getInt(cursorIA.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        infantAssessmentVisit.setIdInstancia2(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.idInstancia2)));
        infantAssessmentVisit.setIdInstancia3(cursorIA.getInt(cursorIA.getColumnIndex(Zp07DBConstants.idInstancia3)));
        infantAssessmentVisit.setInstancePath(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.FILE_PATH)));
        infantAssessmentVisit.setEstado(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.STATUS)));
        infantAssessmentVisit.setStart(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.START)));
        infantAssessmentVisit.setEnd(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.END)));
        infantAssessmentVisit.setSimserial(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        infantAssessmentVisit.setPhonenumber(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        infantAssessmentVisit.setDeviceid(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.TODAY))>0) infantAssessmentVisit.setToday(new Date(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.TODAY))));

        return infantAssessmentVisit;
    }

}
