package ni.org.ics.zip.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zip.appmovil.domain.Zp07InfantAssessmentVisit;
import ni.org.ics.zip.appmovil.utils.MainDBConstants;
import ni.org.ics.zip.appmovil.utils.Zp07DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 2/1/2017.
 * V1.0
 */
public class Zp07InfantAssessmentVisitHelper {

    public static ContentValues createZp07InfantAssessmentVisit(Zp07InfantAssessmentVisit zp07InfantAssessmentVisit){
        ContentValues cv = new ContentValues();
        cv.put(Zp07DBConstants.recordId, zp07InfantAssessmentVisit.getRecordId());
        cv.put(Zp07DBConstants.redcapEventName, zp07InfantAssessmentVisit.getRedcapEventName());
        if (zp07InfantAssessmentVisit.getInfantVisitDate()!=null) cv.put(Zp07DBConstants.infantVisitDate, zp07InfantAssessmentVisit.getInfantVisitDate().getTime());
        cv.put(Zp07DBConstants.infantStatus, zp07InfantAssessmentVisit.getInfantStatus());
        cv.put(Zp07DBConstants.infantVisit, zp07InfantAssessmentVisit.getInfantVisit());
        cv.put(Zp07DBConstants.infantTemp, zp07InfantAssessmentVisit.getInfantTemp());
        cv.put(Zp07DBConstants.infantTmpUnit, zp07InfantAssessmentVisit.getInfantTmpUnit());
        cv.put(Zp07DBConstants.infantWt, zp07InfantAssessmentVisit.getInfantWt());
        cv.put(Zp07DBConstants.infantWtUnit, zp07InfantAssessmentVisit.getInfantWtUnit());
        cv.put(Zp07DBConstants.infantWtPercen, zp07InfantAssessmentVisit.getInfantWtPercen());
        cv.put(Zp07DBConstants.infantWtpercenNa, zp07InfantAssessmentVisit.getInfantWtpercenNa());
        cv.put(Zp07DBConstants.infantLength, zp07InfantAssessmentVisit.getInfantLength());
        cv.put(Zp07DBConstants.infantLengthPercen, zp07InfantAssessmentVisit.getInfantLengthPercen());
        cv.put(Zp07DBConstants.infantLenpercenNa, zp07InfantAssessmentVisit.getInfantLenpercenNa());
        cv.put(Zp07DBConstants.infantHeadcircu, zp07InfantAssessmentVisit.getInfantHeadcircu());
        cv.put(Zp07DBConstants.infantHeapercen, zp07InfantAssessmentVisit.getInfantHeapercen());
        cv.put(Zp07DBConstants.infantHeapercenNa, zp07InfantAssessmentVisit.getInfantHeapercenNa());
        cv.put(Zp07DBConstants.infantReferralNeuro, zp07InfantAssessmentVisit.getInfantReferralNeuro());
        cv.put(Zp07DBConstants.infantApgarNa, zp07InfantAssessmentVisit.getInfantApgarNa());
        cv.put(Zp07DBConstants.infantApgar1min, zp07InfantAssessmentVisit.getInfantApgar1min());
        cv.put(Zp07DBConstants.infantApgar5min, zp07InfantAssessmentVisit.getInfantApgar5min());
        cv.put(Zp07DBConstants.infantSkinEvalu, zp07InfantAssessmentVisit.getInfantSkinEvalu());
        cv.put(Zp07DBConstants.infantRash, zp07InfantAssessmentVisit.getInfantRash());
        cv.put(Zp07DBConstants.infantScarring, zp07InfantAssessmentVisit.getInfantScarring());
        cv.put(Zp07DBConstants.infantOrganEvalu, zp07InfantAssessmentVisit.getInfantOrganEvalu());
        cv.put(Zp07DBConstants.infantAbdominal, zp07InfantAssessmentVisit.getInfantAbdominal());
        cv.put(Zp07DBConstants.infantLiverSpleen, zp07InfantAssessmentVisit.getInfantLiverSpleen());
        cv.put(Zp07DBConstants.infantOphth, zp07InfantAssessmentVisit.getInfantOphth());
        cv.put(Zp07DBConstants.infantOphthAbno, zp07InfantAssessmentVisit.getInfantOphthAbno());
        cv.put(Zp07DBConstants.infantWhichEye, zp07InfantAssessmentVisit.getInfantWhichEye());
        cv.put(Zp07DBConstants.infantEyeCalci, zp07InfantAssessmentVisit.getInfantEyeCalci());
        cv.put(Zp07DBConstants.infantChoriore, zp07InfantAssessmentVisit.getInfantChoriore());
        cv.put(Zp07DBConstants.infantEyeOther, zp07InfantAssessmentVisit.getInfantEyeOther());
        cv.put(Zp07DBConstants.infantOtherIssue, zp07InfantAssessmentVisit.getInfantOtherIssue());
        cv.put(Zp07DBConstants.infantEyeOtherSpecify, zp07InfantAssessmentVisit.getInfantEyeOtherSpecify());
        cv.put(Zp07DBConstants.infantReferralOphth, zp07InfantAssessmentVisit.getInfantReferralOphth());
        cv.put(Zp07DBConstants.infantOae, zp07InfantAssessmentVisit.getInfantOae());
        cv.put(Zp07DBConstants.infantOaeAbnormal, zp07InfantAssessmentVisit.getInfantOaeAbnormal());
        cv.put(Zp07DBConstants.infantWhichEar, zp07InfantAssessmentVisit.getInfantWhichEar());
        cv.put(Zp07DBConstants.infantReferralAudio, zp07InfantAssessmentVisit.getInfantReferralAudio());
        cv.put(Zp07DBConstants.infantAdditionalAudio, zp07InfantAssessmentVisit.getInfantAdditionalAudio());
        cv.put(Zp07DBConstants.infatnHearLeft, zp07InfantAssessmentVisit.getInfatnHearLeft());
        cv.put(Zp07DBConstants.infantHearRight, zp07InfantAssessmentVisit.getInfantHearRight());
        cv.put(Zp07DBConstants.infantBreastfeeding, zp07InfantAssessmentVisit.getInfantBreastfeeding());
        cv.put(Zp07DBConstants.infantBreastReason, zp07InfantAssessmentVisit.getInfantBreastReason());
        cv.put(Zp07DBConstants.infantBreastOther, zp07InfantAssessmentVisit.getInfantBreastOther());
        cv.put(Zp07DBConstants.infantNeurodeve, zp07InfantAssessmentVisit.getInfantNeurodeve());
        cv.put(Zp07DBConstants.infantNeurodeveType, zp07InfantAssessmentVisit.getInfantNeurodeveType());
        cv.put(Zp07DBConstants.infantOtherSpecify, zp07InfantAssessmentVisit.getInfantOtherSpecify());
        cv.put(Zp07DBConstants.infantExhibited, zp07InfantAssessmentVisit.getInfantExhibited());
        cv.put(Zp07DBConstants.infantOtherMovement, zp07InfantAssessmentVisit.getInfantOtherMovement());
        cv.put(Zp07DBConstants.infantFurtherNeuro, zp07InfantAssessmentVisit.getInfantFurtherNeuro());
        cv.put(Zp07DBConstants.infantHeadAltra, zp07InfantAssessmentVisit.getInfantHeadAltra());
        cv.put(Zp07DBConstants.infantUltraObtained, zp07InfantAssessmentVisit.getInfantUltraObtained());
        if (zp07InfantAssessmentVisit.getInfantUltraDt()!=null) cv.put(Zp07DBConstants.infantUltraDt, zp07InfantAssessmentVisit.getInfantUltraDt().getTime());
        cv.put(Zp07DBConstants.infantResultsUltra, zp07InfantAssessmentVisit.getInfantResultsUltra());
        cv.put(Zp07DBConstants.infantResultsSpecify, zp07InfantAssessmentVisit.getInfantResultsSpecify());
        cv.put(Zp07DBConstants.infantHeadCt, zp07InfantAssessmentVisit.getInfantHeadCt());
        cv.put(Zp07DBConstants.infantCtObtained, zp07InfantAssessmentVisit.getInfantCtObtained());
        if (zp07InfantAssessmentVisit.getInfantCtDt()!=null) cv.put(Zp07DBConstants.infantCtDt, zp07InfantAssessmentVisit.getInfantCtDt().getTime());
        cv.put(Zp07DBConstants.infantResultsCt, zp07InfantAssessmentVisit.getInfantResultsCt());
        cv.put(Zp07DBConstants.infantCtSpecify, zp07InfantAssessmentVisit.getInfantCtSpecify());
        cv.put(Zp07DBConstants.infantCerebrospinal, zp07InfantAssessmentVisit.getInfantCerebrospinal());
        cv.put(Zp07DBConstants.infantCerebroStored, zp07InfantAssessmentVisit.getInfantCerebroStored());
        if (zp07InfantAssessmentVisit.getInfantCerebroDt()!=null)cv.put(Zp07DBConstants.infantCerebroDt, zp07InfantAssessmentVisit.getInfantCerebroDt().getTime());
        cv.put(Zp07DBConstants.infantCerebroAmount, zp07InfantAssessmentVisit.getInfantCerebroAmount());
        cv.put(Zp07DBConstants.infantResultsCerebro, zp07InfantAssessmentVisit.getInfantResultsCerebro());
        cv.put(Zp07DBConstants.infantCerebroSpecify, zp07InfantAssessmentVisit.getInfantCerebroSpecify());
        cv.put(Zp07DBConstants.infantMri, zp07InfantAssessmentVisit.getInfantMri());
        cv.put(Zp07DBConstants.infantMriObtained, zp07InfantAssessmentVisit.getInfantMriObtained());
        if (zp07InfantAssessmentVisit.getInfantMriDt()!=null) cv.put(Zp07DBConstants.infantMriDt, zp07InfantAssessmentVisit.getInfantMriDt().getTime());
        cv.put(Zp07DBConstants.infantResultsMri, zp07InfantAssessmentVisit.getInfantResultsMri());
        cv.put(Zp07DBConstants.infantMriSpecify, zp07InfantAssessmentVisit.getInfantMriSpecify());
        cv.put(Zp07DBConstants.infantPreviousResults, zp07InfantAssessmentVisit.getInfantPreviousResults());
        cv.put(Zp07DBConstants.infantReferrCounselling, zp07InfantAssessmentVisit.getInfantReferrCounselling());
        cv.put(Zp07DBConstants.infantOtherLabCollect, zp07InfantAssessmentVisit.getInfantOtherLabCollect());
        cv.put(Zp07DBConstants.infantIdCompleting, zp07InfantAssessmentVisit.getInfantIdCompleting());
        if (zp07InfantAssessmentVisit.getInfantDateCompleted()!=null) cv.put(Zp07DBConstants.infantDateCompleted, zp07InfantAssessmentVisit.getInfantDateCompleted().getTime());
        cv.put(Zp07DBConstants.infantIdReviewer, zp07InfantAssessmentVisit.getInfantIdReviewer());
        if (zp07InfantAssessmentVisit.getInfantDateReviewed()!=null) cv.put(Zp07DBConstants.infantDateReviewed, zp07InfantAssessmentVisit.getInfantDateReviewed().getTime());
        cv.put(Zp07DBConstants.infantIdDataEntry, zp07InfantAssessmentVisit.getInfantIdDataEntry());
        if (zp07InfantAssessmentVisit.getInfantDateEntered()!=null) cv.put(Zp07DBConstants.infantDateEntered, zp07InfantAssessmentVisit.getInfantDateEntered().getTime());


        if (zp07InfantAssessmentVisit.getRecordDate() != null) cv.put(MainDBConstants.recordDate, zp07InfantAssessmentVisit.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, zp07InfantAssessmentVisit.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(zp07InfantAssessmentVisit.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, zp07InfantAssessmentVisit.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, zp07InfantAssessmentVisit.getInstancePath());
        cv.put(MainDBConstants.STATUS, zp07InfantAssessmentVisit.getEstado());
        cv.put(MainDBConstants.START, zp07InfantAssessmentVisit.getStart());
        cv.put(MainDBConstants.END, zp07InfantAssessmentVisit.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, zp07InfantAssessmentVisit.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, zp07InfantAssessmentVisit.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, zp07InfantAssessmentVisit.getPhonenumber());
        if (zp07InfantAssessmentVisit.getToday() != null) cv.put(MainDBConstants.TODAY, zp07InfantAssessmentVisit.getToday().getTime());
        return cv;
    }

    public static Zp07InfantAssessmentVisit createZp07InfantAssessmentVisit(Cursor cursorIA){
        Zp07InfantAssessmentVisit infantAssessmentVisit = new Zp07InfantAssessmentVisit();
        infantAssessmentVisit.setRecordId(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.recordId)));
        infantAssessmentVisit.setRedcapEventName(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.redcapEventName)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate))>0) infantAssessmentVisit.setInfantVisitDate(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantVisitDate))));
        infantAssessmentVisit.setInfantStatus(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantStatus)));
        infantAssessmentVisit.setInfantVisit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantVisit)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantTemp))>0) infantAssessmentVisit.setInfantTemp(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantTemp)));
        infantAssessmentVisit.setInfantTmpUnit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantTmpUnit)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWt))>0) infantAssessmentVisit.setInfantWt(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWt)));
        infantAssessmentVisit.setInfantWtUnit(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWtUnit)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWtPercen))>0) infantAssessmentVisit.setInfantWtPercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantWtPercen)));
        infantAssessmentVisit.setInfantWtpercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWtpercenNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLength))>0) infantAssessmentVisit.setInfantLength(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLength)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLengthPercen))>0) infantAssessmentVisit.setInfantLengthPercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantLengthPercen)));
        infantAssessmentVisit.setInfantLenpercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLenpercenNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadcircu))>0) infantAssessmentVisit.setInfantHeadcircu(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadcircu)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercen))>0) infantAssessmentVisit.setInfantHeapercen(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercen)));
        infantAssessmentVisit.setInfantHeapercenNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeapercenNa)));
        infantAssessmentVisit.setInfantReferralNeuro(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferralNeuro)));
        infantAssessmentVisit.setInfantApgarNa(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantApgarNa)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar1min))>0) infantAssessmentVisit.setInfantApgar1min(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar1min)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar5min))>0) infantAssessmentVisit.setInfantApgar5min(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantApgar5min)));
        infantAssessmentVisit.setInfantSkinEvalu(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantSkinEvalu)));
        infantAssessmentVisit.setInfantRash(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantRash)));
        infantAssessmentVisit.setInfantScarring(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantScarring)));
        infantAssessmentVisit.setInfantOrganEvalu(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOrganEvalu)));
        infantAssessmentVisit.setInfantAbdominal(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantAbdominal)));
        infantAssessmentVisit.setInfantLiverSpleen(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantLiverSpleen)));
        infantAssessmentVisit.setInfantOphth(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOphth)));
        infantAssessmentVisit.setInfantOphthAbno(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOphthAbno)));
        infantAssessmentVisit.setInfantWhichEye(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWhichEye)));
        infantAssessmentVisit.setInfantEyeCalci(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantEyeCalci)));
        infantAssessmentVisit.setInfantChoriore(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantChoriore)));
        infantAssessmentVisit.setInfantEyeOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantEyeOther)));
        infantAssessmentVisit.setInfantOtherIssue(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherIssue)));
        infantAssessmentVisit.setInfantEyeOtherSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantEyeOtherSpecify)));
        infantAssessmentVisit.setInfantReferralOphth(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferralOphth)));
        infantAssessmentVisit.setInfantOae(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOae)));
        infantAssessmentVisit.setInfantOaeAbnormal(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOaeAbnormal)));
        infantAssessmentVisit.setInfantWhichEar(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantWhichEar)));
        infantAssessmentVisit.setInfantReferralAudio(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferralAudio)));
        infantAssessmentVisit.setInfantAdditionalAudio(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantAdditionalAudio)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infatnHearLeft))>0) infantAssessmentVisit.setInfatnHearLeft(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infatnHearLeft)));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHearRight))>0) infantAssessmentVisit.setInfantHearRight(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantHearRight)));
        infantAssessmentVisit.setInfantBreastfeeding(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastfeeding)));
        infantAssessmentVisit.setInfantBreastReason(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastReason)));
        infantAssessmentVisit.setInfantBreastOther(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantBreastOther)));
        infantAssessmentVisit.setInfantNeurodeve(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeurodeve)));
        infantAssessmentVisit.setInfantNeurodeveType(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantNeurodeveType)));
        infantAssessmentVisit.setInfantOtherSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherSpecify)));
        infantAssessmentVisit.setInfantExhibited(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantExhibited)));
        infantAssessmentVisit.setInfantOtherMovement(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherMovement)));
        infantAssessmentVisit.setInfantFurtherNeuro(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantFurtherNeuro)));
        infantAssessmentVisit.setInfantHeadAltra(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadAltra)));
        infantAssessmentVisit.setInfantUltraObtained(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantUltraObtained)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantUltraDt))>0) infantAssessmentVisit.setInfantUltraDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantUltraDt))));
        infantAssessmentVisit.setInfantResultsUltra(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultsUltra)));
        infantAssessmentVisit.setInfantResultsSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultsSpecify)));
        infantAssessmentVisit.setInfantHeadCt(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantHeadCt)));
        infantAssessmentVisit.setInfantCtObtained(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCtObtained)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantCtDt))>0) infantAssessmentVisit.setInfantCtDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantCtDt))));
        infantAssessmentVisit.setInfantResultsCt(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultsCt)));
        infantAssessmentVisit.setInfantCtSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCtSpecify)));
        infantAssessmentVisit.setInfantCerebrospinal(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebrospinal)));
        infantAssessmentVisit.setInfantCerebroStored(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroStored)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroDt))>0) infantAssessmentVisit.setInfantCerebroDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroDt))));
        if (cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroAmount))>0) infantAssessmentVisit.setInfantCerebroAmount(cursorIA.getFloat(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroAmount)));
        infantAssessmentVisit.setInfantResultsCerebro(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultsCerebro)));
        infantAssessmentVisit.setInfantCerebroSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantCerebroSpecify)));
        infantAssessmentVisit.setInfantMri(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMri)));
        infantAssessmentVisit.setInfantMriObtained(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMriObtained)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantMriDt))>0) infantAssessmentVisit.setInfantMriDt(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantMriDt))));
        infantAssessmentVisit.setInfantResultsMri(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantResultsMri)));
        infantAssessmentVisit.setInfantMriSpecify(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantMriSpecify)));
        infantAssessmentVisit.setInfantPreviousResults(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantPreviousResults)));
        infantAssessmentVisit.setInfantReferrCounselling(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantReferrCounselling)));
        infantAssessmentVisit.setInfantOtherLabCollect(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantOtherLabCollect)));
        infantAssessmentVisit.setInfantIdCompleting(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdCompleting)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateCompleted))>0) infantAssessmentVisit.setInfantDateCompleted(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateCompleted))));
        infantAssessmentVisit.setInfantIdReviewer(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdReviewer)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateReviewed))>0) infantAssessmentVisit.setInfantDateReviewed(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateReviewed))));
        infantAssessmentVisit.setInfantIdDataEntry(cursorIA.getString(cursorIA.getColumnIndex(Zp07DBConstants.infantIdDataEntry)));
        if (cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateEntered))>0) infantAssessmentVisit.setInfantDateEntered(new Date(cursorIA.getLong(cursorIA.getColumnIndex(Zp07DBConstants.infantDateEntered))));

        if(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.recordDate))>0) infantAssessmentVisit.setRecordDate(new Date(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.recordDate))));
        infantAssessmentVisit.setRecordUser(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.recordUser)));
        infantAssessmentVisit.setPasive(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        infantAssessmentVisit.setIdInstancia(cursorIA.getInt(cursorIA.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        infantAssessmentVisit.setInstancePath(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.FILE_PATH)));
        infantAssessmentVisit.setEstado(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.STATUS)));
        infantAssessmentVisit.setStart(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.START)));
        infantAssessmentVisit.setEnd(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.END)));
        infantAssessmentVisit.setSimserial(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        infantAssessmentVisit.setPhonenumber(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        infantAssessmentVisit.setDeviceid(cursorIA.getString(cursorIA.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.TODAY))>0) infantAssessmentVisit.setToday(new Date(cursorIA.getLong(cursorIA.getColumnIndex(MainDBConstants.TODAY))));

        return infantAssessmentVisit;
    }
}
